README.md
=> fix: Broken link in README

.github/workflows/pull_request.yaml, Makefile
upload code coverage to codecov.io on every PR
https://app.codecov.io/gh/openfga/openfga/new
=> chore: upload code coverage to codecov.io on every PR

storage/memory/memory.go
=> bug: Add timestamp to Tuple in MemoryDS

.github/workflows/codecov.yaml
So that we can see the report in the project's dashboard: https://app.codecov.io/gh/openfga/openfga
n/a
=> chore: add coverage report to main branch

.github/workflows/main.yaml, .github/workflows/pull_request.yaml, Makefile, server/queries/check_query.go
=> ci: Add performance regression check

cmd/openfga/openfga.go, cmd/openfga/openfga_test.go, go.mod, server/server.go
=> chore: add Close to service

.github/workflows/main.yaml, .github/workflows/pull_request.yaml
I think the current threshold is a bit too sensitive. Use the default.
=> ci: go-bench: use default threshold of 200%

.github/workflows/main.yaml, .github/workflows/pull_request.yaml
Simplify cache setup of Go dependencies as well as normalize cache action version.
=> Update actions cache handling

CHANGELOG.md
Adds the `v0.1.1` release details to the CHANGELOG.
=> docs: add `v0.1.1` release details to the CHANGELOG

Dockerfile, Dockerfile.goreleaser, README.md, docker-compose.yaml
=> fix: add run command to docker compose

server/server.go
This fixes an issue with request validation where requests weren't required to meet validation requirements.
=> fix: add request validation middleware to the server

Makefile, README.md, docker-compose.yaml, pkg/testfixtures/storage/postgres.go, storage/postgres/migrations/20220617_initialize_schema.down.sql, storage/postgres/migrations/20220617_initialize_schema.up.sql
Add a quick way to get up and running with Postgres. Of course we plan to expand on this with a `migrate` command.
=> chore: add postgres startup script

CHANGELOG.md
Adds the `v0.1.2` release details to the CHANGELOG.
=> docs: add v0.1.2 release details to the CHANGELOG

pkg/cmd/service/service_test.go
This PR replaces `os.Setenv` with `t.Setenv`. Starting from Go 1.17, we can use `t.Setenv` to set environment variable in test. The environment variable is automatically restored to its original value when the test and all its subtests complete. This ensures that each test does not start with leftover environment variables from previous completed tests.
Reference: https://pkg.go.dev/testing#T.Setenv
=> test: use `T.Setenv` to set env vars in tests

CHANGELOG.md
Add release details for `v0.1.3` release.
=> docs: add  CHANGELOG release details

CHANGELOG.md
Add the CHANGELOG entry for `v0.1.4`. This release replaces `v0.1.3` release.
=> docs: add  CHANGELOG release details for `v0.1.4` release

.config-schema.json, pkg/cmd/run.go, pkg/cmd/service/service.go, pkg/cmd/service/service_test.go, server/server.go
This binds the remaining flags for the OpenFGA server.
Closes #91
=> chore: bind remaining CLI flags

server/server.go
=> chore: add tracing to resolveAuthorizationModelID

CHANGELOG.md
Add the `v0.1.5` release details to the CHANGELOG in preparation for the release.
=> docs: add `v0.1.5` release details to the CHANGELOG

NOTICE
=> chore: update NOTICE file

server/commands/check.go, server/commands/check_utils.go
=> fix: goroutine leak

server/commands/check.go
=> chore: refactor resolveTupleToUserset so that it may exit earlier

pkg/cmd/service/service_test.go
=> fix: increase test timeout context

CHANGELOG.md
Updates the `v0.1.5` release notes based on the latest changes in main.
=> docs: update `v0.1.5` release notes

CHANGELOG.md
Add the `v0.1.6` release details to the CHANGELOG.
=> docs: add `v0.1.6` release details to the CHANGELOG

CHANGELOG.md
This adds the `v0.1.7` release details to the CHANGELOG.
=> docs: add `v0.1.7` release details to the CHANGELOG

go.mod, go.sum
This PR bumps some go modules to their latest package.
=> chore: bump go modules

go.mod, go.sum, internal/middleware/http/handler_test.go, pkg/cmd/service/service_test.go, server/authn/oidc/oidc.go, server/commands/list_objects.go, server/test/check.go, server/test/list_objects.go, storage/memory/memory.go, storage/mocks/mock_storage.go, storage/postgres/iterators.go, storage/storage.go
Update our code base after https://github.com/openfga/api/pull/24 was merged
=> chore: use "object" proto

README.md
- Fixed title for Production Readiness.
=> chore: fixed title

README.md
- Added OpenSSF Best Practices badge
- Removed Snyk badge as it was not working
- Removed the Apache License badge as it's redundant
=> chore: updated badges

server/commands/list_objects.go, server/test/list_objects.go
=> fix: respect the value of ListObjectsMaxResults

server/test/list_objects.go
Follow-up to https://github.com/openfga/openfga/pull/145#issuecomment-1211066407
=> chore: add a test for ListObjects, the streaming version

server/commands/list_objects.go
Follow-up to https://github.com/openfga/openfga/pull/181
=> fix: improve pointer handling in ListObjects API

docker-compose.yaml
=> refactor: use long form of depends_on in docker compose file

storage/postgres/utils_test.go
=> refactor: use require in a few more test places

server/commands/write_authzmodel.go, server/test/write_authzmodel.go
There is a bug in authorization model validation. This fixes it.
=> fix: authorization model validation

go.mod, go.sum, server/test/write_authzmodel.go
=> chore: update api

pkg/cmd/migrate.go
If there is no return in the if then it always goes to the next line which migrates up to the latest version.
=> fix: bug in migrate

server/test/write_authzmodel.go
=> refactor: rename _name to name

CHANGELOG.md
Add the `v0.2.2` release details to the changelog.
=> docs: add v0.2.2 release details to the CHANGELOG

cmd/openfga/openfga_test.go, pkg/id/id.go, pkg/testutils/testutils.go, server/server_test.go, server/test/check.go, server/test/expand.go, server/test/list_objects.go, server/test/read.go, server/test/read_authzmodel.go, server/test/read_authzmodels.go, server/test/read_tuples.go, server/test/write.go, storage/caching/caching_test.go, storage/test/assertions.go, storage/test/authz_models.go, storage/test/storage.go, storage/test/stores.go
Add Must which is useful for testing and use the default entropy.
Also, since store ids will soon be required to be ulids, update these where I found them.
=> chore: update ulid package

server/server_test.go
Adds MySQL to the server test suite.
=> chore: add MySQL to the server test suite

CHANGELOG.md, server/commands/check.go
Release details for upcoming `v0.2.4` release.
=> docs: add `v0.2.4` release details

CHANGELOG.md
Add some more missing info from the CHANGELOG notice for the `v0.2.4` release.
=> docs: add more release details to `v0.2.4` CHANGELOG entry

cmd/run.go, cmd/run_test.go
This function may panic so add `Must` to indicate this.
=> rename: DefaultConfigWithRandomPorts -> MustDefaultConfigWithRandomPorts

CHANGELOG.md
Add `v0.2.5` release details to CHANGELOG.
=> docs: add `v0.2.5` release details to CHANGELOG

.github/workflows/pull_request.yaml, Makefile, tools/go.mod, tools/go.sum, tools/tools.go
=> ci: add govulncheck

storage/test/tuples.go
=> refactor: tuple tests to use require

Makefile, go.mod, go.sum, internal/graph/graph.go, internal/graph/graph_test.go, pkg/typesystem/typesystem.go, pkg/typesystem/typesystem_test.go, server/commands/connected_objects.go, server/test/check.go, server/test/connected_objects.go, server/test/list_objects.go, server/test/write.go
=> chore: update api dependency with wildcards

.dockerignore, .github/workflows/main.yaml, .github/workflows/pull_request.yaml, Dockerfile, server/commands/read.go
Update dangling refs to Go 19.3 as well.
=> chore: update error message

server/commands/check.go, server/commands/expand.go, server/commands/read_assertions.go, server/commands/read_authzmodel.go
Refactor receivers in commands to all have a short name. E.g., `query` --> `q`.
=> style: consistent short name receivers

server/commands/list_objects.go, server/server_test.go
This is until support for 1.1 models is fully complete.
=> chore: temporarily disable ListObjects, the optimized version

server/test/connected_objects.go
Refactor the ConnectedObjects tests to use DSL strings for the models instead of protobuf structs.
=> test: ConnectedObjects test refactor

CHANGELOG.md
Add the `v0.3.1` release notes to the CHANGELOG.
=> docs: add `v0.3.1` release notes to CHANGELOG

tests/oldcheck/check_test.go
=> chore: turn off logs in 1.0 check tests

CHANGELOG.md
Add CVE reference for a recent security patch to the `v0.3.1` CHANGELOG entry.
=> docs: add CVE reference to `v0.3.1` CHANGELOG entry

tests/check/tests.yaml
=> chore: add a forgotten test

.github/workflows/release.yaml
This PR proposes changes to update the Dockerhub readme with every release.
- GH Action Used: [peter-evans/dockerhub-description](https://github.com/peter-evans/dockerhub-description)
- No Action Required. Because `DOCKERHUB_USERNAME` & `DOCKERHUB_TOKEN` was already available in secrets. Using the same for this.
- `repository` is just the `owner_name/repo_name`
- `short-description` Syncs up the GitHub Repo. Description with Dockerhub description.
- #207
> Signed-off-by: Siddhant Khare <Siddhantkhare2694@gmail.com>
=> ci: automated readme updation with docker release

CHANGELOG.md
Add the `v0.3.2` release notes to the CHANGELOG.
=> docs: add `v0.3.2` release notes to the CHANGELOG

README.md
We've finalized our auth refactor and have been running OpenFGA in production for a few weeks now.
=> Update README to reflect production usage

cmd/run.go, go.mod, go.sum, internal/middleware/middleware.go, internal/middleware/requestid.go, internal/middleware/requestid_test.go
=> feat: request id middleware

.config-schema.json, pkg/server/server.go, pkg/server/server_test.go
=> refactor: make optimized list objects the default

internal/validation/validation.go, pkg/server/commands/check.go, pkg/server/commands/check_utils.go, pkg/server/commands/expand.go, pkg/storage/mocks/mock_storage.go
=> refactor: take typesystem in FilterInvalidTuples

.config-schema.json, cmd/run.go
As part of this we should also update https://github.com/openfga/openfga.dev/blob/main/docs/content/getting-started/production-best-practices.mdx with some guidance.
=> chore: reasonable db defaults

docker-compose.yaml
=> fix: docker compose environment variable

pkg/server/commands/write.go, pkg/server/server.go
=> fix: ensure span names are the function names

docker-compose.yaml
Update docker compose file to be more in line to the example illustrated in docs.
To be more in line with https://github.com/openfga/openfga.dev/pull/360
=> chore: update docker compose file to use env variables

.github/workflows/release-nightly.yaml, .github/workflows/release.yaml, .goreleaser-nightly.yaml
This PR proposes changes to adding a CI to create a nightly release for OpenFGA
fixes #76
=> ci:  OpenFGA nightly release :sparkles:

Dockerfile.goreleaser
Fix `apk add` command in Dockerfile for goreleaser.
=> ci: fix goreleaser dockerfile

CHANGELOG.md
Add the `v0.3.7` release notes to the CHANGELOG.
=> docs: add `v0.3.7` release notes to the CHANGELOG

telemetry/otel-collector-config.yaml
Tuning of OTEL parameters for retry/memory etc.
=> feat: tuning of OTEL parameters

README.md
=> chore(docs): note that go1.19 is needed for compiling from source

assets/tests/consolidated_1_1_tests.yaml
adding additional functional test for list object
Close https://github.com/openfga/openfga/issues/607
=> chore: add additional functional test

pkg/server/server_test.go
Makes use of the `Server` constructor to construct a Server instance that we use in tests. This allows us to reduce the amount of manual boilerplate code that we have to remember to setup each time we construct a server.
=> test: refactor server tests to use Server constructor

pkg/server/commands/connected_objects.go, pkg/server/test/list_objects.go
- Fix test setup (https://github.com/openfga/openfga/issues/619)
- Remove unused code path
- Add coverage for this code block https://github.com/openfga/openfga/blob/3a032d1346a6065f5a1cf8c9970fc3450977d91a/pkg/server/commands/connected_objects.go#L542-L544
=> fix: list objects test setup

.github/workflows/main.yaml, .github/workflows/pull_request.yaml
Follow-up of https://github.com/openfga/openfga/pull/614
=> chore: mark benchmark step as failure if status code is not 0

pkg/server/commands/write_authzmodel.go, pkg/typesystem/typesystem.go, pkg/typesystem/typesystem_test.go
This should reduce memory usage.
=> chore: refactor typesystem

cmd/openfga/main_test.go, pkg/testfixtures/storage/mysql.go, pkg/testfixtures/storage/postgres.go
To debug these failures https://github.com/openfga/openfga/actions/runs/4390160212/jobs/7688394238
=> chore: add testing logs

pkg/storage/mysql/mysql.go
Follow-up of https://github.com/openfga/openfga/pull/631
=> fix: remove sort from ReadUsersetTuples in mysql

internal/graph/check.go
Fixes https://github.com/openfga/openfga/issues/615
Changes:
- The inner-most `span` that found the Check resolution will now have the attribute `allowed:true`. This helps visually identify which path led to the resolution (similar to the UI in the playground)
- I renamed a few spans because they made more sense visually
- I added a few attributes to some spans to help debugging
=> fix: tracing in Check API

CHANGELOG.md
=> chore(docs): add `v0.4.0` release notes to the changelog

CHANGELOG.md
=> chore(docs): add `v0.4.1` release notes to the changelog

internal/graph/graph.go, internal/graph/graph_test.go
Fixes broken build: https://github.com/openfga/openfga/actions/runs/4536794174/jobs/7993912100?pr=658#step:7:24
=> fix: broken unit test

README.md
Adding link to community meetings
=> Add community meetings to README

README.md
=> chore: revise wording of community meetings reference

.github/workflows/release-nightly.yaml, .github/workflows/release.yaml
Follow up of https://github.com/openfga/openfga/pull/684
=> fix: github workflows token permissions (part 2)

CHANGELOG.md
Adds the `v0.4.3` release notes to the CHANGELOG.
=> docs: add `v0.4.3` release details to CHANGELOG

.github/workflows/release-nightly.yaml, .github/workflows/release.yaml
=> ci: fix permissions for release workflows

Dockerfile, Dockerfile.goreleaser, docker-compose.yaml
A recent change to the `chainguard/static` image changed base permissions on the root `/bin` directory. This broke our gRPC health probe binary. 
```
docker run --entrypoint /bin/grpc_health_probe openfga/openfga:latest-arm64 -addr localhost:50051
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/bin/grpc_health_probe": stat /bin/grpc_health_probe: permission denied: unknown.
```
This changes the location of the gRPC health probe binary to `/usr/local/bin` to fix this issue and to avoid issues like this in the future.
To test these changes out you can run:
```shell
$ goreleaser release --clean --snapshot
$ docker run --entrypoint /usr/local/bin/grpc_health_probe …
```
=> ci: fix image builds with latest chainguard/static image

README.md
=> chore(docs): add link to adopters file

pkg/typesystem/typesystem.go
This is a follow-up of https://github.com/openfga/openfga/pull/726
=> refactor: remove `typesystem.allRelations()`

.github/workflows/scorecard.yml, README.md
Add in openssf scorecard
Close https://github.com/openfga/openfga/issues/737
=> chore(ci): integrate openssf scorecard

.github/dependabot.yaml
This PR sets up dependabot to update github actions and unblocks https://github.com/openfga/openfga/pull/739
=> chore(ci): configure dependabot to update github actions

CHANGELOG.md
Add `v1.1.0` release notes to the changelogs.
- [Notice: Deprecation of Schema Version 1.0 Models](https://github.com/orgs/openfga/discussions/111)
=> chore(docs): add `v1.1.0` release notes to the changelog

.github/workflows/release.yaml
Update the Goreleaser Github token to use a token with the appropriate scopes for this repo and the homebrew-tap repo.
=> ci: update goreleaser token

.github/workflows/pull_request.yaml
=> chore(ci): run PR workflow on merge queue

.fossa.yml
=> chore(legal): exclude notice file from fossa

assets/tests/consolidated_1_1_tests.yaml
Add a list objects test for somewhat complex authz model with multiple. traversal paths
=> chore(tests): add complex list objects test

CHANGELOG.md
Add the `v1.1.1` release notes to the CHANGELOG in preparation for the `v1.1.1` release.
=> docs: add `v1.1.1` release notes to the CHANGELOG

assets/tests/consolidated_1_1_tests.yaml, tests/check/check.go, tests/listobjects/listobjects.go
=> chore(tests): re-add complex list objects test, chunking write tuples into 40

CHANGELOG.md
Add the `v1.2.0` release details to the CHANGELOG in preparation for the upcoming release.
=> docs: add `v1.2.0` release details to the CHANGELOG

README.md
Fix broken links
Closes https://github.com/openfga/openfga/issues/836
=> fix: links in readme (#836)

.golangci.yaml, cmd/openfga/main_test.go
Add build-tags: [functional] to .golangci.yaml  And fix the issues caused by the introduction
Add build-tags: [functional] to .golangci.yaml
#777
=> fix:Add build-tags: [functional] to .golangci.yaml

telemetry/grafana/dashboards/openfga.json
=> fix: graphs in Grafana dashboard

internal/graph/check.go, internal/graph/check_test.go, pkg/server/commands/connected_objects.go, pkg/server/commands/list_objects.go, pkg/server/server.go, pkg/server/test/connected_objects.go, pkg/server/test/list_objects.go, pkg/server/test/server.go
Update:
- Check
- ListObjects
- ConnectedObjects
Follow-up of https://github.com/openfga/openfga/pull/833
=> refactor: add constructors for checker, list objects, connected objects

CHANGELOG.md
Add the `v1.3.0` release notes to the CHANGELOG in preparation for the upcoming release.
=> docs(release): add `v1.3.0` release notes to the CHANGELOG

go.mod, pkg/server/server.go, pkg/typesystem/typesystem.go
- This PR applies [slices](https://pkg.go.dev/slices) and [maps](https://pkg.go.dev/maps) builtin packages from go1.21.
=> refactor: use slices and maps packages from go1.21

pkg/storage/test/storage.go, pkg/storage/test/tuples.go
=> test: add tests for datastore.Read

.github/dependabot.yaml
=> chore: group dependabot dependency upgrades, and bump tp weekly

assets/tests/consolidated_1_1_tests.yaml
This is a follow-up of https://github.com/openfga/openfga/pull/921.
=> test: add integration test for ListObjects

tests/check/check.go, tests/listobjects/listobjects.go
This PR should aid in debugging https://github.com/openfga/openfga/issues/892
=> test: add logs to debug easily

pkg/typesystem/typesystem.go, pkg/typesystem/typesystem_test.go
- Removing dead code that is never hit because `typesystem.hasNoEntrypoints()` already covers it: https://app.codecov.io/gh/openfga/openfga/blob/main/pkg%2Ftypesystem%2Ftypesystem.go <img width="1727" alt="image" src="https://github.com/openfga/openfga/assets/5374887/7048f6e3-98af-4b7b-a9d4-92d49ba918d9">
- Added more unit tests
=> chore: remove unused code in typesystem

internal/graph/check.go
remove unused variable and make linting happy again
https://github.com/openfga/openfga/commit/725296025fd81227c89525808652c6acd4a605f6
=> fix: remove unused variable

CHANGELOG.md
Release for upcoming v1.3.3
https://github.com/openfga/openfga/compare/v1.3.2...HEAD
=> docs(release): add v1.3.3 release notes

SECURITY-INSIGHTS.yml
- ref: https://github.com/ossf/security-insights-spec/blob/v1.0.0/specification.md
=> chore(docs): add security insights

.github/workflows/main.yaml
Follow-up of https://github.com/openfga/openfga/pull/1069 😅
=> fix: amend #1069

.github/workflows/pull_request.yaml
**Context:** In the process of continuous integration and deployment, a significant amount of time is often spent by developers in tracing through CI logs to debug issues. The default naming convention of CI steps in the Actions tab makes it a bit difficult to quickly identify and navigate through logs for specific steps.
| Before | After |
|--------|--------|
| <img width="788" alt="Screenshot 2023-10-23 at 11 04 43 PM" src="https://github.com/openfga/openfga/assets/55068936/d932fc9e-6d46-4033-9d60-f9fe81732c59"> | <img width="1152" alt="image" src="https://github.com/openfga/openfga/assets/55068936/b9190067-b0b8-44c2-ae22-576aa520c0aa"> | 
**Changes Introduced:** Each CI step now has a relative, descriptive name.
**Benefits - Enhanced DevX**: Developers can now easily locate and …
=> CI: Improve CI Log Traceability by Naming CI Steps

.github/workflows/release.yaml
Scan docker image after release and upload results to Github Code Scanning
=> chore: add scanning of docker image via snyk

tests/check/check_test.go
Attempt to reduce benchmark speed variability such as seen in 
- https://github.com/openfga/openfga/actions/runs/6647307802/job/18062457154?pr=1081#step:7:21
- https://github.com/openfga/openfga/actions/runs/6646945916/job/18061397034#step:7:20
Fetching the model can mean a cache hit or a miss.
=> test: Check benchmarks pass in auth model ID

CHANGELOG.md
=> chore: update release notes for v1.3.5

.github/workflows/release.yaml
`security-events: write` is required in order to upload snyk scan results to GitHub Code Scanning
https://github.com/openfga/openfga/actions/runs/6660183755/job/18100821561
```
RequestError [HttpError]: Resource not accessible by integration
at /home/runner/work/_actions/github/codeql-action/v2/node_modules/@octokit/request/dist-node/index.js:86:21
at processTicksAndRejections (node:internal/process/task_queues:[9](https://github.com/openfga/openfga/actions/runs/6660183755/job/18100821561#step:12:10)6:5)
at async requestWithGraphqlErrorHandling (/home/runner/work/_actions/github/codeql-action/v2/node_modules/@octokit/plugin-retry/dist-node/index.js:71:20)
at async Job.doExecute (/home/runner/work/_actions/github/codeql-action/v2/node_modules/bottleneck/light.js:405:18) {
status: 403, …
```
=> ci: add missing permission on release job

internal/graph/cached_resolver_test.go
Add a benchmark for Check request cache key computation.
=> test(bench): add benchmark for computing Check request cache keys

assets/tests/consolidated_1_1_tests.yaml, internal/test/listobjects/listobjects.go, tests/check/check.go, tests/listobjects/listobjects.go
Wires up context for ABAC testing in our consolidated test suite.
=> test(abac): wire up request context for ABAC tests

assets/tests/consolidated_1_1_tests.yaml, go.mod, go.sum, internal/test/check/check.go, internal/test/listobjects/listobjects.go, tests/check/check.go, tests/listobjects/listobjects.go
Add some tests for ABAC Condition scenarios.
=> test(abac): add basic ABAC tests

pkg/condition/eval/eval.go, pkg/condition/eval/eval_test.go, pkg/tuple/tuple.go, pkg/typesystem/typesystem.go
=> fix: error handling in evaluating conditions

internal/graph/check.go, pkg/server/commands/list_objects.go, pkg/server/commands/reverseexpand/reverse_expand.go
=> fix(error): error handling with conditional eval

README.md
Made codecov shield link to codecov report
=> docs(readme): make codecov link to codecov report

SECURITY-INSIGHTS.yml
=> chore: Update SECURITY-INSIGHTS.yml

CHANGELOG.md
Add `v1.3.6` release notes to the CHANGELOG.
=> docs(changelog): add `v1.3.6` release notes

README.md
=> chore: adding SLSA Level 3 Badge

CHANGELOG.md
CHANGELOG release notes for `v1.3.7`.
=> docs(release): `v1.3.7` release notes

pkg/storage/mysql/mysql.go, pkg/storage/postgres/postgres.go, pkg/storage/test/tuples.go
Propagate condition name and context to tuples on `ReadChanges`
https://github.com/openfga/openfga/pull/1038
=> feat: support conditions in ReadChanges

pkg/server/commands/create_store.go, pkg/server/commands/delete_store.go, pkg/server/commands/expand.go, pkg/server/commands/get_store.go, pkg/server/commands/list_stores.go, pkg/server/commands/read.go, pkg/server/commands/read_assertions.go, pkg/server/commands/read_authzmodel.go, pkg/server/commands/read_authzmodels.go, pkg/server/commands/read_changes.go, pkg/server/commands/write.go, pkg/server/commands/write_assertions.go, pkg/server/commands/write_authzmodel.go, pkg/server/commands/write_test.go, pkg/server/server.go, pkg/server/server_test.go, pkg/server/test/create_store.go, pkg/server/test/delete_store.go, pkg/server/test/expand.go, pkg/server/test/get_store.go, pkg/server/test/list_stores.go, pkg/server/test/read.go, pkg/server/test/read_assertions.go, pkg/server/test/read_authzmodel.go, pkg/server/test/read_authzmodels.go, pkg/server/test/read_changes.go, pkg/server/test/write.go, pkg/server/test/write_assertions.go, pkg/server/test/write_authzmodel.go
This PR addresses https://github.com/openfga/openfga/issues/1039 by adding Options to command constructors
=> refactor: Option builder for command constructors

.github/workflows/main.yaml, .github/workflows/pull_request.yaml
Only compare benchmarks if the CPUs are the same. Closes https://github.com/openfga/openfga/issues/1116
Tested in https://github.com/miparnisari/benchtest/pull/24
=> ci: only compare benchmarks if the CPUs are the same

internal/validation/validation_test.go, pkg/typesystem/typesystem.go
Closes https://github.com/openfga/openfga/issues/1104
=> perf: improve tuple validation by precomputing TTUs

internal/condition/condition.go, internal/condition/eval/eval.go, internal/condition/eval/eval_test.go
https://github.com/openfga/openfga/pull/1038
https://github.com/openfga/openfga/pull/1038#discussion_r1406705543
https://github.com/openfga/openfga/pull/1038#discussion_r1406652174
=> chore: update outdated comments

pkg/storage/memory/memory.go, pkg/storage/mysql/mysql.go, pkg/storage/postgres/postgres.go, pkg/storage/record.go, pkg/storage/test/tuples.go, pkg/tuple/tuple.go
=> refactor: use tuple util for more consistency

pkg/server/commands/write.go
=> pkg/server/commands: Don't crash when processing a a nil set of writes

pkg/storage/mysql/mysql.go, pkg/storage/mysql/mysql_test.go, pkg/storage/postgres/postgres.go, pkg/storage/postgres/postgres_test.go, pkg/storage/sqlcommon/sqlcommon.go
=> fix: handle converting NULL to string condition name

pkg/server/commands/write.go, pkg/server/commands/write_test.go, pkg/server/test/write.go, pkg/server/test/write_authzmodel.go
Quick follow-up of https://github.com/openfga/openfga/pull/1208
Suggestion to reviewers:
=> test: add more tests for Write and WriteAuthorizationModel API

CHANGELOG.md
Add `v1.3.9` release details to CHANGELOG
=> docs(release): add `v1.3.9` release details to CHANGELOG

CHANGELOG.md
Add `v1.3.10` release details to CHANGELOG
=> docs(release): add v1.3.10 release notes

Dockerfile
Updates `github.com/grpc-ecosystem/grpc-health-probe` from `v0.4.22` to `v0.4.23`
https://github.com/grpc-ecosystem/grpc-health-probe/releases/tag/v0.4.23
=> chore(deps): bump github.com/grpc-ecosystem/grpc-health-probe

pkg/server/commands/reverseexpand/reverse_expand.go
=> fix: missing span in ListObjects

internal/graph/check.go
This is just something minor that I noticed while doing something else
=> style: delegates in check

internal/condition/condition.go, internal/condition/eval/eval.go, internal/condition/eval/eval_test.go, internal/graph/check.go, pkg/server/commands/reverseexpand/reverse_expand.go
Add span info to traces for Condition evaluation results. See the screenshots for examples.
=> chore(tracing): add span info for Condition evaluation

.github/CODEOWNERS
=> chore: change CODEOWNERS team to BE team

pkg/encoder/base64.go, pkg/encoder/doc.go, pkg/encoder/encoder.go, pkg/encoder/token_encoder.go
This PR is part of a series of PRs aimed at improving the documentation of our publicly exported packages. 
Once all exported structs, vars, funcs are documented we can proceed with enforcing these good practices through the `golangci` linter configuration by enabling the `revive` and `stylecheck` linters.
- https://pkg.go.dev/github.com/openfga/openfga
- https://go.dev/doc/comment
=> docs: update encoder package documentation

pkg/encrypter/doc.go, pkg/encrypter/encrypter.go, pkg/encrypter/gcm_encrypter.go
This PR is part of a series of PRs aimed at improving the documentation of our publicly exported packages. 
Once all exported structs, vars, funcs are documented we can proceed with enforcing these good practices through the `golangci` linter configuration by enabling the `revive` and `stylecheck` linters.
- https://github.com/openfga/openfga/pull/1261
=> docs: update encrypter package documentation

pkg/typesystem/doc.go, pkg/typesystem/error.go, pkg/typesystem/resolver.go, pkg/typesystem/typesystem.go
This PR is part of a series of PRs aimed at improving the documentation of our publicly exported packages. 
Once all exported structs, vars, funcs are documented we can proceed with enforcing these good practices through the `golangci` linter configuration by enabling the `revive` and `stylecheck` linters.
- https://github.com/openfga/openfga/pull/1261
- https://github.com/openfga/openfga/pull/1263
=> docs: update typesystem package documentation

CHANGELOG.md
Add `v1.4.1` release details to the CHANGELOG.
=> docs(v1.4.1): add `v1.4.1` release notes to CHANGELOG

CHANGELOG.md
=> docs(v1.4.3): add v1.4.3 release notes to CHANGELOG

cmd/util/util.go, pkg/server/server_test.go, pkg/testfixtures/storage/storage.go
- Noticed in https://github.com/openfga/openfga/pull/1356 that we have a duplicate test helper. This PR removes it.
- Address remaining feedback about `t.Fatalf`
=> test: remove duplicate helper

README.md
=> chore(docs): update docker badge in the README

.github/CODEOWNERS, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/report_a_bug.yml, README.md, docs/security-self-assessment.md
=> chore: point to our community page instead of discord

pkg/storage/test/authz_models.go
As follow up on https://github.com/openfga/openfga/pull/1387, we want to also test the cases where 3 authorization models are written for the same store.
Follow up for https://github.com/openfga/openfga/pull/1387
=> test: update FindLatestAuthorizationModelTest to test 3 authz models

.semgrepignore, .snyk
This PR reduces the number of false detections returned by Snyk and Semgrep code scanning.
This PR adds `.snyk` and `.semgrepignore` files with disallow lists to filter out unit tests and documentation to reduce the false detections identified by Snyk and Semgrep code scanners.
N/A
=> ci: exclude tests from code scanners

README.md
=> chore: link to better scorecard visualization

.github/workflows/codecov.yaml, .github/workflows/pull_request.yaml
Fix https://github.com/openfga/openfga/actions/runs/8147186389/job/22267316633
```shell
debug - 2024-03-04 21:25:54,854 -- Starting create commit process --- {"commit_sha": "b8252cec5efca6a449029991a121913b4099b7a8", "parent_sha": null, "pr": null, "branch": "main", "slug": "openfga/openfga", "token": null, "service": "github", "enterprise_url": null}
Error: Codecov token not found. Please provide Codecov token with -t flag.
Warning: Codecov: Failed to properly create commit: The process '/home/runner/work/_actions/codecov/codecov-action/0cfda1dd0a4ad9efc75[51](https://github.com/openfga/openfga/actions/runs/8147605900/job/22268699931#step:5:52)7f399d859cd1ea4ced1/dist/codecov' failed with exit code 1
```
I uploaded a new secret `CODECOV_TOKEN` in …
=> ci: fix upload of coverage to codecov

README.md
=> chore: minor fixes

assets/tests/consolidated_1_1_tests.yaml, pkg/server/commands/listusers/list_users.go, pkg/server/commands/listusers/list_users_rpc.go, pkg/server/commands/listusers/list_users_rpc_test.go
Avoid stack overflows caused by loops in ListUsers API.
=> listusers: avoid stack overflows

SECURITY-INSIGHTS.yml
=> chore: update SECURITY-INSIGHTS

assets/tests/consolidated_1_1_tests.yaml, pkg/server/commands/listusers/list_users_rpc.go
Add assertions for ListUsers API in models that contain `intersection`.
=> `ListUsers` integration tests for intersection

assets/tests/consolidated_1_1_tests.yaml
Add assertions for ListUsers API in models that contain `exclusion`.
=> `ListUsers` integration tests for exclusion

.github/workflows/release.yaml
#780 is not needed anymore (and it doesn't work 😢 )
=> revert #780 (homebrew bump after every release)

internal/graph/check.go, internal/graph/check_test.go, internal/graph/cycle_check_resolver_test.go, internal/graph/interface.go
Fixing a panic that occurs on some cases where the model has cycles and exclusion is involved.
The panic was introduced in https://github.com/openfga/openfga/pull/1372
=> fix: check cycle detection with exclusion

pkg/server/test/expand.go
In preparation for https://github.com/openfga/openfga/pull/1521, add more tests (starting in line 568) asserting the current behavior of Expand API.
https://github.com/openfga/rfcs/pull/23, specifically addressing https://github.com/openfga/rfcs/pull/23#discussion_r1546394083
=> test: add Expand tests

internal/graph/cached_resolver.go, internal/graph/check.go, internal/graph/cycle_check_resolver.go, pkg/server/server.go
This is so that we can make more specific queries for traces when debugging a particular store's performance.
=> chore: add store_id as span attribute for check

pkg/typesystem/typesystem_test.go
Model validation is on the critical path ([we do it every time we fetch a model](https://github.com/openfga/openfga/blob/3fef4891e02cd7394a2e3513fff89c22c3814cee/pkg/typesystem/resolver.go#L83-L92), which includes Check API).
Cycle detection is CPU intensive.
`typesystem.HasCycle` and `typesystem.hasEntrypoints` both try to detect the same kind of cycles. The reason we duplicated it is because first we run `hasEntrypoints`, THEN we run `HasCycles`. There is no reason to do this, because `ErrNoEntryPointsLoop == ErrCycle`
if X is the number of total relations in the model,
- hasEntrypoints is called X times, (so we are doing cycle detection X times)
- hasCycles is called X times too
We should improve this.
=> chore: add benchmark for model validation

assets/tests/abac_tests.yaml, tests/check/check.go, tests/listobjects/listobjects.go
1. Address https://github.com/openfga/openfga/pull/1515#discussion_r1572949057
2. Create sub-tests for each stage and each assertion
=> chore: add abac tests

assets/tests/consolidated_1_1_tests.yaml, go.mod, go.sum, internal/graph/cycle_check_resolver_test.go, pkg/middleware/requestid/requestid.go, tests/check/check.go, tests/listobjects/listobjects.go
- Remove "github.com/craigpastro/openfga-dsl-parser/v2"
=> chore: remove old parser

cmd/openfga/main_test.go, cmd/run/run_test.go, pkg/testutils/testutils.go, tests/functional_test.go, tests/tests.go
Fix flaky test seen in https://github.com/openfga/openfga/actions/runs/8915815591/job/24486664293?pr=1576
=> test: always ensure health check

pkg/storage/storagewrappers/boundedconcurrency.go
If context is cancelled, we still want to measure how much time the goroutine was waiting for.
=> amend #1593

pkg/server/server.go, pkg/server/server_test.go
All server validations must run before any long-lasting resources are created.
=> chore: fix leak on server validation errors

pkg/server/commands/listusers/list_users.go, pkg/server/commands/listusers/list_users_rpc.go, pkg/server/commands/listusers/list_users_rpc_test.go, pkg/server/list_users.go, tests/listusers/listusers_test.go
Implemented DispatchCount metrics for list users. This will be useful when throttling is implemented. Since we don't have the throttling PR merged, that hasn't been implemented but it should be simple since we have the counter logic now.
=> feat(list-users): Implement dispatch count for list users

pkg/server/commands/list_objects.go, pkg/server/commands/list_objects_test.go, pkg/server/server.go
When delegating to check, pass the `consistency` param. Tests are not included in this PR; will follow with separate PR. This enables us to unblock storage interface changes work.
- #1695
=> feat: skip cache on list objects (when delegating to check)

cmd/run/run_test.go, go.mod, go.sum
Solves failure in https://github.com/openfga/openfga/actions/runs/9770805280/job/26972564360?pr=1636
```
=== Symbol Results ===
Vulnerability #1: GO-2024-2963
Denial of service due to improper 100-continue handling in net/http
More info: https://pkg.go.dev/vuln/GO-2024-2963
Standard library
Found in: net/http@go1.22.4
Fixed in: net/http@go1.22.5
Example traces found:
Error:       #1: pkg/testutils/testutils.go:220:33: testutils.EnsureServiceHealthy calls retryablehttp.Get, which eventually calls http.Client.CloseIdleConnections
Error:       #2: internal/authn/oidc/oidc.go:170:32: oidc.RemoteOidcAuthenticator.GetConfiguration calls http.Client.Do
Error:       #3: internal/condition/condition.go:69:18: condition.EvaluableCondition.Compile calls sync.Once.Do, which eventually calls http.Get …
```
=> chore: update to go 1.22.5

pkg/typesystem/typesystem.go, pkg/typesystem/typesystem_test.go
https://github.com/openfga/openfga/pull/1715
https://github.com/openfga/openfga/pull/1725
https://github.com/openfga/openfga/pull/1735
https://github.com/openfga/openfga/pull/1734
=> chore: TypeSystem methods to determine if Relation resolves to Directly Assignable Types

README.md
=> chore: change link to example for running as a library

cmd/run/run.go, pkg/middleware/recovery/recovery.go, pkg/middleware/recovery/recovery_test.go
- Use `github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/recovery` which is maintained in go-grpc-middleware v2
=> chore: use `github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/recovery`

assets/tests/consolidated_1_1_tests.yaml, internal/graph/check.go, pkg/server/commands/listusers/list_users_rpc.go, pkg/typesystem/typesystem.go, pkg/typesystem/typesystem_test.go
Close https://github.com/openfga/openfga/issues/1766
=> fix(check,listusers): if TTU relation is undefined, don't error

CHANGELOG.md
Updating changelog for upcoming 1.5.6 release.
=> docs(v1.5.6): add v1.5.6 release notes to CHANGELOG

assets/tests/abac_tests.yaml, assets/tests/consolidated_1_1_tests.yaml, internal/graph/check.go
Add additional test cases for testing userset and TTU.  In additional, add error traces in some error cases.
=> tests: add additional test cases

pkg/server/test/list_objects.go, pkg/server/test/list_users.go
=> chore: improve logging output for benchmarks

internal/graph/check.go, internal/graph/check_test.go, pkg/server/commands/list_objects_test.go, pkg/server/test/list_objects.go
Follow-up of https://github.com/openfga/openfga/pull/1626
=> chore: remove deprecated function NewLocalCheckerWithCycleDetection

internal/graph/check_test.go
Amend test introduced in https://github.com/openfga/openfga/pull/1786
=> test: amend test

internal/condition/eval/eval.go, internal/graph/check.go, pkg/tuple/tuple.go, pkg/tuple/tuple_test.go
Through profiling we discovered that marshalling proto objects is not free:
=> perf: reduce proto conversions

internal/graph/check.go, internal/graph/check_test.go
Remove all changes related to performance optimizations in Check API that we introduced after v1.5.5 was published.
=> feat: do not apply performance optimizations in Check

internal/condition/types/ipaddress.go, pkg/server/server_test.go, pkg/storage/test/stores.go
Chore of fixing lint errors
Recent CICD merge fails on code that was not changed https://github.com/openfga/openfga/actions/runs/10380014737/job/28739151888
=> chore: fix lint errors

.config-schema.json, cmd/run/run.go, internal/graph/check.go, internal/graph/check_test.go, pkg/server/server.go, pkg/testutils/testutils.go, tests/check/check_test.go, tests/functional_test.go, tests/listobjects/listobjects_test.go, tests/listusers/listusers_test.go
This PR introduces a new experimental flag `enable-check-optimizations` to opt in to performance optimizations previously introduced between v1.5.6 and v1.5.8 and later removed in v1.5.9.
https://github.com/openfga/openfga/pull/1837
https://github.com/openfga/openfga/pull/1841
=> perf: enable optimizations for Check

internal/graph/check.go, internal/graph/check_test.go
Refactor the iterator read starting from user to allow better unit testing
=> chore: reafactor iter read starting from user

tests/check/check.go, tests/check/check_ttu.go
First set of TTU test cases for integration
=> test: TTU test for integration

tests/check/check_test.go
Updating integration test to run on main branch as well as with experimental performance optimization flag on
=> tests: run integration matrix test on experimental perf. optimization

tests/check/complexity_three.go
Adding integration test for complexity 3 nested case
=> tests: add complexity 3 nested test

CHANGELOG.md
=> docs(v1.6.1): add v1.6.1 release notes to CHANGELOG

README.md
Refers user to download the latest Go version instead of providing a specific one.
Closes #1944
=> docs: Remove specific Go version in README.md

pkg/storage/iterators.go, pkg/storage/iterators_test.go
Previously, `combinedIterator` would skip calling `.Stop()` on iterators that were fully consumed.
Originally discovered and fixed in https://github.com/openfga/openfga/pull/1924
=> fix: combinedIterator must stop all iterators

CHANGELOG.md, internal/mocks/mock_storage.go, pkg/server/commands/read_changes.go, pkg/server/commands/read_changes_test.go, pkg/storage/memory/memory.go, pkg/storage/mysql/mysql.go, pkg/storage/mysql/mysql_test.go, pkg/storage/postgres/postgres.go, pkg/storage/postgres/postgres_test.go, pkg/storage/sqlite/sqlite.go, pkg/storage/storage.go, pkg/storage/test/tuples.go
Allow the changelog to be traversed backwards.
=> feat!: update ReadChanges interface for additional query patterns

CHANGELOG.md, go.mod
Bump go patch version to `1.22.7` (from `1.22.6`)
Should address the following CVE vulnerability in the stdlib:
```
┌─────────┬────────────────┬──────────┬────────┬───────────────────┬────────────────┬───────────────────────────────────────────────────────────┐
  │ Library │ Vulnerability  │ Severity │ Status │ Installed Version │ Fixed Version  │                           Title                           │
  ├─────────┼────────────────┼──────────┼────────┼───────────────────┼────────────────┼───────────────────────────────────────────────────────────┤
  | stdlib  │ CVE-2024-34156 │ HIGH     │ fixed  │ 1.22.6            │ 1.22.7, 1.23.1 │ encoding/gob: golang: Calling Decoder.Decode on a message │
  |         │                │          │        │                   │                │ which …
```
=> deps: bump go patch version to 1.22.7

internal/checkutil/checkutil.go, internal/checkutil/checkutil_test.go, internal/graph/check.go, internal/graph/tuplemapper.go, pkg/storage/iterators.go
Minor changes in our composition and usage of iterators.
=> Use proper interfaces and cleanup some duplication work

docker-compose.override.yaml, telemetry/otel-collector-config.yaml
All the changes made in this PR affect the Docker compose when doing local development only.
- I wiped all the docker images from my laptop and when I tried to do `docker-compose up`, the `otel-collector` failed to start (see image below). I'm fixing that.
- Update version of `prometheus` container.
- Un-expose ports that do not need to be exposed to the host machine. I only keep the UI ports.
=> fix: docker setup

tests/functional_test.go
fixed tests after including openfga/api#208
openfga/api#208
=> fixed tests after including openfga/api#208

CHANGELOG.md
=> release: v1.7.0

internal/test/batchcheck/batchcheck.go, tests/batchcheck/batchcheck.go, tests/batchcheck/batchcheck_test.go, tests/check/check.go
This PR is entirely integration tests for #2039. It reuses all of our existing yaml-defined Check integration tests. For unit tests see #2065 
#2047 was split into two separate PRs for ease of review. This one is all integration tests
=> test: batch check integration tests

pkg/server/commands/expand_test.go
Quick follow up to #2079 to do a more thorough assertion.
=> test: refactor expand test to use full response

CHANGELOG.md
Add v1.8.0 release details to the CHANGELOG.
=> docs: update changelog for v1.8.0

pkg/server/server_test.go
=> test: add test for cache controller feature

internal/utils/bucket.go, pkg/server/check.go, pkg/server/commands/check_command_test.go, pkg/server/commands/errors.go, pkg/server/commands/expand.go, pkg/server/commands/get_store.go, pkg/server/commands/get_store_test.go, pkg/server/commands/list_objects.go, pkg/server/commands/list_stores.go, pkg/server/commands/listusers/list_users_rpc.go, pkg/server/commands/read.go, pkg/server/commands/read_authzmodels.go, pkg/server/commands/read_changes.go, pkg/server/commands/read_changes_test.go, pkg/server/commands/read_test.go, pkg/server/commands/write.go, pkg/server/commands/write_test.go, pkg/server/errors/errors.go, pkg/server/errors/errors_test.go, pkg/server/list_users.go, pkg/server/list_users_test.go, pkg/server/server.go, pkg/server/server_test.go, pkg/server/test/expand.go, pkg/server/test/read_authzmodels.go, pkg/server/test/write.go
Fix `lint` errors: https://github.com/openfga/openfga/actions/runs/11768775601/job/32778980136?pr=2089#step:4:26
=> chore: fix 1.62 lint errors

pkg/server/commands/expand_test.go
This reverts commit c590b88f42cc7d8010c0aeb7c835803c3a40f8cd.
In #2080 I tried to add an assertion to this test to compare the full nested responses, but it reintroduced an order dependency which we tried to remove in #2079 and made these tests flakey again.
=> test: fix flakey expand test

pkg/storage/iterators.go
Prevent holding iterator reference longer that it needs to be.
=> chore: simplify combinediterator

internal/authz/authz.go, pkg/authclaims/authclaims.go, pkg/server/server.go, pkg/server/write.go, pkg/typesystem/typesystem.go
Minor refactors. There should be no change in behaviors.
=> refactor: authorization

pkg/server/commands/write_test.go
Follow-up to https://github.com/openfga/openfga/pull/2110. I'm adding more robust testing on the error messages.
=> test: add test for error messages from Write API

CHANGELOG.md
Bump changelog to prepare for release of `v1.8.1`
=> docs: changelog for v1.8.1

go.mod, go.sum
Updates OpenFGA to use the changes from [this api PR](https://github.com/openfga/api/pull/213)
https://github.com/openfga/api/compare/c14fb4b3d4b4...0bb89b73d655
=> chore: bump proto definitions for batch check API fix

CHANGELOG.md
this updates the changelog to prepare for release of `v1.8.2`
=> docs: bump changelog in prep for 1.8.2

go.mod, go.sum
Update proto reference to pull in [this proto update](https://github.com/openfga/api/pull/216)
=> chore: bump api proto ref

CHANGELOG.md
This is a Changelog update to prepare for the release of `v1.8.4`
https://github.com/openfga/openfga/security/advisories/GHSA-32q6-rr98-cjqv
=> docs: update changelog to prep for v1.8.4

pkg/typesystem/typesystem.go, pkg/typesystem/typesystem_test.go
…the appropiate model for testing
=> adding a remaining wildcard use case to the fast path, and including test

codecov.yml
Increase minimum required test coverage to 85%
=> chore: increase test coverage requirement to 85%

SECURITY-INSIGHTS.yml
Bringing SECURITY-INSIGHTS.md up to date.
=> chore: Update SECURITY-INSIGHTS.md

CHANGELOG.md, pkg/server/errors/errors.go, pkg/server/errors/errors_test.go
=> Revert "feat: creates `PassthroughError` type to proxy errors through FGA"

CHANGELOG.md
=> docs(v1.8.8): add v1.8.8 release notes to CHANGELOG

tests/listobjects/listobjects.go, tests/listobjects/listobjects_test.go, tests/listobjects/matrix.go
Adding infrastructure for matrix tests with list objects.
=> test: add infra for matrix tests for list objects

tests/listobjects/matrix_directs.go
Another ListObjects testing PR. Currently based on the branch in #2334.
=> test: LO test nested algebra one line

tests/listobjects/matrix_directs.go
More ListObjects testing! Following after #2331
=> test: listobjects nested algebra with multiple types

tests/listobjects/matrix_directs.go
More tests, this one coming behind #2335 .
=> test: add LO test for computed_mult_types with conditions

tests/listobjects/matrix_directs.go
More ListObjects testing. Partner PR to #2337
=> test: List Objects directs-employee alg_combined_oneline

tests/listobjects/matrix_directs.go
Another in a long chain of ListObjects test PRs
=> test: LO assertion for directs-employee weight 1 alg_combined

tests/listobjects/matrix.go, tests/listobjects/matrix_usersets.go
Another in the string of ListObjects test PRs
=> test: ListObjects usersets-user#alg_combined test

tests/listobjects/matrix.go, tests/listobjects/matrix_ttus.go
Another in the chain of list objects testing PRs
=> test: listobjects ttus#recursive and #recursive_public

tests/listobjects/matrix_ttus.go
Another ListObjects matrix test on `type ttus`
=> test: ListObjects `ttus#recursive_alg_combined_oneline`

tests/listobjects/matrix_usersets.go
Adding list objects matrix test for userset#userset_recursive_combind_w3
=> test: list objects test with userset#userset_recursive_combind_w3

tests/listobjects/matrix_ttus.go
ListObjects matrix test scenario for `ttus:tuple_cycle_len2_ttu`
=> test: ListObjects `ttus:tuple_cycle_len2_ttu`

tests/listobjects/matrix_usersets.go
Adding matrix test for list object alg_combined_computed
=> test: list object alg_combined_computed

internal/graph/check.go, internal/graph/check_test.go
Add error handling for panics in `exclusion` in check.
https://github.com/openfga/openfga/pull/2361
=> feat: add exclusion panic error handling

internal/graph/check_fast_path.go
Prevent starvation of parent processors waiting for children to emit bigger batch sizes.
=> Reduce fast path batch threshold from 1000 to 100

.config-schema.json, cmd/run/flags.go, cmd/run/run.go, cmd/run/run_test.go, internal/shared/shared.go, pkg/server/config/cache_settings.go, pkg/server/config/config.go, pkg/server/server.go, pkg/storage/storagewrappers/request.go, pkg/storage/storagewrappers/request_test.go
Configuration for using the shared iterator framework
Follow up for https://github.com/openfga/openfga/pull/2410
=> feat: config for shared iterator framework

pkg/storage/storagewrappers/cached_datastore.go, pkg/storage/storagewrappers/cached_datastore_test.go
=> fix: flaky iter cache test

CHANGELOG.md
Add [v1.8.12](https://github.com/openfga/openfga/compare/v1.8.11...v1.8.12) release details to the CHANGELOG.
=> v1.8.12 release CHANGELOG.md updated

pkg/storage/mysql/mysql.go, pkg/storage/mysql/mysql_test.go, pkg/storage/postgres/postgres.go, pkg/storage/postgres/postgres_test.go, pkg/storage/sqlcommon/sqlcommon.go, pkg/storage/sqlite/sqlite.go, pkg/storage/sqlite/tuple_iterator.go
Reverts openfga/openfga#2434
Still needs work as it makes the test suite of SQLite brittle.
=> Revert "feat: make sqlite lazy"

pkg/storage/storagewrappers/request.go, pkg/storage/storagewrappers/sharediterator/shared_iterator_datastore.go
Follow up work on shared iterator to have measurement unique by method to allow more detailed statistics.
Follow up on https://github.com/openfga/openfga/pull/2433
=> feat: shared iterator measurement unique by method

CHANGELOG.md, pkg/storage/storagewrappers/cached_datastore.go, pkg/storage/storagewrappers/cached_datastore_test.go
This reverts commit fe9cc3ab896f433b29b1ba93b9ec3e30594eb643.
=> Revert "feat: add recover log in cached iterator stop goroutine (#2428)"

internal/graph/check_fast_path.go, internal/graph/object_providers.go, internal/graph/object_providers_test.go
=> revert: fanin refactor with additional bounding

CHANGELOG.md
Add v1.8.14 release details to the CHANGELOG.
=> docs(v1.8.14): add v1.8.14 release notes to CHANGELOG

CHANGELOG.md, pkg/storage/mysql/mysql.go, pkg/storage/postgres/postgres.go
=> Revert "fix: restore conditional checks for connection pool timeout settings"

CHANGELOG.md
Add v1.8.16 release details to the CHANGELOG.
=> docs(v1.8.16): add v1.8.16 release notes to CHANGELOG

internal/iterator/fan_in.go, internal/iterator/fan_in_test.go
Removes unused code and its flaky test.
=> clean: Remove fanin code

CHANGELOG.md, assets/tests/consolidated_1_1_tests.yaml, internal/graph/check.go, pkg/server/commands/reverseexpand/reverse_expand_weighted.go, pkg/server/commands/reverseexpand/reverse_expand_weighted_test.go, pkg/typesystem/typesystem.go, pkg/typesystem/typesystem_test.go
Proposed change to refactor-userset
=> Refactor userset suggestion
