.github/workflows/release.yaml
This gives the release CI workflow `content: write` permission, which is needed to upload Github Release artifacts.
https://goreleaser.com/ci/actions/#token-permissions
=> ci: add `contents: write` permission to release workflow

README.md
Remove examples for now until the docs have examples section.
=> fix: correct link to docs

.github/workflows/release.yaml, .goreleaser.yaml
Choosing to not release container images to Github Container Registry for now.
N/A
=> ci: remove `ghcr.io` container tags from goreleaser releases

.goreleaser.yaml, Dockerfile, docker-compose.yaml
This adds `openfga/openfga:latest` tags to the goreleaser release process and it cleans up the Dockerfile by removing some packages that are not needed in the built image.
=> ci: tidy up the Dockerfile and add the `latest` tag to releases

.github/workflows/fossa.yaml
Artifacts were being pushed to FOSSA, but the build wasn't failing if the FOSSA tests failed.
Also it was configured to run only on merge to main and has been changed to run on pushes to all branches and on any PR.
=> fix(ci): check for failing FOSSA tests on PRs

Makefile
https://github.com/golang/go/blob/78b722d8c2f764c3048c6f0344e9ebcd2687813d/src/cmd/go/internal/test/test.go#L852
Fix warning by trimming the last `,` from the `COVERPKG` variable
n/a
=> fix(makefile): warning: no packages being tested depend on matches for pattern

pkg/cmd/service/service.go, pkg/cmd/service/service_test.go, server/server.go, server/test/read.go
I noticed we're using `gRPC`, `GRPC`, and `grpc` in various places. I'm submitting this to change these references to simply `grpc`, which is a bit more pretty to read than the other two.
=> chore: rename references of gRPC or GRPC to simply grpc

.goreleaser.yaml, internal/build/build.go, pkg/cmd/run.go
This fixes our app build information. It was broken when we introduced the CLI. These changes make sure that we get the build version, commit, and date linked into the final binary.
=> chore: fix app build info

pkg/cmd/service/service_test.go
=> fix: explicitly close client connection in grpc tests

README.md
Fix the server id of the discord widget. Until widgets are enabled on the server the widget will show up as
=> chore(docs): fix discord server id in widget

.github/workflows/fossa.yaml, .github/workflows/semgrep.yaml, .github/workflows/snyk.yaml
These checks will always fail for external contributors, this change only makes them run on branches coming in from within the org, we will have to rely on the weaker webhook integration for outside PRs (these checks will still run on merge to main).
=> chore(ci): only run semgrep, fossa & snyk on branches owned by openfga org

Makefile, server/server.go
Mark the 2 high severity violations reported by semgrep as false positives.
- The command in the Makefile contains parameters meant for local development and should be overridden for a production deployment.
- The server configuration contains an option to include credentials.
https://semgrep.dev/orgs/auth0/findings?tab=open&dedup=true&severity=2&repo=openfga%2Fopenfga
=> chore: ignore 2 semgrep violations since they are false positives

pkg/cmd/run.go, pkg/cmd/service/service.go
I found a small bug that I didn't catch before merging #92 . These changes fix an issue where if you don't have a `config.yaml` present in any one of ["/etc/openfga", "$HOME/.openfga, "."], then the values even from the CLI flags won't get loaded. The problem was that we were returning default config values before calling `viper.Unmarshal`, and so any flags that were binded to viper did not have any influence on the config.
#91
=> fix: viper.Unmarshal config even if `config.yaml` is not present

Makefile, README.md, config-schema.json, pkg/cmd/run.go, pkg/cmd/service/service.go, pkg/testfixtures/storage/storage.go
Generally, we have been calling our storage a datastore, e.g., OpenFGADatastore. This PR is to keep us consistent. 
And fix the make command `run-postgres`.
=> chore: rename database -> datastore in flags and config

.config-schema.json, go.mod, go.sum, pkg/cmd/service/service.go, pkg/cmd/service/service_test.go
The adds support for env variables to the list of optional ways to configure the OpenFGA server. Configuration is loaded according to the default behavior of the spf13/viper package. That is,
> Viper uses the following precedence order. Each item takes precedence over the item below it:
> 
> explicit call to Set
> flag
> env
> config
> key/value store
> default
Each config property is mapped to an env variable by translating the config to all uppercase and replacing any usage of `.` with `_` and attaching the `OPENFGA_` prefix to it. For example, `http.enabled` becomes `OPENFGA_HTTP_ENABLED` and `authn.preshared.keys` becomes `OPENFGA_AUTHN_PRESHARED_KEYS` etc..
https://github.com/spf13/viper#why-viper
=> feat: wire up support for env variables

.config-schema.json, README.md, pkg/cmd/service/service.go
Update default so that playground is enabled by default. Also update corresponding README
Close https://github.com/openfga/openfga/issues/102
=> chore: change playground enable default

.goreleaser.yaml, Makefile, README.md, pkg/cmd/run.go
This fixes the issue with the Playground assets not being included with our build artifacts generated by goreleaser.
=> fix: add Playground artifact to the goreleaser build artifacts

.config-schema.json, README.md, pkg/cmd/run.go, pkg/cmd/service/service.go, pkg/cmd/service/service_test.go
This adds configurable pprof profiling support to the OpenFGA server.
Closes #110 
Documentation: https://github.com/openfga/openfga.dev/pull/170
=> feat: add configurable pprof profiling support

.github/workflows/release.yaml
The `v0.1.5` CHANGELOG release notes have richer Markdown text (with special characters etc..) that cause issues with bash shell escape sequences. Prior releases didn't have such characters and consequently did not have the same issues. The purpose of this PR is to drop the automatic changelog release notes generator until we can fix this is a more elegant (automated) way. For now this will unblock us from releasing the latest `v0.1.5` release.
=> ci: drop auto changelog release notes temporarily until we can resolve

.github/workflows/release.yaml
Drop the goreleaser release notes path. This is a cleanup task from #125 .
#125 #126
=> ci: drop goreleaser release notes path

pkg/tuple/validation.go, server/commands/write.go, server/commands/write_test.go, server/test/write.go
Even though we should allow deleting tuples where there is no current
relation / authorization model not exist, etc.  We should nevertheless
ensure the tuple itself is valid in syntax (i.e., the user is defined).
- Close https://github.com/openfga/openfga/issues/132
=> fix: need basic syntax validation on deletes

.config-schema.json, pkg/cmd/service/service_test.go
Some of the new ListObjects flags were missing in the config-schema.json definitions.
=> chore: add missing config properties for ListObjects flags

server/commands/list_objects.go, storage/postgres/iterators.go
Addressing some comments from https://github.com/openfga/openfga/pull/145#issuecomment-1211066407
Also fixing the case where this
```
case genericError := <-errChan:
return nil, genericError
}
```
returns `nil, nil`.
See https://go.dev/play/p/I07S9PTkann. [We don't need to call `close(errChan)`](https://stackoverflow.com/a/8593986)
=> fix: minor changes to ListObjects

CHANGELOG.md
Brief content guidance for the top of the changelog.
In an effort to make sure our changelog is easy to skim, searchable, and serves the humans that will read it - without crossing into full documentation territory - this added guidance means to steer contributors toward the simplest possible changelog additions while leaving more intensive description, justification, and implementation help to the project's full documentation site.
=> feat: content styling clarity to changelog header

server/commands/check.go, server/commands/list_objects.go
**Counter**: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#asynchronous-counter
> reports [monotonically](https://wikipedia.org/wiki/Monotonic_function) increasing value(s) when the instrument is being observed. Example uses for Asynchronous Counter: [CPU time](https://wikipedia.org/wiki/CPU_time), which could be reported for each thread, each process or the entire system. For example "the CPU time for process A running in user mode, measured in seconds".
**Gauge**: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#asynchronous-gauge
> reports non-additive value(s) (e.g. the room temperature - it makes no sense to report the temperature value from multiple rooms and sum them up) when …
=> fix: change otel counters to gauges

docker-compose.yaml
It is a bit confusing that we have Postgres in the docker compose file, but don't use it when we `docker compose up`. So let's use it. With these changes we start a Postgres container, start OpenFGA using that container, and perform the migration.
=> chore: default to Postgres in docker compose

server/server.go
This changes our Health check implementation slightly so that it is inline with the grpc Health Check protocol.
> The server should register all the services manually and set the individual status, including an empty service name and its status. For each request received, if the service name can be found in the registry, a response must be sent back with an OK status and the status field should be set to SERVING or NOT_SERVING accordingly. If the service name is not registered, the server returns a NOT_FOUND GRPC status.
> 
> The server should use an empty string as the key for server's overall health status, so that a client not interested in a specific service can query the server's status with an empty request. 
More specifically, we only return a status if the request is made with a …
=> chore: minor Health server touch ups

.gitignore
=> fix: add openfga back to .gitignore

storage/test/tuples.go
Fix erroneous test message pointed out by @MidasLamb in discord. Thank you!
Also part of a general push to move to using `require` more.
=> fix: erroneous test message

server/commands/write_authzmodel.go, server/test/check.go, server/test/expand.go, server/test/list_objects.go, server/test/read.go, server/test/read_authzmodel.go, server/test/read_authzmodels.go, server/test/read_tuples.go, server/test/write.go, storage/caching/caching_test.go, storage/memory/memory.go, storage/mocks/mock_storage.go, storage/postgres/postgres.go, storage/storage.go, storage/test/authz_models.go
Refactor `WriteAuthorizationModel` to take an array of `*openfgapb.TypeDefinition`s rather than an `*openfgapb.TypeDefinitions`. Currently every implementation starts off by extracting the underlying `*openfgapb.TypeDefinition` array from `*openfgapb.TypeDefinitions` so why not just make it explicit in the function.
=> refactor: write auth models to take an array of type definitions

pkg/cmd/service/service.go, server/middleware/logging.go, server/server.go, storage/postgres/utils.go
Previously we were trying to log internal errors at the HTTP layer, but at this point the error had already been converted to a status type error and the internal error had been lost. So, in this PR, we move this logging to the gRPC layer.
Another benefit of this change is that if you are using the gRPC endpoint you will actually generate this log, whereas previously you would not have.
=> fix: log internal errors at the grpc layer

server/commands/check.go, server/test/check.go
This fixes the bug reported in https://discord.com/channels/759188666072825867/920359187949707305/1019251304251523112
(https://discord.com/channels/759188666072825867/920359187949707305/1019251304251523112)
=> fix: skip malformed tuples involving tuple to userset definitions

Makefile
Now that we are adding [other storage engines](https://github.com/openfga/openfga/pull/210), I think it would be useful to have commands in the Makefile that help with the local development of OpenFGA for these engines. Previously to start Postgres we could rely on the docker-compose file, but I don't suppose this will be the case with MySQL. So to keep things consistent, this PR adds a `start-postgres-container` command to the Makefile which can be used with the `migrate-postgres` and `run-postgres` commands. I envision we will have similar commands for MySQL.
=> refactor: add start-postgres-container to the makefile

assets/migrations/postgres/002_add_authorization_model_version.sql, pkg/typesystem/typesystem.go, server/commands/write_authzmodel.go, server/test/check.go, server/test/expand.go, server/test/list_objects.go, server/test/read.go, server/test/read_authzmodel.go, server/test/read_authzmodels.go, server/test/read_tuples.go, server/test/server.go, server/test/write.go, server/test/write_authzmodel.go, storage/caching/caching_test.go, storage/memory/memory.go, storage/mocks/mock_storage.go, storage/postgres/postgres.go, storage/postgres/postgres_test.go, storage/storage.go, storage/test/authz_models.go
Store the schema version in our datastore.
One thing I don't like there is that our signatures have grown a bit unwieldy. Do we prefer to combine the `version SchemaVersion, typeDefinitions []*openfgapb.TypeDefinition` into a `typeSystem *typesystem.Typesystem`. There is a bit of subtlety here as a `TypeSystem` contains a `map[string]*openfgapb.TypeDefinition` rather than an `[]*openfgapb.TypeDefinition`.
You know, we could even add the model id to the `TypeSystem`. Then, in checks, we simply read the entire model rather than a type at a time. WDYT?
=> chore: store the schema version

server/test/list_objects.go
This fixes the flaky StreamedListObjects tests that were not waiting on full consumption of the result channel.
=> fix: ListObjects streaming tests

Makefile, server/commands/list_objects.go, server/test/list_objects.go
When we read the value of `objectsFound` and then increment it, we need to put a lock around this entire block of code, otherwise a data race can occur.
Alternatively, read and increment `objectsFound` in one operation :D
=> fix streaming list objects API returning more objects than it should

pkg/cmd/migrate.go
Currently if I try to migrate the memory backend I get:
```
$ ./openfga migrate --datastore-engine memory
Error: unknown datastore engine type: memory
```
We probably shouldn't return an error with unknown engine type. Rather it should succeed. This may help with automation where one will always run the migration step regardless of engine type.
=> bug: allow migrate for memory

storage/postgres/postgres.go
Sigh... pgx v5 must have changed how `New` works so that it is now quite similar to `sql.Open`. Anyway, this change is to ensure we connect to Postgres before starting.
=> bug: wait for connection to postgres before starting

.config-schema.json, pkg/cmd/run.go, pkg/cmd/service/service.go, pkg/cmd/service/service_test.go
There is no situation in which we would not enable gRPC. Remove this config option.
We also have two GRPCConfig and HTTPConfig structs. It would be nice to refactor this. And we use `service` to wrap a `server` and store a bunch of data that is in the server redundantly. This is a bit confusing and would also be nice to refactor.
=> doc: remove grpc enabled config 

pkg/cmd/service/service.go
We used to support an unspecified host in the `grpc.addr` and `http.addr` config. That is, you could provide `:8080` as a host and port address. We accidentally broke this in a recent release, and so this fixes it. 
Fixes #274
=> chore: fix host:port mapping with unspecified host

pkg/cmd/service/service.go
In [config schema](https://github.com/openfga/openfga/blob/main/.config-schema.json) is this config path described: `grpc.tls.cert` and `grpc.tls.key`. Neither runtime flags `--grpc-tls-cert`/`--grpc-tls-key` nor yaml configs `grpc.tls.cert` and `grpc.tls.key` are mapped correctly.
Mismatch is done by:
https://github.com/openfga/openfga/blob/0999404bfb1ef7846b2ca12469ef049cb6c6f8e9/pkg/cmd/service/service.go#L70-L74
Fields `cert` and `key` cannot be mapped to `CertPath` and `KeyPath` without `mapstructure` tag.
fixes #284
=> fix: correcting TLS certificates config path

server/errors/encoded_errors.go, server/server.go
This PR wires up the grpc-gateway runtime handler for streaming error handling. This is to ensure that the streaming endpoints return the same error codes as expected from the unary endpoints.
=> chore: wire up `runtime.WithStreamErrorHandler`

pkg/cmd/service/service.go, pkg/cmd/service/service_test.go
Throw an error if attempting to run the server and `config.http.upstreamTimeout` and `config.listObjectsDeadline`.
https://github.com/openfga/openfga/issues/314
=> fix: throw error if config.http.upstreamTimeout is lower than config.listObjectsDeadline

pkg/cmd/migrate.go
Allow the migrations to use the same config files as the running server. This way it allows re-using the same file for both which is a nice QoL improvement in case you're using the files.
=> feat: allow migrations to also read the config file

.goreleaser.yaml
This adds another docker build target for `linux/arm64` and the corresponding docker manifests so developers running on arm64 cores (e.g. developers using the new M1 or arm based cores) don't get the following warning message:
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
2022-11-01T22:14:13.883Z	INFO	using 'memory' storage engine
2022-11-01T22:14:13.886Z	WARN	authentication is disabled
2022-11-01T22:14:13.886Z	WARN	grpc TLS is disabled, serving connections using insecure plaintext
2022-11-01T22:14:13.894Z	INFO	grpc server listening on '0.0.0.0:8081'...
2022-11-01T22:14:13.936Z	INFO	HTTP server listening on '0.0.0.0:8080'...
2022-11-01T22:14:13.937Z	INFO	🛝 starting openfga …
```
=> chore: add multi-platform container build manifests to releases

.github/workflows/pull_request.yaml, Makefile
This PR changes the way we report coverage by running `go test` on all packages and then stripping away all of the cover profiles that cover mocks. It leads to the same report, but it avoids the verbose comma-separate list of `coverpkg` which makes it hard to read the test output.
=> chore: simplify coverage and suppress verbose coverpkg output

cmd/run_test.go, storage/postgres/iterators.go, storage/postgres/postgres.go, storage/postgres/postgres_test.go, storage/postgres/utils.go, storage/postgres/utils_test.go, storage/storage.go, storage/test/tuples.go
Refactor Postgres to use `database/sql`. This allows us to bypass this issue with https://github.com/jackc/pgx/issues/1354 and it also starts to lay the foundation for creating a shared/common package between SQL datastores (such as our Postgres and MySQL ones).
=> chore: refactor postgres to use `database/sql`

assets/migrations/mysql/003_add_reverse_lookup_index.sql, assets/migrations/postgres/003_add_reverse_lookup_index.sql, go.mod, go.sum, internal/graph/graph.go, internal/graph/graph_test.go, pkg/typesystem/typesystem.go, pkg/typesystem/typesystem_test.go, server/commands/check.go, server/commands/connected_objects.go, server/commands/expand.go, server/commands/list_objects.go, server/commands/write.go, server/server.go, server/test/check.go, server/test/connected_objects.go, server/test/list_objects.go, server/test/server.go, server/test/write_authzmodel.go, testdata/github/tuples.json, testdata/github/typedefs.json
This PR introduces a new internal API called the `ConnectedObjects` API. This API is used to reverse expand relationship tuples between some source user and some target `object#relation`. We use this ConnectedObjects API in an improved version of ListObjects for any models other than those exhibiting intersection or exclusion rewrites (support for improved intersection and exclusion coming soon).
https://github.com/openfga/roadmap/issues/8
=> feat: optimized ListObjects with reverse expansion

server/test/connected_objects.go
Adds the `Id` and `SchemaVersion` fields that were missing in the AuthorizationModel.
=> chore: add `Id` and `SchemaVersion` fields to models in tests

server/test/connected_objects.go
This moves some of the test tuples for one of the ConnectedObjects test cases to be split between ContextualTuples and storage tuples.
=> chore: move some tuples to ContextualTuples to avoid dynamo limits

README.md
Update README build instruction as there is no `cmd/openfga/openfga.go` file.  Instead, user should invoke `make build`.
Close https://github.com/openfga/openfga/issues/352
=> fix: update README for build instruction

server/commands/check.go
=> refactor: getTypeDefinitionRelationUsersets to only get the rewrite

Makefile
This abbreviates the `make start-mysql` and `make start-postgres` commands. Typing our the `-container` suffix is a bit much for the fingers 😄
=> chore: abbreviate `start-mysql` and `start-postgres`

cmd/openfga/main_test.go, internal/graph/graph_test.go, server/commands/check.go
This PR fixes Check support for 1.1 models by allowing Checks to be run on types that are indirectly related. For example
```
type user
type group
relations
define member: [user]
type document
relations
define viewer: [group#member]
```
| object     | relation | user             |
|------------|----------|------------------|
| group:eng  | member   | user:jon         |
| document:1 | viewer   | group:eng#member |
`Check(document:1#viewer@user:jon)` --> `{allowed: true}`. 
Prior to this PR strict validation would cause an error to be returned because the `user` type is not directly related to `document#viewer`.
=> fix: resolve indirect relationships with type restrictions in Check

server/commands/check.go, server/commands/check_utils.go, server/commands/connected_objects.go, server/commands/expand.go, server/commands/list_objects.go, storage/memory/memory.go, storage/mocks/mock_storage.go, storage/mysql/iterators.go, storage/mysql/mysql.go, storage/mysql/utils.go, storage/postgres/iterators.go, storage/postgres/postgres.go, storage/postgres/utils.go, storage/storage.go, storage/storage_test.go, storage/test/tuples.go
Suggestion: click this:
---
This is a follow-up of https://github.com/openfga/openfga/pull/368.
The `Next()` function of the iterators was modified to take in a `context` that, when cancelled or deadlined, will make the iterator's `Next()` function return `ErrIteratorDone`. 
Load tests were run against ListObjects to ensure there is no goroutine leaks.
=> chore: refactor iterators

internal/validation/validation.go, server/commands/check.go, server/commands/write_assertions.go, server/test/write_assertions.go
write_assertion should not care about type restriction as it is similar to check
Close https://github.com/openfga/openfga/issues/411
=> fix: write assertion should not care about type restriction

cmd/run.go
Fix flaky run tests due to the server stopping before it's had time to spin up.
=> chore: fix flaky `run` entrypoint tests

server/server_test.go
This splits the individual `mysql`, `postgres`, and `memory` server tests into individual Go tests so that they can be run individually if you prefer. This is particularly helpful during development because then you can just run the `memory` tests for quick feedback.
=> chore: split the server tests into individual tests

internal/validation/validation.go, internal/validation/validation_test.go
The changes herein add extra tuple validations for 1.1 models. In particular, an `object` value cannot be formatted as a typed wildcard (e.g. `type:*`) AND `user` values involving usersets cannot reference a typed wildcard in their 'object' component. So tuples such as `document:*#viewer@user:jon` and `document:1#viewer@document:*#editor` are both invalid.
Fixes #415
=> fix: correct validation errors for typed wildcard behavior in 1.1 models

internal/validation/validation.go, server/test/write.go
Fix validation of type restrictions on objects.
Fixes #456
=> fix: correctly validate type restrictions on object types

.config-schema.json, cmd/run.go, cmd/run_test.go
This puts the OpenTelemetry metric integration behind an experimental feature flag `otel-metrics`. We will proceed forward with adding metrics as a first-class citizen of the server configurations once we've decided on a metric ecosystem that the community will benefit most from. We're still deciding between Prometheus for Metrics vs OpenTelemetry.
=> chore: put OpenTelemetry metrics behind an experimental feature flag

server/commands/check.go
=> fix: move iter.stop to after initialization

cmd/run.go, pkg/storage/context.go, pkg/storage/memory/memory.go, pkg/storage/mysql/mysql.go, pkg/storage/postgres/postgres.go
In a future PR I will add a timeout context to the datastore calls, but this requires removing the ctx from the datastore iterators.
#380
=> perf: thin context wrapper over datastore

pkg/storage/mocks/mock_storage.go, pkg/storage/storage.go
Refactor some of the storage interface to more logically separate reader and writer interfaces.
Part of the work in #476
=> refactor: shift around storage interface definitions

pkg/server/test/connected_objects.go, pkg/typesystem/typesystem.go, pkg/typesystem/typesystem_test.go
This code ensures that we don't revisit prior relationship rewrites during rewrite tree evaluation when checking if Intersection or Exclusion rewrite operators are involved.
This code positively impacts ListObjects because we use `RelationInvolvesIntersection` and `RelationInvolvesExclusion` to determine if we should use the optimized ListObjects (`ConnectedObjects` implementation) or the unoptimized version (concurrent `Check` evaluation). 
These two methods (RelationInvolvesIntersection RelationInvolvesExclusion) were encountering stackoverflow scenarios because this safeguard wasn't in place for this specific (and unique) case.
Fixes #505
=> fix: avoid re-eval of visited rewrites during rewrite tree recursion

pkg/storage/iterators.go
I don't know why we didn't do this from the get-go :(
This PR also should bring a performance improvement because now, if the iterator is finished, we don't call `Next()`.
=> feat(internal): make CombinedIterator accept more than two inputs

pkg/logger/logger.go
The stacktrace is never useful, so remove it. E.g.:
```
github.com/openfga/openfga/pkg/logger.(*ZapLogger).Error
/Users/craig/git/openfga/pkg/logger/logger.go:53
github.com/openfga/openfga/internal/middleware.NewLoggingInterceptor.func1
/Users/craig/git/openfga/internal/middleware/logging.go:62
google.golang.org/grpc.getChainUnaryHandler.func1
/Users/craig/go/pkg/mod/google.golang.org/grpc@v1.52.3/server.go:1163
github.com/openfga/openfga/internal/middleware.NewRequestIDInterceptor.func1
/Users/craig/git/openfga/internal/middleware/requestid.go:48
google.golang.org/grpc.getChainUnaryHandler.func1
/Users/craig/go/pkg/mod/google.golang.org/grpc@v1.52.3/server.go:1163
go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.UnaryServerInterceptor.func1 …
```
=> refactor: remove stacktrace from error logs

pkg/server/commands/list_objects.go, pkg/server/server.go, pkg/server/test/list_objects.go
Wires up ListObjects (for the concurrent Check evaluation path) with the newly refactored Check implementation.
=> chore: wire up ListObjects with the refactored Check implementation

cmd/openfga/main_test.go, internal/graph/check.go, pkg/server/commands/list_objects.go
Fixes ListObjects in the event that concurrent Checks are evaluated (for 1.0 models or models involving intersection or exclusion).
Related to #524
=> fix: add missing typesystem context in ListObjects (concurrent check)

pkg/server/commands/list_objects.go
This PR adds a span attribute to the `ListObjects` span that indicates what handler was used (optimized or non-optimized variant).
This work is essentially superseded by https://github.com/openfga/openfga/pull/522, because at that point it will be obvious which path ListObjects took.
=> chore: add a span attr to indicate what ListObjects handler was used

internal/graph/graph.go, internal/graph/graph_test.go, pkg/server/commands/connected_objects.go, pkg/server/server.go
This adds tracing to the internal `ConnectedObjects` API, which is a reverse graph expansion algorithm that is used in the optimized version of ListObjects (the one that works with models involving type restrictions).
Here's an example screenshot of the traces produced by the changes in this PR:
Each span is annotated with attributes that represent the relationship tuples that are expanded at each level in the reverse expansion graph evaluation.
Related to https://github.com/openfga/openfga/pull/521
=> chore: add tracing to internal ConnectedObjects API

docker-compose.yaml
=> fix: expose default grpc port in docker-compose.yaml

internal/graph/check.go, tests/oldcheck/check_test.go, tests/oldcheck/tests.yaml
Skip computed relations on tupleset relationships if they are undefined for that model.
Fixes #531
=> fix: skip computed relations on tuplesets if they are undefined

.github/workflows/release-nightly.yaml
Fixes the version tag of the goreleaser image used to run the nightly builds.
=> ci: update goreleaser nightly workflow

pkg/server/server.go, tests/check/check_test.go
When auth model id is not found in check, it should return error auth model id not found instead of internal error.
Close https://github.com/openfga/openfga/issues/540
=> fix: error handling for check in auth model id not found

internal/graph/check.go, tests/check/tests.yaml
Fixes Check resolution when a typed-wildcard is encountered that doesn't match the type restrictions.
=> fix: continue Check evaluation search if typed-wildcard doesn't match

Dockerfile.goreleaser
`wget` is not part of the `alpine` image by default. This adds the `wget` command to a builder image and then copies the `grpc_health_probe` binary from the builder image into the final image.
=> ci: fix goreleaser Dockerfile

.goreleaser-nightly.yaml, .goreleaser.yaml, Dockerfile, Dockerfile.goreleaser
Goreleaser doesn't play nicely with multi-stage builds 🤷 .. It wasn't meant to run multi-stage docker builds because it simply copies the built artifacts to the target container.
So I've changed the build process to fetch the `grpc-health-probe` from it's Github Container Registry source, which will fetch the appropriate container for the platform being built automatically. I've tested it out locally and it works great 👍 
https://github.com/goreleaser/goreleaser/issues/609
=> ci: fix goreleaser build

.github/workflows/pull_request.yaml, Dockerfile, Dockerfile.goreleaser
Change usages of `RUN chmod +x ...` to the natively supported `COPY --chmod=0755 ..` instead. My theory is this will eliminate the cross-platform build issue that we're seeing with our releases.
https://github.com/openfga/openfga/actions/runs/4196374586/jobs/7277261746
`RUN chmod +x` - we're getting an "exec format" error I believe because it's attempting to use a cached layer of the `alpine` image for the `linux/amd64` platform target when it's running the `linux/arm64` build. Using the native `--chmod` I hope allows the docker buildkit to figure it out better 🤷 ...
=> ci: use native `--chmod` arg in `COPY` command

go.mod, go.sum
bump indirect x/net package to v0.7.0
address https://security.snyk.io/vuln/SNYK-GOLANG-GOLANGORGXNETHTTP2-3323837
=> chore: bump x/net package

.github/workflows/release-nightly.yaml, .github/workflows/release.yaml, .goreleaser-nightly.yaml
Update the nightly release build workflow by removing the extra build step. Since `goreleaser` already builds the image and makes it available for the Docker daemon context, we just have to publish the built manifest by calling `docker push openfga/openfga:latest`.
=> ci: update nightly release workflow

.github/dependabot.yaml
Reduce the frequency of dependabot PRs. I was hoping to set it bi-weekly, but it looks like you can only do it weekly or monthly.
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#scheduleinterval
=> ci: reduce dependabot frequency

pkg/storage/memory/memory.go
Race condition detected when running test in parallel. Root cause is ListObjectsByType's access to s.tuples is not guarded by mutex.
=> fix: race condition in memory store list object

cmd/run/flags.go
Fixes
```shell
[3/03/23 1:38:05] ~/GitHub/openfga (main) $ docker run -p 8080:8080 -p 8081:8081 openfga/openfga run --profiler-addr=":3001" --profiler-enabled
Error: unknown flag: --profiler-addr
```
http://openfga.dev/docs/getting-started/setup-openfga#profiler-pprof
=> fix: add missing profiler-addr flag

assets/tests/consolidated_1_1_tests.yaml, internal/graph/graph.go, internal/graph/graph_test.go
Fixes the `RelationshipIngresses` computation of indirectly related relationships through computed usersets. This fixes a known bug with ListObjects that uses reverse expansion.
Fixes #602
=> fix: reverse expansion with indirect computed userset relationship

pkg/server/test/list_objects.go
This fixes the ListObjects benchmarks by injecting the needed `typesystem` into the context before calling `Execute`.
=> fix: inject typesystem into context in benchmarks

tests/check/check.go, tests/check/check_test.go, tests/listobjects/listobjects.go, tests/listobjects/listobjects_test.go, tests/writemodel/writemodel.go, tests/writemodel/writemodel_test.go
Allows other packages to run RunAllTests in their unit tests
=> fix: move RunAllTests into non _test.go

cmd/openfga/main.go, cmd/version.go
Allow printing out of version in CLI
```shell
adriantam@C02F5002MD6P openfga % ./openfga
A high performance and flexible authorization/permission engine built for developers and inspired by Google Zanzibar.
OpenFGA is designed to make it easy for developers to model their application permissions, and to add and integrate fine-grained authorization into their applications.
Complete documentation is available at https://openfga.dev.
Usage:
openfga [command]
Available Commands:
completion  Generate the autocompletion script for the specified shell
help        Help about any command
migrate     Run database schema migrations needed for the OpenFGA server
run         Run the OpenFGA server
version     Return the OpenFGA version
Flags:
-h, --help   help for openfga
Use "openfga [command] …
```
=> feat: add version in CLI

pkg/storage/postgres/postgres.go
Remove unnecessary sort operation in ReadUsersetTuples.
=> Remove sort from ReadUsersetTuples

Dockerfile, Dockerfile.goreleaser
👋 Build using the chainguard go image (which uses glibc rather than musl) and then run the resulting executable in the distroless chainguard image. This should be more secure than a generic alpine image.
I remember a long time ago wondering why it wouldn't work in a distroless image because we had no dependency on CGO, but you must explicitly have `CGO_ENABLED=0` in the build step for it to work.
=> build: use chainguard images in Dockerfile

cmd/migrate.go
Adds a `--timeout` flag (`OPENFGA_TIMEOUT` env variable) to the `openfga migrate` command so that we can wait up to the timeout period for the database to come online before attempting to apply migrations.
=> chore: add `timeout` flag to `migrate` command

assets/tests/consolidated_1_1_tests.yaml, internal/graph/graph.go, internal/graph/graph_test.go
This fixes some behavior with TTU ingresses not being computed properly, and this was leading to some behavior where `ListObjects` could fail to evaluate relationships consistently relative to `Check`.
Fixes the ListObjects behavior for the example presented in #615.
=> fix: ConnectedObjects TTU expansion behavior

internal/graph/graph.go, pkg/server/commands/connected_objects.go
Update variable name for caller for RelationshipIngresses to make reading clearer
Close https://github.com/openfga/openfga/issues/612
=> chore: correct name for calling RelationshipIngresses

cmd/migrate.go
`goose.Up` on the appropriate migrations path for `mysql` migrations.
=> fix: set correct migrations path for mysql in `openfga migrate`

Dockerfile, Dockerfile.goreleaser
bump grpc healthprobe version
https://github.com/grpc-ecosystem/grpc-health-probe/compare/v0.4.16...master
contains fix for https://github.com/advisories/GHSA-mh68-qf2j-8c5g
=> chore: bump grpc healthprobe version

pkg/server/test/read.go
Fixes the error message for the server read unit tests when the response user is incorrect - it currently prints the relation instead of the user for each tuple.
=> chore(tests): fix read test error message

cmd/run/run.go
Change so that we get request id first.  This allows us usage of request id in validation layer.
=> fix: update order of middleware

cmd/run/run.go, cmd/run/run_test.go
Avoid hard coding ports in test
Close https://github.com/openfga/openfga/issues/621
=> fix: do not hard-code ports in test

CHANGELOG.md, cmd/migrate.go
While testing the changes in https://github.com/openfga/openfga/pull/655 I noticed a few logs that could be improved.
Also:
Before this PR: `--help` output is incorrectly indented
With this PR:
=> feat: improve error logging in migrate command

assets/migrations/mysql/003_add_reverse_lookup_index.sql
Current error:
```shell
[12/04/23 5:37:02] ~/GitHub/openfga (main) $ ./openfga migrate --datastore-engine mysql --datastore-uri 'root:secret@tcp(localhost:3306)/openfga?parseTime=true' --version 2
2023/04/12 17:37:20 ERROR 003_add_reverse_lookup_index.sql: failed to run SQL migration: failed to execute SQL query "DROP INDEX  idx_reverse_lookup_user;": Error 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
```
This PR fixes it.
Tested by:
`docker-compose up -d` with this Docker compose file
```yaml
services:
mysql:
image: mysql:latest
container_name: mysql
environment:
- MYSQL_DATABASE=openfga
- MYSQL_ROOT_PASSWORD=secret
networks:
- default
ports:
- "3306:3306"
healthcheck: …
```
=> fix: migration script #3 for mysql

CHANGELOG.md
Adds the v1.0.0 release notes to the CHANGELOG.
=> docs: add v1.0.0 release details to CHANGELOG

CHANGELOG.md
Adds the v1.0.1 release notes to the CHANGELOG.
=> docs: add v1.0.1 release details to CHANGELOG

cmd/migrate.go, pkg/storage/mysql/mysql_test.go, pkg/storage/postgres/postgres_test.go, pkg/testfixtures/storage/mysql.go, pkg/testfixtures/storage/postgres.go, pkg/testfixtures/storage/storage.go
This is to help detect problems like this: https://github.com/openfga/openfga/pull/691
Tested manually:
```shell
[17/04/23 7:48:07] ~/GitHub/openfga (test-migrations) $  make start-postgres 
docker run -d --name postgres -p 5432:5432 -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=password postgres:14
c6c088272b07293dbc12f4611dedbfbc8307267ebda45fc36a5e4059a05fa3d6
> use 'postgres://postgres:password@localhost:5432/postgres' to connect to postgres
[17/04/23 7:48:11] ~/GitHub/openfga (test-migrations) $ ./openfga migrate --datastore-engine postgres --datastore-uri 'postgres://postgres:password@localhost:5432/postgres' --version 4
2023/04/17 19:48:15 current version 0
2023/04/17 19:48:15 migrating to 4
2023/04/17 19:48:15 migration done
[17/04/23 7:48:15] ~/GitHub/openfga (test-migrations) $ …
```
=> test: add tests for rollbacks of database scripts

README.md, assets/migrations/mysql/001_initialize_schema.sql, pkg/testfixtures/storage/mysql.go
- chore: pin MySQL container image to v8
- normalize tabs/spaces in migration script
=> chore: pin MySQL container image to v8

pkg/storage/context.go, pkg/storage/storage.go, pkg/storage/test/tuples.go
Fixes: 
- database calls for ListObjects v0 use a new context object to avoid database connection churning
- flaky test
=> fix: database calls for ListObjects v0 use a new context object to avoid db connection churning

assets/migrations/postgres/003_add_reverse_lookup_index.sql
If in a future PR we decide to drop the Postgres index `idx_reverse_lookup_user` and then you try to rollback to version 2, migration script #3 will fail because it is not idempotent.
TODO: find if there is an equivalent for MySQL.
=> fix: down script of postgres/003_add_reverse_lookup_index.sql

pkg/server/commands/list_objects.go, pkg/server/test/list_objects.go, pkg/storage/mocks/slow_storage.go
List objects should return results when ListObjectsDeadline is hit rather than waiting for results to be completed. Otherwise, 500 internal error will be returned if the request takes a long time (i.e., maybe due to many items to be looked up).
- Close https://github.com/openfga/openfga/issues/703
- Added unit test
- Manual test by adding a 10 seconds timeout in the [reverseExpandObject](https://github.com/openfga/openfga/blob/f33657319d7885600a19c112509868a6ee1c5b3e/pkg/server/commands/connected_objects.go#L452).  Observe than 500 Internal Error is returned before the change.  200 OK with empty list is returned after the change.
=> fix: list objects to respect configurable ListObjectsDeadline

.config-schema.json, cmd/run/flags.go, cmd/run/run.go, pkg/server/server_test.go, pkg/storage/mysql/mysql.go, pkg/storage/mysql/mysql_test.go, pkg/storage/postgres/postgres.go, pkg/storage/postgres/postgres_test.go, pkg/storage/sqlcommon/sqlcommon.go, pkg/testfixtures/storage/mysql.go, pkg/testfixtures/storage/postgres.go, pkg/testfixtures/storage/storage.go, tests/tests.go
This adds explicit support for separately providing a username and/or password to the datastore as separate explicit configuration values.
All the expected sources are supported: config.yaml, flags and environment variables. Both postgrsql & mysql are implemented.
When using secret managers like Vault or even Kubernetes secrets only allowing the specifying a full connection URI only becomes problematic.Usually _only_ the credentials are stored in these services and they may need to be rotated in an automated fashion.
Allowing the username and/or password to be provided separately eases integration of OpenFGA with these credential managements systems. For example, passing the base URI to a Helm chart value and then providing the username and password via K8s secrets mapped as environment …
=> Feature[credentials]: Support explicit datastore username & password configuration points

.goreleaser.yaml
This adds a release process to our goreleaser manifest so that we release a new formula of OpenFGA to our official Homebrew tap for the OpenFGA organization (https://github.com/openfga/homebrew-tap).
https://goreleaser.com/customization/homebrew/
https://github.com/goreleaser/goreleaser/blob/main/.goreleaser.yaml#L167 - as an example
=> ci: add Homebrew release stage to goreleaser's release process

pkg/server/commands/write.go, pkg/server/test/write.go
Should respond with proper error message when auth model id is not found for write.
Close https://github.com/openfga/openfga/issues/724
1. Create store
2. Write auth model
3. Write tuples but specify auth model id that is a valid ulid but no such auth model id
4. Ensure 400 Bad Request is returned (not 500)
=> fix: in write API, if auth model ID not found, throw 400 instead of 500 error

.github/workflows/codecov.yaml, .github/workflows/main.yaml, .github/workflows/pull_request.yaml, .github/workflows/release-nightly.yaml, .github/workflows/release.yaml, .github/workflows/semgrep.yaml, Dockerfile, Dockerfile.goreleaser
Github and docker should use SHA
Recommended by https://github.com/ossf/scorecard/blob/376f465c111c39c6a5ad7408e8896cd790cb5219/docs/checks.md#pinned-dependencies
=> chore(ci): update github action and docker to use SHA

pkg/server/commands/list_objects.go, pkg/server/server_test.go
This fixes a regression introduced in https://github.com/openfga/openfga/pull/757. The failure is seen here https://github.com/openfga/openfga/actions/runs/4994450765/jobs/8945024934#step:5:38. Note that this failure happens once in a while, not all the time :)
The following benchmarks (not included in the PR) are minimum reproducible examples of the overall behavior before that PR, after that PR, and with this PR fixing it.
```go
// passes
func BenchmarkBeforePR757(b *testing.B) {
for i := 0; i < b.N; i++ {
errChan := make(chan error) //unbuffered
resultsChan := make(chan error, 1000)
go func() {
errChan <- fmt.Errorf("error!")
close(resultsChan)
}()
for {
select {
case _, ok := <-resultsChan:
if !ok {
panic("not expected")
}
case _, ok := <-errChan:
if ok {
return
}
}
}
}
}
// panics …
```
=> fix: regression in #757

Dockerfile, Dockerfile.goreleaser
Update version of the binary `grpc-health-probe` that is bundled in our Docker image.
- https://github.com/openfga/openfga/security/advisories/GHSA-r4mc-x5qf-96fj
- https://github.com/grpc-ecosystem/grpc-health-probe/pkgs/container/grpc-health-probe
=> chore: update version of ghcr.io/grpc-ecosystem/grpc-health-probe

cmd/run/run.go, internal/graph/check_test.go, pkg/server/server_test.go, pkg/storage/caching/caching_test.go, pkg/storage/memory/memory.go, pkg/storage/memory/memory_test.go
- refactor: constructor of in-memory storage to use the `options` pattern: https://golang.cafe/blog/golang-functional-options-pattern.html
=> refactor: constructor of in-memory storage

pkg/server/test/write_authzmodel.go, pkg/typesystem/typesystem.go, pkg/typesystem/typesystem_test.go
This fixes a bug with model validation that wasn't allowing models with non-zero entrypoints to be written to OpenFGA.
Fixes the issue reported in #801.
=> fix: validate models with non-zero entrypoints properly

assets/tests/consolidated_1_1_tests.yaml
Adding additional unit tests for reverse expand intersection + exclusion
Part of https://github.com/openfga/openfga/pull/797
=> feat: adding unit tests for reverse expand interseciton + exclusion

pkg/server/test/write_authzmodel.go, pkg/typesystem/typesystem.go, pkg/typesystem/typesystem_test.go
This reverts commit d3b5eec530dd068057378a34b7f9c12f45fa9078.
Reverts commit starting with sha `d3b5eec5`
=> Revert "fix: validate models with non-zero entrypoints properly (#802)"

Dockerfile, Dockerfile.goreleaser
This bumps up to the latest version of grpc-health-probe.
=> chore: bump version of grpc-health-probe

pkg/typesystem/typesystem.go
PR resolves #814 by updating the returned error to remove the use of `errors.Join` which added the unwanted newline (`\n`).
Updated line 727 of `pkg/typesystem/typesystem.go` so that the the error prefix is included in the `fmt.Errorf` options, rather than using `errors.Join`
Relates to Issue #814
=> Updated error return to remove new line

internal/graph/check_test.go
Adding the test mentioned here https://github.com/openfga/openfga/pull/855#issuecomment-1629551787. 
This test passes on `main`, but on that (closed) PR fails with:
```GOROOT=/usr/local/opt/go/libexec #gosetup
GOPATH=/Users/mparnisari/go #gosetup
/usr/local/opt/go/libexec/bin/go test -c -o /Users/mparnisari/Library/Caches/JetBrains/GoLand2023.1/tmp/GoLand/___TestCheckWithOneConcurrentGoroutineCausesNoDeadlock_in_github_com_openfga_openfga_internal_graph.test github.com/openfga/openfga/internal/graph #gosetup
/usr/local/opt/go/libexec/bin/go tool test2json -t /Users/mparnisari/Library/Caches/JetBrains/GoLand2023.1/tmp/GoLand/___TestCheckWithOneConcurrentGoroutineCausesNoDeadlock_in_github_com_openfga_openfga_internal_graph.test -test.v -test.paniconexit0 -test.run …
```
=> test: Check concurrency set to 1 causes no deadlock

cmd/run/run.go, internal/graph/check.go, pkg/server/commands/list_objects.go, pkg/storage/storagewrappers/boundedconcurrency.go, pkg/storage/storagewrappers/boundedconcurrency_test.go, pkg/storage/storagewrappers/caching.go, pkg/storage/storagewrappers/caching_test.go
This PR implements a wrapper for the [`RelationshipTupleReader` interface](https://github.com/openfga/openfga/blob/main/pkg/storage/storage.go#L47) that has a channel limiter so that only so many database queries can be in flight per request.
It also measures how much time is spent waiting. For example: for a complex ListObjects call:
In this PR we use it only for ListObjects API calls, so that one complex ListObjects call won't hog all database connections.
In the future we can introduce this idea in Check API, too.
This is a follow-up of https://github.com/openfga/openfga/pull/855
Ran a load test for 10 minutes on both this PR and main: `ab -r -t 600 -c 100 -p body.txt -T application/json http://localhost:8080/stores/01H4SEESD718G51KWP3GHBKNE7/list-objects`
=> fix: in ListObjects API, Check calls have now a bounded number of concurrent database reads

.config-schema.json, cmd/run/flags.go, cmd/run/run.go, cmd/run/run_test.go, internal/graph/check.go, internal/graph/check_test.go, pkg/server/commands/connected_objects.go, pkg/server/commands/list_objects.go, pkg/server/server.go, pkg/server/server_test.go, pkg/server/test/connected_objects.go, pkg/server/test/list_objects.go, pkg/server/test/server.go
(It'd be nice if this was merged first: https://github.com/openfga/openfga/pull/833)
Add two new server configuration settings:
- MAX_CONCURRENT_READS_FOR_CHECK controls, ultimately, database connections used
- MAX_CONCURRENT_READS_FOR_LIST_OBJECTS controls, ultimately, database connections used
- RESOLVE_NODE_BREADTH_LIMIT (not too happy with this name but i want it to mimic RESOLVE_NODE_LIMIT since they are kind of similar) controls, ultimately, goroutines spun up
Follow-up PR of https://github.com/openfga/openfga/pull/860
=> feat: add three server settings to control resources used by Check API

pkg/server/commands/connectedobjects/connected_objects.go, pkg/server/commands/list_objects.go, pkg/server/test/connected_objects.go, pkg/server/test/server.go
Follow-up of https://github.com/openfga/openfga/pull/872.
- `ConnectedObjectsCommand` -> `ConnectedObjectsQuery`  (command modifies data, query doesn't)
- `ConnectedObjectsQuery.StreamedConnectedObjects()` -> `ConnectedObjectsQuery.Execute()`  (same pattern as other queries/commands)
- `ListObjectsQuery`'s and `ConnectedObjectsQuery`'s struct fields are now private (same pattern as other queries/commands)
- `ConnectedObjectsQuery.Limit` -> `ConnectedObjectsQuery.MaxResults` (same as ListObjectsQuery)
No functional changes
=> style: naming of connected objects query

Dockerfile
Speed up docker builds by not downloading every dependency every time.
https://docs.docker.com/build/guide/mounts/#add-a-cache-mount
=> build: speed up docker builds

docker-compose.yaml
Updates jaegar service to user a badger local storage backend instead of in-memory to provide persistence
Fixes: #868
=> feat: badger for persisting tracing data

.config-schema.json, cmd/run/run.go, pkg/server/server.go, pkg/server/server_test.go
The defaults for concurrency read limits should be unbounded to match preexisting behavior. Constraining the concurrency limits should be an "opt in" setting.
Close https://github.com/openfga/openfga/issues/915
=> fix: concurrency read settings should be unbounded by default

assets/tests/consolidated_1_1_tests.yaml, pkg/server/server.go
I introduced a regression in https://github.com/openfga/openfga/commit/24ab5f2f8197412a24449b5993d7fc12375ac7be
When there is an error in Check (e.g. a timeout or a model too complex), a panic is thrown. https://github.com/openfga/openfga/actions/runs/5753573580/job/15597084481#step:4:62
=> test: add Check test when resolution is too complex

cmd/migrate/migrate.go
simply fix #774 adding a more coherent description for the timeout flag.
Was suggested by @jon-whit the separation between db timeout and migration timeout on https://github.com/openfga/openfga/issues/774#issuecomment-1563085833 but as noticed in https://github.com/pressly/goose/issues/576 goose does not provide a timeout mechanism neither accepts a context as parameter (which could be potentially a `context.WithTimeout`).
So to avoid a kludge solution and address the main issue, I just adjusted the flag description.
=> fix: the misconception between 'migration timeout' and 'database connection timeout'

internal/graph/check.go, internal/graph/check_test.go, pkg/typesystem/typesystem.go, pkg/typesystem/typesystem_test.go
Do not get userset if only direct relations are possible
First step for https://github.com/openfga/openfga/issues/852
=> feat: optimizing check call by pruning user lookup

cmd/run/run.go, cmd/run/run_test.go, pkg/middleware/http/handler.go, tests/check/check_test.go, tests/tests.go
Add an integration test that asserts that an expected request log is emitted with the expected shape for one Check request.
https://github.com/openfga/openfga/issues/918
=> test: assert emitted log during Check request

.github/workflows/main.yaml, .github/workflows/pull_request.yaml, Makefile
To optimize CICD time, only run benchmark test against memory datastore.
Close https://github.com/openfga/openfga/issues/939
=> chore: only run memory check in regular cicd benchmark

pkg/server/commands/list_objects.go
Change log message emitted when a ListObjects call times out.
Before
```go
openfga  | {"level":"warn","timestamp":1692656780.110943,"msg":"list objects timeout with list object configuration timeout","build.version":"dev","build.commit":"none","timeout duration":"1ms"}
```
After
```go
openfga  | {"level":"warn","timestamp":1692656654.7408397,"msg":"list objects timeout after 1ms","build.version":"dev","build.commit":"none"}
```
=> fix: log when ListObjects call times out

pkg/testfixtures/storage/mysql.go, pkg/testfixtures/storage/storage.go
Fix the `failed to connect to mysql container: driver: bad connection` error that sometimes triggers when running `make unit-test` locally or, very rarely, in Github: https://github.com/openfga/openfga/actions/runs/5558243992/job/15057407607#step:5:58
Locally (note: the failures seen below are unrelated)
```shell
[22/08/23 7:10:23] ~/GitHub/openfga (fix-mysql-bad-connection) $ for ((i=1; i<=1000; i++)); do
echo "Running test iteration $i"
make unit-test
done
Running test iteration 1
tools.go:7:2: import "github.com/golang/mock/mockgen" is a program, not an importable package
go generate ./...
go test -race \
-coverpkg=./... \
-coverprofile=coverageunit.tmp.out \
-covermode=atomic \
-count=1 \
-timeout=5m \
./...
?       github.com/openfga/openfga/assets       [no test files]
? …
```
=> fix: 'bad connection' error when running MySQL tests

pkg/server/errors/encoded_errors.go, pkg/server/errors/encoded_errors_test.go
=> fix: send 403 instead of 500 when unauthenticated

internal/authn/oidc/oidc.go
- Set the value of `jwkRefreshInterval` to `48 * time.Hour` since it's not necessary to define from time.ParseDuration func
=> refactor: update jwkRefreshInterval value

.config-schema.json, cmd/run/flags.go, cmd/run/run.go, cmd/run/run_test.go, docker-compose.yaml, pkg/telemetry/tracing.go
Right now, OTEL tracing uses gRPC with the insecure option. This PR makes the insecure option optional. Users are free to opt in for secure traces export using `OPENFGA_TRACE_OTLP_TLS_ENABLED`.
Related PR on `openfga.dev`: https://github.com/openfga/openfga.dev/pull/485
Also see: https://github.com/open-telemetry/opentelemetry-go/blob/main/exporters/otlp/otlpmetric/internal/oconf/options.go#L134 which is called from here: https://github.com/open-telemetry/opentelemetry-go/blob/main/exporters/otlp/otlptrace/otlptracegrpc/client.go#L65 when setting up new otlptracegrpc exporter/client. The `Insecure` configuration is handled internally based on env variables.
=> feat(tracing): configurable security

pkg/server/commands/list_objects.go, pkg/server/server.go, pkg/storage/storagewrappers/boundedconcurrency.go, pkg/storage/storagewrappers/boundedconcurrency_test.go
Add configurable concurrency limit for list object
Close https://github.com/openfga/openfga/issues/955
Add the following model
```
model
schema 1.1
type doc
relations
define can_change_owner: owner
define can_read: viewer or owner or viewer from parent
define can_share: owner or owner from parent
define can_write: owner or owner from parent
define owner: [user]
define parent: [folder]
define viewer: [user,user:*,group#member]
type folder
relations
define can_create_file: owner
define owner: [user]
define parent: [folder]
define viewer: [user,user:*,group#member] or owner or viewer from parent
type group
relations
define member: [user]
type user
```
With the follow tuples
```
{
"tuples": [
{
"key": {
"object": "folder:1",
"relation": "owner",
"user": "user:test_user"
},
"timestamp": …
```
=> feat: list objects should limit number of DB reads on every call

cmd/run/run.go, pkg/server/server.go
Move RPC request validation into the RPC handlers instead of as a top-level middleware on the standalone server.
This change allows developers who use OpenFGA as a library to get the same validations that the standalone server provides. Since middleware doesn't apply to the RPC handler, we move validation inside of the RPC handler.
- Closes https://github.com/openfga/openfga/issues/965
- Relates to https://github.com/openfga/cli/issues/141 - this PR allows the CLI test command to have proper validations when the OpenFGA server is embedded
- https://github.com/openfga/openfga/issues/871
=> refactor(validation): move request validations to RPC handlers

pkg/server/commands/connectedobjects/connected_objects.go, pkg/server/commands/list_objects.go, pkg/server/server.go, pkg/server/test/connected_objects.go, pkg/server/test/list_objects.go
Adding trace information on datastore query count for list object
Close https://github.com/openfga/openfga/issues/956
Close https://github.com/openfga/openfga/issues/938
=> feat: add datastore query count for list object on trace and histogram

internal/graph/graph.go, internal/graph/graph_test.go, pkg/server/commands/list_objects.go, pkg/server/commands/reverseexpand/reverse_expand.go, pkg/server/test/reverse_expand.go, pkg/server/test/server.go
Changes:
- Rename `ConnectedObjects -> ReverseExpand`
- Rename `ConnectedObjectsGraph -> RelationshipGraph`
- Rename `RelationshipIngress -> RelationshipEdge` (or sometimes `edge` when used as a variable)
- Updated a few comments
- Added a few TODOs (subject to discussion) which are added to https://github.com/openfga/openfga/issues/957
This is a requisite of https://github.com/openfga/openfga/pull/934
=> style: rename connected objects -> reverse expand

.vscode/launch.json, cmd/run/run.go, go.mod, internal/middleware/validator/validator.go, pkg/server/server.go
Rewires the request validation behavior so that the validation(s) run early in the middleware chain if you're running OpenFGA as a standalone server, but if you're using OpenFGA as a library then the validation context won't be set and so the validation will run inline when the RPC handlers are invoked by the client application.
This is a follow-up of https://github.com/openfga/openfga/pull/975
=> chore: rewire request validation

pkg/storage/storagewrappers/context.go
In class `ContextTracerWrapper` we have `defer cancel()` everywhere. But `cancel()` is a no-op. So, i'm removing it to make it obvious that we are NOT cancelling the context.
=> style: context storage wrapper

pkg/server/commands/write.go, pkg/server/commands/write_test.go
If an implementation of OpenFGA's storage adapter interface produces an `ErrTransactionalWriteFailed` error due to a transaction concurrency conflict, then OpenFGA should return an internal server error to the client indicating that the request should be retried. After retrying, if at least one of the two concurrent modifications was durably persisted, then the subsequent (retried) request should fail with a `ErrInvalidWriteInput` error because the tuple has since been written and thus the second write would otherwise cause a duplicate.
=> fix: change response code to internal error for concurrency conflicts

.github/.mlc_config.json, .github/workflows/markdown-links.yaml, CHANGELOG.md, README.md
This PR adds a new Github Actions workflow to check if the links in the markdown files are alive or dead. It uses a third-party action [markdown-link-check](https://github.com/marketplace/actions/markdown-link-check), to accomplish this.
Closes #1013, #1014
=> chore: add workflow to check markdown links

pkg/middleware/validator/validator.go
- This PR migrates the validator interceptor from `github.com/grpc-ecosystem/go-grpc-middleware/validator` to `github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/validator`
https://github.com/grpc-ecosystem/go-grpc-middleware/tree/main/interceptors/validator
=> chore: migrate grpc validator to go-grpc-middleware/v2/interceptors/validator

assets/migrations/mysql/004_add_authorization_model_serialized_protobuf.sql, assets/migrations/postgres/004_add_authorization_model_serialized_protobuf.sql, pkg/storage/mysql/mysql.go, pkg/storage/mysql/mysql_test.go, pkg/storage/postgres/postgres.go, pkg/storage/postgres/postgres_test.go, pkg/storage/sqlcommon/sqlcommon.go, pkg/storage/test/authz_models.go
- Migration: Add new `serialized_protobuf` column
- WriteAuthorizationModel: create rows for each type definition but including `serialized_protobuf`
- ReadAuthorizationModel: if a row containing a non-null value for `serialized_protobuf`, return this as the model.
https://github.com/openfga/openfga/issues/1025
=> feat: persist authz model serialized protobuf

.config-schema.json, cmd/run/flags.go, cmd/run/run.go, pkg/server/commands/write_authzmodel.go, pkg/server/server.go, pkg/server/test/write_assertions.go, pkg/server/test/write_authzmodel.go
Following up on #1028, we're introducing a new config knob `MAX_AUTHORIZATION_MODEL_SIZE_IN_BYTES` with a default of `256KB`, providing a consistent size limit across datastores.
We're picking a default value of `262144` bytes which is a fraction of the size limits in Postgres' BYTEA datatype (1GB) and MySQL's LONGBLOB datatype (4GB) which are used in the `serialized_protobuf` column of the `authorization_model` table.
https://github.com/openfga/openfga/pull/1028
=> feat: limit size in bytes of authz models

pkg/server/test/read_changes.go, pkg/server/test/server.go
Add a test that ensures that concurrent tuple writes do not impact ReadChanges API (as in, return duplicate results).
=> test: add test for ReadChanges when writes happen concurrently

pkg/storage/mysql/mysql.go, pkg/storage/mysql/mysql_test.go, pkg/storage/postgres/postgres.go, pkg/storage/postgres/postgres_test.go, pkg/storage/sqlcommon/sqlcommon.go, pkg/storage/test/storage.go
- Reduce code duplication
- Improve code coverage
Originally suggested in https://github.com/openfga/openfga/pull/702 but put here so it's faster to merge.
=> test: add test for datastore.IsReady

cmd/run/run.go, internal/authn/oidc/oidc.go, internal/authn/presharedkey/presharedkey.go, internal/middleware/authn/authn.go, pkg/server/health/health.go
- This PR migrates the auth interceptor from `github.com/grpc-ecosystem/go-grpc-middleware/auth` to `github.com/grpc-ecosystem/go-grpc-middleware/v2/interceptors/auth`
https://github.com/grpc-ecosystem/go-grpc-middleware/tree/main/interceptors/auth
=> chore: migrate grpc auth to go-grpc-middleware/v2/interceptors/auth

go.mod, go.sum
Fixes reported vulnerabilities as reported by `govulncheck`.
=> chore(dep): bump Go and net package up to avoid govulncheck reports

pkg/server/commands/list_objects.go, pkg/server/commands/reverseexpand/reverse_expand.go, pkg/server/server_test.go, pkg/server/test/reverse_expand.go
This fixes a problem where dangling goroutines in ReverseExpand are all blocked on a channel that no longer has a listener. Instead, we listen on context and if it is cancelled we avoid trying to send on the channel.
https://github.com/openfga/openfga/issues/1033
=> fix: avoid forgotten sender with context cancellation in ReverseExpand

.github/workflows/main.yaml, .github/workflows/pull_request.yaml, Makefile
How it works after this PR: on push to `main` we generate and save benchmarks and on every commit to a PR we compare against `main`.
Tested in a personal repo: https://github.com/miparnisari/benchtest/actions/runs/6589243682/job/17903264164?pr=22
=> ci: fix benchmark reporting

.config-schema.json, cmd/run/flags.go, cmd/run/run.go, cmd/run/run_test.go, internal/server/config/config.go, pkg/storage/mysql/mysql.go, pkg/storage/postgres/postgres.go, pkg/storage/sqlcommon/sqlcommon.go
Exports DB metrics (if metrics are enabled) via prometheus.
Question: shuld this be added behind additional config field under `metrics`?
Exports DB metrics, such as time spent waiting for free connection, pool stats, query stats, and more if the metrics are enabled. For full list of metrics you can see [prometheus/client_golang](https://github.com/prometheus/client_golang/blob/main/prometheus/collectors/dbstats_collector.go).
- Didn't find any section where this would need to be added.
=> feat(storage): track db metrics

pkg/server/test/get_store.go, pkg/server/test/read.go, pkg/server/test/read_changes.go, pkg/storage/iterators_test.go, pkg/storage/test/storage.go
This PR addresses https://github.com/openfga/openfga/issues/894 by using **protocmp** functions to check that proto messages in unit tests are semantically equal
https://github.com/openfga/openfga/issues/894
=> Fix protobuf comparison

docker-compose.override.yaml, docker-compose.yaml
Fix https://github.com/openfga/openfga/issues/1047
- basic `docker-compose.yaml` will have the most minimal setup necessary (just openfga & postgres). So that the [README steps](https://github.com/openfga/openfga#docker-compose) work
- `docker-compose.override.yaml` will have all the observability enabled for easier debugging
```
$ docker-compose -f docker-compose.yaml -f docker-compose.override.yaml up
// spins 6 containers
$ docker-compose -f docker-compose.yaml up
// spins 2 containers
```
=> chore: fix docker-compose.yaml

pkg/server/commands/read_assertions.go, pkg/server/server_test.go, pkg/server/test/server.go, pkg/server/test/write_assertions.go
Update unit test so that we read assertion after write assertion
=> test: adding unit tests to validate result of read assertion

pkg/condition/condition.go, pkg/condition/condition_test.go, pkg/condition/types/ipaddress.go
Add a converter overload to convert a CEL string to a custom IPAddress type. This adds the ability to do the following in ABAC Conditions
```
...
condition my_cond() {
ipaddress("192.168.0.01").in_cidr("192.168.0.0/24")
}
```
=> fix(ipaddr): add overload for casting string to ipaddress

pkg/server/commands/reverseexpand/reverse_expand_test.go
Goal: debug flaky test https://github.com/openfga/openfga/actions/runs/6723611407/job/18274057202?pr=1096
It is hard to reproduce locally. Adding logs so when it happens again we can debug it. E.g.
```
=== RUN   TestReverseExpandRespectsContextCancellation
reverse_expand_test.go:60: before execute reverse expand
reverse_expand_test.go:78: before receive one result
reverse_expand_test.go:48: returning tuple iterator
reverse_expand_test.go:80: after receive one result
reverse_expand_test.go:82: after send cancellation
reverse_expand_test.go:73: after execute reverse expand
reverse_expand_test.go:89: OK!
--- PASS: TestReverseExpandRespectsContextCancellation (0.01s)
PASS
Process finished with the exit code 0
```
=> test: add logs to reverse expand test

.golangci.yaml, pkg/server/commands/reverseexpand/reverse_expand.go
```
[2/11/23 2:58:19] ~/GitHub/openfga (main) $ make lint
pkg/server/commands/reverseexpand/reverse_expand.go:456:7: unusedwrite: unused write to field Type (govet)
Type: req.sourceUserRef.GetObjectType(),
^
pkg/server/commands/reverseexpand/reverse_expand.go:468:21: unusedwrite: unused write to field RelationOrWildcard (govet)
sourceRelationRef.RelationOrWildcard = &openfgav1.RelationReference_Relation{
^
make: *** [lint] Error 1
```
=> style: stricter govet linter

pkg/condition/condition.go, pkg/condition/condition_test.go, pkg/condition/errors.go, pkg/condition/eval/eval.go, pkg/condition/eval/eval_test.go, pkg/condition/types/converters.go, pkg/condition/types/generic.go, pkg/condition/types/types.go, pkg/condition/types/types_test.go, pkg/server/errors/errors.go
- Expose `CompilationError`, `EvaluationError`, and `ParameterTypeError`
- Tweak error messages
- Expose these errors instead of returning internal server errors
https://github.com/openfga/openfga/pull/1038
=> fix: expose errors from conditions

pkg/condition/errors.go
before
```
ⅹ Check(user=user:jon,relation=has_feature,object=feature:one): expected=true, got=N/A, error=rpc error: code = InvalidArgument desc = failed to evaluate relationship condition 'is_valid': parameter type error on condition 'is_valid': failed to convert context parameter '_timestamp': expected RFC 3339 formatted timestamp string, but found '1990-02-01'
```
after
```
ⅹ Check(user=user:jon,relation=has_feature,object=feature:one): expected=true, got=N/A, error=rpc error: code = InvalidArgument desc = parameter type error on condition 'is_valid': failed to convert context parameter '_timestamp': expected RFC 3339 formatted timestamp string, but found '1990-02-01'
```
https://github.com/openfga/openfga/pull/1038
=> fix: improve param type errors during evaluation

.github/workflows/release.yaml
Make sure third party actions on release workflow are pinned to specific sha.
```
npx pin-github-action -i .github/workflows/release.yaml
```
=> chore: pin third party actions

.golangci.yaml, cmd/migrate/migrate_test.go, cmd/openfga/main_test.go, cmd/run/run_test.go, cmd/util/util.go, cmd/validatemodels/validate_models_test.go, internal/graph/cached_resolver_test.go, pkg/middleware/requestid/requestid_test.go, pkg/middleware/validator/validator_test.go, pkg/server/commands/reverseexpand/reverse_expand_test.go, pkg/server/server_test.go, pkg/server/test/list_stores.go, pkg/server/test/read_authzmodels.go, pkg/storage/mysql/mysql_test.go, pkg/storage/postgres/postgres_test.go, pkg/storage/test/assertions.go, pkg/storage/test/stores.go, pkg/tuple/tuple_test.go
- Add new linter rule `testifylint` which was introduced since golangci-lint v1.55.0
- Issues fixed
```
cmd/util/util.go:77:2: error-nil: use require.NoError (testifylint)
require.Nil(t, os.Mkdir(confdir, 0750))
^
cmd/util/util.go:85:2: error-nil: use require.NoError (testifylint)
require.Nil(t, err)
^
cmd/util/util.go:87:2: error-nil: use require.NoError (testifylint)
require.Nil(t, err)
^
pkg/server/test/list_stores.go:42:2: empty: use require.Empty (testifylint)
require.Equal(t, 0, len(listStoresResponse.Stores))
^
pkg/server/test/list_stores.go:59:2: len: use require.Len (testifylint)
require.Equal(t, 1, len(listStoresResponse.Stores))
^
pkg/server/test/list_stores.go:69:2: len: use require.Len (testifylint)
require.Equal(t, 1, len(secondListStoresResponse.Stores))
^ …
```
=> chore: add testifylint

assets/tests/abac_tests.yaml, assets/tests/consolidated_1_1_tests.yaml, internal/errors/errors.go, internal/graph/check.go, internal/test/check/check.go, internal/test/listobjects/listobjects.go, pkg/condition/condition.go, pkg/condition/errors.go, pkg/condition/eval/eval.go, pkg/server/commands/list_objects.go, pkg/server/commands/reverseexpand/reverse_expand.go, pkg/server/errors/errors.go, pkg/server/server.go, tests/check/check.go, tests/listobjects/listobjects.go
These changes modify the server behavior to return errors instead of deny decisions when we attempt to evaluate an ABAC Condition that we cannot fully evaluate. For example,
```
type user
type document
relations
define viewer: [user with condxy]
condition condxy(x: int, y: int) {
x < 10 || y < 10
}
- document:1#viewer@user:jon, {condition: "condxy"}
```
Evaluating `Check(document:1#viewer@user:jon, { context: { } })` would return an error instead of `{allowed: false}`.
The changes also are strict about requiring every parameter of an condition to be specified even if it is not necessary to fully evaluate the condition. We chose to do this to be explicit about the type system. We may change this at a later time. Using the example above,
`Check(document:1#viewer@user:jon, { context: { "x": …
=> chore(abac): return errors instead of deny decision with ABAC conditions

docker-compose.override.yaml
This pull request change the Jaeger image version from` latest `to `1.49`.
=> chore: set jaeger image version to v1.49 (openfga#1102)

.github/workflows/release.yaml
Add missing step to snyk job.
```
⚠ Important: Beginning January 24th, 2023, application dependencies in container
images will be scanned by default when using the snyk container test/monitor
commands. If you are using Snyk in a CI pipeline, action may be required. Read
https://snyk.io/blog/securing-container-applications-using-the-snyk-cli/ for
more info.
ENOENT: no such file or directory, open 'Dockerfile'
```
Follow up to #1112
https://github.com/openfga/openfga/actions/runs/6777586634/job/18421636656
=> chore: fix snyk job in release workflow

Dockerfile, Dockerfile.goreleaser
Bump grpc-health-probe to v0.4.22
https://github.com/grpc-ecosystem/grpc-health-probe/releases/tag/v0.4.22
https://github.com/grpc-ecosystem/grpc-health-probe/pull/166
=> chore: bump grpc-health-probe to v0.4.22

.github/workflows/release.yaml
Follow up to #1112, adding a verification step that runs `slsa-verifier` on released assets.
#1112
=> chore: run verification with slsa-verifier

.github/workflows/release.yaml
Use the pinned version of `slsa-github-generator` ([commit id](https://github.com/slsa-framework/slsa-github-generator/commit/07e64b653f10a80b6510f4568f685f8b7b9ea830)). For security & to increase OpenSSF Scorecard score for Pinned dependencies. Currently, all of the dependencies are fine, except one (see [here](https://api.securityscorecards.dev/projects/github.com/openfga/openfga)):
=> use pinned version for `slsa-github-generator`

Dockerfile, docker-compose.yaml
This pull request adds a gRPC health probe to the Dockerfile, which will be used to check the health of the container. The healthcheck configuration in `docker-compose.yaml` file has been removed and replaced with the new gRPC health probe. This change ensures that the container is considered healthy only if the gRPC health probe returns a successful response.
fixes #1117
=> Healthcheck in `OpenFGA` Dockerfile 

cmd/run/run.go
Set global tracer provider to a Noop TracerProvider if tracing is disabled.
https://github.com/openfga/openfga/issues/1105
=> chore(trace): use Noop TracerProvider if tracing is disabled

.golangci.yaml, tests/check/check_test.go
- Add `mirror` linter and fix issue
```
tests/check/check_test.go:143:17: avoid allocations with bytes.NewBufferString (mirror)
httpReqBody: bytes.NewBuffer([]byte(`{
^
```
=> style: add `mirror` linter

docker-compose.override.yaml
Bring a change lost in https://github.com/openfga/openfga/pull/1092/files#diff-3fde9d1a396e140fefc7676e1bd237d67b6864552b6f45af1ebcc27bcd0bb6e9
Before this PR:
```
$ docker-compose up --build openfga
✔ Container postgres       Created                                                                      0.1s 
✔ Container migrate        Created                                                                      0.1s 
✔ Container openfga        Created                                                                      0.1s 
Attaching to openfga
openfga  | 2023-11-14T23:53:46.923Z     INFO    🕵 tracing enabled: sampling ratio is 1 and sending traces to 'otel-collector:4317', tls: false
openfga  | panic: failed to establish a connection with the otlp exporter: context deadline exceeded …
```
=> build: openfga depends on otel-collector

pkg/testfixtures/storage/mysql.go, pkg/testfixtures/storage/postgres.go
For https://github.com/openfga/openfga/issues/1140.
There's probably more things that we can do, but this is a start.
Before:
```shell
[14/11/23 6:35:06] ~/GitHub/openfga (main) $  grep -E "PASS:.*?\(\d+\.\d+s\)" tests.txt | sed -E 's/.*PASS:\s*(.*)\s*\((.*)s\)/\1\t\2/g' | sed -E 's/ //g' | sort --reverse -nk2 |  head -n 20
TestValidationResult    137.92
TestValidationResult/mysql      128.92
TestServerMetricsReporting      126.89
TestMySQLDatastore      118.86
TestServerMetricsReporting/mysql        114.72
TestMigrateCommandRollbacks     100.41
TestMigrateCommandRollbacks/mysql       91.74
TestServerWithMySQLDatastoreAndExplicitCredentials      70.46
TestServerWithMySQLDatastore    66.83
TestCheckMySQL  60.59
TestListObjectsMySQL    60.56
TestListObjectsPostgres 53.80 …
```
=> test: speed up integration tests for mysql and postgres

pkg/server/test/list_objects.go
Storage implementations might rightfully expect authorization model's id to be a non empty string.
=> tests: make sure models have ids

cmd/migrate/flags.go, cmd/migrate/migrate.go, cmd/migrate/migrate_test.go
Before, openfga run had the possibility to overwrite the username / password present in the run command, but not in the migrate command.
This commit fixes it by adding the flags and the corresponding behavior to the migrate command. Furthermore it adds the env variable handling from run also to migrate
Fixes #1125
=> Add env vars and username/password overwrite for migrate tool

Makefile, pkg/server/test/read.go, pkg/storage/memory/memory.go, pkg/storage/memory/memory_test.go, pkg/storage/record.go, pkg/storage/record_test.go
Bring these changes over to `main`: 
- https://github.com/openfga/openfga/pull/999/files#diff-76e1d9c2639fc6c407f987f2698d74723cbe632c79cb31a5e0c1140dd33783b7
- https://github.com/openfga/openfga/pull/999/files#diff-bae0ac15d10001bd5dd35974bc2075e71b6dbc7d590a3157b40ded4480ace797
(I removed all the ABAC-related stuff in this PR)
The reason for this change is to lay the groundwork for `feat/abac`. Currently, the `feat/abac` branch has a regression for the memory storage adapter. See https://github.com/openfga/openfga/actions/runs/7009608156/job/19068427402?pr=1038. Specifically, the regression is that we are introducing lots of calls to `AsTuple`:
```shell
git checkout feat/abac
go test -run=XXX -bench=BenchmarkCheckMemory/BenchmarkCheckWithDirectResolution -benchtime 5s -memprofile …
```
=> chore: memory storage stores TupleRecords internally

.github/workflows/stale-bot.yaml
Adds a bot to detect stale PRs and issues. The staleness check has been configured to not automatically close any PR or issue, but we do give warning that if action is not taken then the maintainer reserves the right to close it without further activity.
By default PRs and issues will be labeled with the `stale` label. So that will allow us as a maintainer team to quickly search/filter for the issues and PRs that are inactive.
https://github.com/actions/stale
=> ci(stale-bot): add stale bot to check for stale PRs and issues

.config-schema.json, cmd/run/run.go, internal/server/config/config.go, pkg/server/commands/write.go, pkg/server/commands/write_authzmodel.go, pkg/server/server.go, pkg/server/server_test.go
In #1169, I introduced the default `reject-conditions` experimental flag. In order to run server and enable conditions you have to do something like `OPENFGA_EXPERIMENTALS="-"` which is clunky.
> Since we default reject-conditions and it’s the only experimental, it’s a negative negative, which means it can never be true.
This PR, changes that in favor of `enable-conditions` experimental flag which is not set by default.
Follow up to https://github.com/openfga/openfga/pull/1169
=> fix: inverse experimental flag for conditions

cmd/run/run.go
After changes introduced in https://github.com/openfga/openfga/pull/1139, children spans went missing.
See https://github.com/openfga/openfga/pull/1038#pullrequestreview-1756471345
I'll follow up this change with some improvements to our telemetry package and some tests.
https://github.com/openfga/openfga/pull/1139
=> fix: correctly set noop trace provider

internal/validation/validation.go, pkg/server/commands/reverseexpand/reverse_expand.go
Prior to ABAC Conditions we'd only reverse expand edges that were relevant to the model. Consequently, we had no need for similar tuple [filter iterator code](https://github.com/openfga/openfga/blob/main/internal/graph/check.go#L573-L577) like we have in check.
Now that we introduce conditions into the mix, between two models we can have the same relationship edges but with incompatible conditions defined for type restrctions. This means that we must also now filter the tuples yielded by `ReadStartingWithUser`.
These changes fixes this test:
https://github.com/openfga/openfga/blob/13a1dec951623513056a5c894f6ed650d4d1c449/assets/tests/abac_tests.yaml#L589
=> fix: filter out tuples with non-matching conditions from reverse expand

.github/workflows/release.yaml
```
Run set -euo pipefail
set -euo pipefail
gh -R "$GITHUB_REPOSITORY" release download "$GITHUB_REF_NAME" \
-p "$PROVENANCE" -p "*.tar.gz" -p "*.tar.gz.sbom" -p
shell: /usr/bin/bash -e {0}
env:
GH_TOKEN: ***
PROVENANCE: openfga.intoto.jsonl
flag needs an argument: 'p' in -p
Usage:  gh release download [<tag>] [flags]
Flags:
-A, --archive format        Download the source code archive in the specified format (zip or tar.gz)
--clobber               Overwrite existing files of the same name
-D, --dir directory         The directory to download files into (default ".")
-O, --output file           The file to write a single asset to (use "-" to write to standard output)
-p, --pattern stringArray   Download only assets that match a glob pattern
--skip-existing         Skip downloading when …
```
=> chore: remove extraneous param in slsa verification step

pkg/storage/mysql/mysql_test.go, pkg/storage/postgres/postgres_test.go, pkg/storage/test/tuples.go
Add storage conformance tests for normalization behavior around TupleKeys with conditions and condition context. Namely, if you write a tuple with a `nil` condition it should come back as a nil condition. Conditions are nullable. Likewise,  if you specify a non-empty condition in a tuple we normalize condition context to an empty context if the context is `nil`.
=> test(storage): add conformance test for normalized Condition behavior

pkg/server/commands/write.go, pkg/server/commands/write_test.go, pkg/server/errors/encoded_errors.go, pkg/server/errors/encoded_errors_test.go, pkg/storage/errors.go
In the case of error is write failure is due to ErrTransactionalWriteFailed.  We should return 409 instead of 500 error.
Close https://github.com/openfga/openfga/issues/1080
Corresponding change https://github.com/openfga/api/pull/107
=> fix: storage conflict errors return 409 instead of 500

cmd/run/run.go
`listObjects-deadline` and `max-concurrent-reads-for-list-objects` only explicitly mentioned `ListObjects`. To be very clear and precise, this PR includes the `StreamedListObjects in those help descriptions. This is because those flags control behavior for both of those endpoints given that they share a common underlying implementation.
=> chore: improve flag descriptions

cmd/run/run.go, pkg/middleware/logging/logging.go, tests/check/check_test.go
Close https://github.com/openfga/openfga/issues/918 and https://github.com/openfga/openfga/issues/935
Now, all **unary** requests that are invalid (for example, a missing parameter) will be logged in the server.
With the tests in this PR + manual tests:
Logs in Main vs this PR:
Traces in this PR:
Response headers in this PR
=> fix: #935 (log request validation errors)

.goreleaser-nightly.yaml, .goreleaser.yaml, cmd/run/run_test.go, internal/build/build.go, internal/condition/eval/eval.go, internal/graph/cached_resolver.go, internal/server/config/config.go, internal/server/config/config_test.go, internal/utils/bucket.go, internal/utils/bucket_test.go, pkg/server/commands/list_objects.go, pkg/server/server.go, pkg/storage/storagewrappers/boundedconcurrency.go, pkg/typesystem/typesystem.go, pkg/typesystem/typesystem_test.go
Add a prometheus histogram metric to calculate the distribution of Condition evaluation costs. 
Additionally, I've wired up the `Namespace` field so it reports the project name `openfga`.
=> chore: add prometheus histogram metric for Condition evaluation cost

pkg/server/test/list_objects.go
Pre-requisite for: https://github.com/openfga/openfga/pull/1173
This PR updates the model used in ListObjects benchmarks so that it covers more code paths.
⚠️ this PR alerts of a performance regression. That is expected, since the model being benchmarked is more complex and requires more goroutines.
| Benchmark suite | Current: a7b23f6bb001836c82c09d657d3c12c1941e64d0 | Previous: 78422af76964abbfe524002a7dbf1f01e8ec8979 | Ratio |
|-|-|-|-|
| `BenchmarkOpenFGAServer/BenchmarkMemoryDatastore/BenchmarkListObjects/allResults - ns/op` | `379572501` ns/op | `182679092` ns/op | `2.08` |
=> test: update listObjects benchmark

pkg/storage/memory/memory.go
This PR refactors how we find the authorization model by ID within the memory storage in order to reduce the cyclomatic complexity from 5 to 4 and make the code easier and negligently faster to navigate.
=> chore: reduce complexity of storage.memory.findAuthorizationModelByID

CHANGELOG.md, cmd/run/run_test.go, internal/condition/metrics/metrics.go
In the `v1.4.1` release we added the `Namespace` field to the custom Prometheus metrics we define. This leads to a FQN with the namespace prefixed to the metric (e.g. `openfga_`) which changed the name of the metric as reported by the server.
The purpose of this PR is to note that in the `v1.4.1` release details and to improve the test which verifies the metrics are reporting as expected in a way that is more protected from false positives.
=> chore: improve metrics test and update `v1.4.1` CHANGELOG details

internal/mocks/mock_error_iterator.go, pkg/server/commands/reverseexpand/reverse_expand.go, pkg/server/commands/reverseexpand/reverse_expand_test.go
Convert some of the unexpected edge path to panics and clean up mock tests infrastructure
Implement feedback on https://github.com/openfga/openfga/pull/1297
=> chore: convert to panic on unexpected edge in reverse expand

.github/workflows/main.yaml, .github/workflows/pull_request.yaml, tests/check/check_test.go, tests/tests.go
We need to stop the benchmark timer when tear down is costly in terms of time, so that time spent tearing down is not added to the benchmark itself.
=> test: amend #1316

cmd/run/run.go, pkg/server/server.go, pkg/typesystem/resolver.go, pkg/typesystem/resolver_test.go, tests/check/check_test.go, tests/listobjects/listobjects_test.go
This is a follow-up of https://github.com/openfga/openfga/pull/1317.
Whether we use OpenFGA as a library or as a server, we need to provide an API to clean up Server resources.
=> feat: new server.Stop() to close all server resources

pkg/server/commands/list_objects.go, pkg/server/commands/reverseexpand/reverse_expand.go, pkg/server/commands/reverseexpand/reverse_expand_test.go, pkg/server/server_test.go, pkg/server/test/list_objects.go, pkg/server/test/reverse_expand.go, pkg/testfixtures/storage/mysql.go, pkg/testfixtures/storage/postgres.go, tests/listobjects/listobjects_test.go
Avoid the forgotten consumer problem between ListObjects and ReverseExpand which, under some query outcomes, could lead to memory leaks. In particular, if we hit the `--listObjects-deadline` while actively reverse expanding, then the ListObjects consumer listening on the ReverseExpand results channel would be left dangling and thus not release the resources back to the Go garbage collector. The changes herein fix that issue particularly and thus avoid memory leaks.
Closes https://github.com/openfga/openfga/issues/1309.
=> fix: handle ReverseExpand channel closure correctly

Dockerfile, Dockerfile.goreleaser
- Update grpc-health-probe to v0.4.24
- Fix incorrect path for grpc-health-probe in default healthcheck command.
=> chore: update grpc-health-probe

pkg/server/test/read.go, pkg/storage/test/storage.go, pkg/storage/test/tuples.go
This is a follow-up of https://github.com/openfga/openfga/pull/1325 with more tests 😆 
Two tests were missing, filter by user and object type, for both `Read` and `ReadPage`.
=> test: add more tests for ReadPage correctness

cmd/run/run.go, pkg/server/commands/reverseexpand/reverse_expand_test.go, pkg/storage/memory/memory_test.go, pkg/storage/storagewrappers/boundedconcurrency_test.go, pkg/storage/storagewrappers/caching_test.go, pkg/typesystem/resolver_test.go, tests/tests.go
Fix
```
Run golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc
prepare environment
run golangci-lint
Running [/home/runner/golangci-lint-1.56.0-linux-amd64/golangci-lint run --out-format=github-actions -v -c .golangci.yaml] in [] ...
Error: File is not `goimports`-ed with -local github.com/openfga/openfga (goimports)
Error: go-require: require must only be used in the goroutine running the test function (testifylint)
Error: go-require: require must only be used in the goroutine running the test function (testifylint)
Error: go-require: require must only be used in the goroutine running the test function (testifylint)
```
seen on https://github.com/openfga/openfga/actions/runs/7820454748/job/21335217274?pr=1345#step:4:29
=> chore: fix testifylint errors on tests

pkg/server/test/reverse_expand.go
Fix data race in test
```
==================
WARNING: DATA RACE
Read at 0x00c000de66c3 by goroutine 1303:
testing.(*common).logDepth()
/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1011 +0xcd
testing.(*common).log()
/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1004 +0xa4
testing.(*common).Logf()
/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1055 +0x6a
github.com/openfga/openfga/pkg/server/test.TestReverseExpand.func1.1()
/home/runner/go/pkg/mod/github.com/openfga/openfga@v1.4.4-0.20240201172210-29d9c34d421b/pkg/server/test/reverse_expand.go:1249 +0x1a6
Previous write at 0x00c000de66c3 by goroutine 1298:
testing.tRunner.func1()
/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1582 +0x8fa
runtime.deferreturn() …
```
=> test: fix data race in ReverseExpand test

pkg/server/test/list_stores.go
Fix potential panic in a test:
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1a18987]
goroutine 147 [running]:
testing.tRunner.func1.2({0x1bcbc20, 0x3c65e20})
/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1545 +0x3f7
testing.tRunner.func1()
/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1548 +0x716
panic({0x1bcbc20?, 0x3c65e20?})
/opt/hostedtoolcache/go/1.21.5/x64/src/runtime/panic.go:920 +0x270
github.com/openfga/openfga/pkg/server/test.TestListStores(0xc0008876c0, {0x30bb2b8?, 0xc0004d7400})
/home/runner/go/pkg/mod/github.com/openfga/openfga@v1.4.4-0.20240201172210-29d9c34d421b/pkg/server/te …
```
=> test: don't panic if ListStores fails

pkg/logger/logger.go
- Clean up code by using zap.ParseAtomicLevel to parse log level from string
=> refactor: use zap.ParseAtomicLevel to parse log level from string

internal/condition/condition_test.go
Intermittent failures have been observed with the `TestEvaluateWithInterruptCheckFrequency` test. These tests pertain to the CEL interpreter and the interaction between the interpreter's interrupt mechanism and context timeouts. Several of these tests will assert that the context will time-out before the CEL can be interpreted. However this creates a race condition and occasionally, the CEL will be interpreted before than the 1 microsecond timeout. The "fix" here is to add more loops to the CEL expression so that it takes longer than 1 microsecond to evaluate. This makes the test succeed much more reliably:
```
go test ./internal/condition/condition_test.go -race -run "TestEvaluateWithInterruptCheckFrequency" -count=10000
ok      command-line-arguments  115.756s
```
If this test continues …
=> test: Improving reliability of `TestEvaluateWithInterruptCheckFrequency`

cmd/run/run_test.go, internal/mocks/mock_tracing_server.go, tests/check/check_test.go
- Update mock tracing server helper to use `t.Cleanup` func, this function was introduced since Go 1.14 (https://go.dev/doc/go1.14)
=> refactor: use t.Cleanup func to stop mock tracing server

cmd/run/run.go, pkg/testutils/testutils.go, tests/tests.go
Fix false positive goroutine leak seen in https://github.com/openfga/openfga/actions/runs/7935612049/job/21669138931:
```shell
--- FAIL: TestListObjectsMySQL (34.92s)
tests.go:48: 
Error Trace:	/home/runner/work/openfga/openfga/pkg/testutils/testutils.go:200
/home/runner/work/openfga/openfga/tests/tests.go:48
/home/runner/work/openfga/openfga/tests/tests.go:32
/home/runner/work/openfga/openfga/tests/listobjects/listobjects_test.go:34
/home/runner/work/openfga/openfga/tests/listobjects/listobjects_test.go:23
Error:      	Received unexpected error:
rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial tcp 0.0.0.0:37117: connect: connection refused"
Test:       	TestListObjectsMySQL
Messages:   	server did not reach healthy status
mysql.go:106: …
```
=> fix: leaking goroutines in tests if server didn't start properly

cmd/run/run.go
Remove duplicate unix signal. `os.Interrupt` is `syscall.SIGINT`
https://cs.opensource.google/go/go/+/master:src/os/exec_posix.go;l=22?q=os.Interrupt&ss=go%2Fgo
=> refactor: remove duplicate unix signal

Dockerfile
This is a workaround to have Dependabot correctly propose updates for grpc-health-probe where we use a noop build stage to copy the dependency over to the final build stage artifact.
We should see updates for it like these https://github.com/openfga/openfga/pull/1380
https://github.com/dependabot/dependabot-core/issues/5103
=> chore: copy grpc-health-probe from a build stage

CHANGELOG.md
Updating changelog for upcoming v1.5.0 release.
=> docs(v1.5.0): add v1.5.0 release notes to CHANGELOG

pkg/server/test/write_authzmodel.go, pkg/typesystem/typesystem.go, pkg/typesystem/typesystem_test.go
In preparation for fixing https://github.com/openfga/openfga/issues/1385 and https://github.com/openfga/openfga/issues/1260, i am putting all the tests that exercise `typesystem.hasEntrypoints` in its own unit test `TestHasEntrypoints` so that (1) development cycle is shortened as I will only have to run `TestHasEntrypoints` to figure out if I broke something, and (2) I will be able to see which lines aren't covered more quickly.
I also updated `TestHasCycle` for similar reasons.
- Issues listed above
- Follow-up to this PR with all tests passing is https://github.com/openfga/openfga/pull/1405
=> test: add tests for typesystem.hasEntrypoints

pkg/server/errors/errors.go, pkg/server/errors/errors_test.go
Fix HandleTupleValidateError so that it handles invalid condition tuple error bugs.
Close https://github.com/openfga/openfga/issues/1419
1. Add with the following model
```
model
schema 1.1
type user
type group
relations
define member: [user]
define can_access: [user with less_than_hundred]
condition less_than_hundred(x: int) {
x < 100
}
```
Send GET with 
```
{
"tuple_key": {
"user": "user:test",
"relation": "can_access",
"object": "group:8"
},
"contextual_tuples": {
"tuple_keys": [
{
"user": "user:test",
"relation": "can_access",
"object": "group:8",
"condition": {
"name": "less_than_hundred",
"context": {
"x": "b"
}
}
}
]
}
}
```
and see 400 Bad Request error with body
```
{
"code": "validation_error",
"message": "Invalid tuple 'group:8#can_access@user:test (condition …
```
=> fix: handle invalid condition tuple error

.golangci.yaml, internal/condition/eval/eval_test.go, internal/condition/metrics/metrics.go, internal/server/config/config_test.go
Enabling `misspell` linter to improve our Go report card:
https://github.com/openfga/openfga/issues/598
=> style: enable misspell linter

cmd/run/run_test.go
Noticed after pulling https://github.com/openfga/openfga/pull/1417 locally and running tests that the order of the assertions is wrong. First we need to check that the call succeeded, then we check the status code in the response.
=> test: fix order of assertions

pkg/server/commands/list_objects.go, pkg/server/commands/reverseexpand/reverse_expand.go, pkg/server/server.go, pkg/server/test/reverse_expand.go
We have renamed the `QueryCount` variable we use internally for `ResolutionMetaData` to `DatastoreQueryCount`
Rename internal variable used in ListObjects `QueryCount` to `DatastoreQueryCount` to be consistent
- [] The correct base branch is being used, if not `main`
- [] I have added tests to validate that the change in functionality is working as expected
=> chore: Rename `QueryCount` to `DatastoreQueryCount`

cmd/run/run.go, cmd/run/run_test.go, pkg/server/server.go
Deprecate `request_duration_by_query_count_ms` in favour of `request_duration_ms`
- Add new histogram `request_duration_ms`
- Add the histogram to `Check`, `ListObjects` and `StreamedListObjects`
- Updated Histogram description
- Change configuration description for `request-duration-datastore-query-count-buckets` and `request-duration-dispatch-count-buckets`
- Added comment above `request_duration_by_query_count_ms` that it will be deprecated and removed soon
https://github.com/openfga/openfga/pull/1444#discussion_r1523596104
=> deprecate: Deprecate `request_duration_by_query_count_ms` in favour of `request_duration_ms`

assets/tests/consolidated_1_1_tests.yaml, tests/listusers/listusers.go
Suggestion for reviewers: hit "hide whitespace" when reviewing file changes.
- Adding more assertions for ListUsers API. 
- We have internal tickets tracking the extension of the tests to include coverage for ABAC (DXAZC-1916), contextual tuples (DXAZC-1915) and `and, but not` (DXAZC-1921)
Some reason for tests failures:
- contextual tuples need to be parsed
- duplicate results need to be cleaned
- if the filter is `type#relation`, we need to include `relation` in the response
- cycles need to be detected
- etc..
=> test: add more integration tests for ListUsers API

internal/test/listusers/listusers.go, pkg/server/commands/listusers/list_users_rpc.go, tests/listusers/listusers.go
`make(array, 1)` is not the same as `make(array, 0, 1)`
=> fix(list-users): initialization of response array

CHANGELOG.md
Add v1.5.1 release details to the CHANGELOG.
=> docs(v1.5.1): add v1.5.1 release notes to CHANGELOG

.github/workflows/release.yaml
Bump up slsa related workflows to v1.10.0 which should fix errors in provenance related steps of our last release.
https://github.com/openfga/openfga/actions/runs/8362142892
```
Verifying artifact slsa-generator-generic-linux-amd64: FAILED: error retrieving Rekor public keys: updating local metadata and targets: error updating to TUF remote mirror: invalid key
```
https://github.com/slsa-framework/slsa-github-generator/blob/v1.10.0/CHANGELOG.md#v1100
=> bump: slsa actions to v1.10.0

assets/tests/consolidated_1_1_tests.yaml, internal/test/listusers/listusers.go, tests/listusers/listusers.go
Currently, several of the existing integration tests are failing for `ListUsers`. This makes development difficult because as we implement and fix functionality, we have difficulty sifting through the noise. This PR intentionally skips the failing tests so that we can un-skip as we develop _and_ ensure that other tests do not begin failing.
Out of 165 tests, 27 are skipped (16%).
**Skip reasons**
- Returning relation w/ userset - 9
- Contextual tuple validation - 8
- Model validation errors - 5
- Intersection and wildcards - 2
- Not sure yet - 2
- Too-deep detection - 1
=> `ListUsers` temporarily skip failing tests as we develop

pkg/server/commands/reverseexpand/reverse_expand.go, pkg/tuple/tuple.go, pkg/tuple/tuple_test.go, pkg/typesystem/typesystem.go
There are multiple instances in the code where a typed public wildcard tuple (ex: `user:*`) is generated manually. Instead, I'm proposing a `TypedPublicWildcard` function that creates the tuple when provided a type as a string.
This work is inspired by https://github.com/openfga/openfga/pull/1485#discussion_r1538232311: 
> This should be a helper in the pkg/tuple package.
Also done in this PR is implementing more consistent usage of the `Wildcard` string and `BuildObject` function.
Related PR comment: https://github.com/openfga/openfga/pull/1485#discussion_r1538232311
=> `TypedPublicWildcard` function for creating wildcard tuples from type strings

.goreleaser-nightly.yaml, .goreleaser.yaml, Dockerfile.goreleaser, Makefile
Resolve the differences between the `Dockerfile` and the one used in the Goreleaser build `Dockerfile.goreleaser`. See:
https://github.com/openfga/openfga/blob/8526d5208ff7003aa7b7cc8e30c530052fd37b80/Dockerfile#L1
vs
https://github.com/openfga/openfga/blob/8526d5208ff7003aa7b7cc8e30c530052fd37b80/Dockerfile.goreleaser#L4
Closes #1504 (see https://github.com/orgs/openfga/discussions/290)
https://github.com/goreleaser/goreleaser/issues/4741
=> chore(deps): bump grpc-health-probe in Goreleaser built image

CHANGELOG.md
* test: fix data race in ReverseExpand test by @miparnisari in https://github.com/openfga/openfga/pull/1474
* docs: update security-self-assessment.md by @lj365 in https://github.com/openfga/openfga/pull/1456
* fix(check): count of datastore reads by @miparnisari in https://github.com/openfga/openfga/pull/1452
* bump: slsa actions to v1.10.0 by @jpadilla in https://github.com/openfga/openfga/pull/1478
* test: attempt at preventing 'bind: address already in use' by @miparnisari in https://github.com/openfga/openfga/pull/1468
* chore(deps): bump github.com/docker/docker from 25.0.4+incompatible to 25.0.5+incompatible by @dependabot in https://github.com/openfga/openfga/pull/1476
* release: add homebrew release job by @chenrui333 in https://github.com/openfga/openfga/pull/780
* CI: Add …
=> docs(v1.5.2): add v1.5.2 release notes to CHANGELOG

assets/tests/consolidated_1_1_tests.yaml, pkg/server/commands/listusers/list_users_rpc.go, pkg/server/commands/listusers/list_users_rpc_test.go
This PR fixes an issue in `ListUsers` where usersets weren't returning the relation in the response. Ex: (`group:fga` instead of `group:fga#member`). 
This bug occurred because we weren't checking the relation in the conditional when evaluating a userset _and_ because we weren't returning the correct object type. 
Parent PR: #1428
=> fix:`ListUsers` include correct relation when returning usersets

.config-schema.json, cmd/run/run.go, pkg/server/server.go, pkg/server/server_test.go
Wiring-up ListUsers endpoint with the `--experimentals` flag. This allows it to be enabled by running `openfga run --experimentals enable-list-users`. This follows a similar pattern as modular models experimental enablement in #1443. 
- Similar PR: #1443
=> fix: `ListUsers` experimental flag

.config-schema.json, pkg/server/commands/write_authzmodel.go, pkg/server/commands/write_authzmodel_test.go, pkg/server/server.go, pkg/server/server_test.go
Removes the experimental flag that was guarding the ability to write modular models/schema 1.2. 
I've left in some of the tests just to exercise that the ability to write 1.2 is there but happy to remove if that's perferred.
Original PR #1443
=> feat: remove experimentals for modular models/schema 1.2

cmd/run/run_test.go, internal/server/config/config.go, pkg/testutils/testutils.go, tests/check/check_test.go, tests/tests.go
Having the ability to spawn an in-process OpenFGA for testing purposes
is very handy and has been very useful for us.
A recent PR [1] moved it to an internal package, which made it hard to
use. So, this moves the aforementioned functions to an exported package
so folks can keep benefiting from these handy functions.
[1] https://github.com/openfga/openfga/pull/1468
=> chore: move `MustDefaultConfigWithRandomPorts` and `TCPRandomPort` to `testutils` package

assets/tests/consolidated_1_1_tests.yaml, pkg/server/commands/listusers/list_users_rpc.go, pkg/server/commands/listusers/list_users_rpc_test.go
Currently, the underlying algorithm for list users already mostly supports reflexive (self-defining) usersets. However, the `doesHavePossibleEdges` function validates the types in the request against the model and does not consider self-defining usersets as a valid edge. **Ex:** `ListUsers(object: "doc:1", relation: "viewer", user_filter: "doc#viewer")`. In this case, the endpoint exits early. So the solution here is to add another check for reflexive usersets specifically and prevent from exiting early.
**Reflexive Usersets**
The following demonstrates the behavior of reflexive usersets:
```
Check(user: "document:1#viewer", object: "document:1", relation: "viewer") // => true
ListUsers(object: "document:1", relation: "viewer", user_filter: "user") // => ["document:1#viewer",...] …
```
=> fix: `ListUsers` reflexive usersets support

internal/graph/cached_resolver.go
Avoid a race by creating a copy of the ResolveCheckResponse returned from the CachedCheckResolver. Since ResolveCheck is called concurrently across multiple goroutines, if two subproblems share the same cached Check subproblem then we'll see a race on the resolution metadata accesses to things like `DatastoreQueryCount` etc.. This fixes that by avoiding a shared referenced when we return the cached ResolveCheckResponse.
=> fix: CachedCheckResolver data race issues

internal/graph/cached_resolver_test.go
Add a unit test to verify that the `CachedCheckResolver` returns an immutable / copy of the cached `ResolveCheckResponse` instead of returning the original reference/pointer of the originally cached response.
Code under test: https://github.com/openfga/openfga/pull/1541
=> test: add a test for race conditions stemming from CachedCheckResolver

pkg/server/commands/listusers/list_users_rpc.go, pkg/server/commands/listusers/validate.go, pkg/server/list_users.go, pkg/server/server.go
Add basic tracing around one ListUsers request. This will allow us to see where errors are coming from, and troubleshoot performance issues.
Note:
- This doesn't cover tracing around evaluation of conditions, we'll have to add this later.
Happy path. See how relevant attributes are logged.
Mocked error coming from DB propagates error up the call stack.
=> `ListUsers`: add tracing

assets/tests/consolidated_1_1_tests.yaml, pkg/server/commands/listusers/list_users.go, pkg/server/commands/listusers/list_users_rpc.go, pkg/server/commands/listusers/list_users_rpc_test.go, pkg/server/list_users.go, pkg/server/list_users_test.go, pkg/server/server.go, tests/listusers/listusers.go
This PR introduces depth limit protection that will prevent the recursive algorithm from exceeding a configured limit. This configuration is set on the server with the `resolveNodeLimit` property. This check uses a decrementing counter on the request object, as is in Check, and will emit the `ErrResolutionDepthExceeded` error. The main ListUsers method on the server will detect for that specific error and will response with the `AuthorizationModelResolutionTooComplex` error.
Parent PR: #1428
=> fix: `ListUsers` recursive depth limit protection

pkg/server/server_test.go
Adding a ListUsers-focused test case to `TestReleasesConnections` (previously named `TestListObjectsReleasesConnections`). This test ensures that ListUsers is properly releasing DB connections after the API request completes.
Parent PR: #1428 
Related PR: #1061
=> test: Adding `ListUsers` case to TestReleasesConnections

pkg/server/commands/listusers/list_users_rpc.go, pkg/server/commands/listusers/list_users_rpc_test.go
There is a race condition in ListUsers caused by two goroutines in `expandExclusion` trying to write to the same object. In this PR I fix it and add tests for the other cases (union and intersection) just in case.
=> fix: `ListUsers` race conditions

internal/validation/validation.go, pkg/server/commands/list_objects_test.go, pkg/server/commands/reverseexpand/reverse_expand.go, pkg/server/commands/reverseexpand/reverse_expand_test.go
In ListObjects, when reading tuples, we should skip over all the invalid ones, and the definition of "invalid" can't just be "invalid condition".
With this model
```
model
schema 1.1
type user
type group
relations
define member: [user, group#member]
```
and these tuples
```
group:fga#member@user:maria
group:eng#member#member@group:fga#member // invalid
```
|                                                            | Before                              | After          |
|------------------------------------------------------------|-------------------------------------|----------------|
| ListObjects(type:group, relation:member, user: user:maria) | [ "group:fga", "group:eng#member" ] | ["group:fga" ] |
=> fix: stricter validation during ListObjects read of tuples

internal/graph/cached_resolver.go, internal/graph/cached_resolver_test.go
Detected this through local testing. Upon a server close, there may be in-flight Check requests still working.
```go
^C{"level":"info","ts":1713928093.823026,"msg":"Termination signal received! Gracefully shutting down","environment":"dev","region":"local","service_version":"latest"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x28 pc=0x105179a20]
goroutine 20624571 [running]:
github.com/karlseguin/ccache/v3.(*Cache[...]).bucket(0x15288d3b0b0, {0x152858ef698?, 0x12})
/Users/maria.inesparnisari/go-mod-cache/github.com/karlseguin/ccache/v3@v3.0.5/cache.go:211 +0x80
github.com/karlseguin/ccache/v3.(*Cache[...]).Get(0x106f7dcc0, {0x152858ef698, 0x12})
/Users/maria.inesparnisari/go-mod-cache/github.com/karlseguin/ …
```
=> fix: prevent panic on server close if caching is enabled

pkg/server/server_test.go, pkg/testutils/testutils.go, tests/check/check_test.go
This is an added safety measure to prevent goroutine leaks in code that is known to create goroutines.
=> chore: run goroutine leak detector on benchmarks

cmd/run/run.go, cmd/run/run_test.go, pkg/server/server.go
We previously deprecated `request_duration_by_query_count_ms` in favour of `request_duration_ms` ([Link](https://github.com/openfga/openfga/pull/1450)). We will be removing the deprecated metric in this PR.
https://github.com/openfga/openfga/pull/1450
=> Remove deprecated metric `request_duration_by_query_count_ms`

pkg/server/test/reverse_expand.go, pkg/storage/test/storage.go, pkg/tuple/tuple.go, pkg/tuple/tuple_test.go
Add some test helpers to bootstrap FGA store data (model and tuples) and encourage usage of tuple strings instead of having touse `tuple.NewTupleKey` everywhere.
=> chore: add test helpers to bootstrap FGA stores and tuple strings

internal/server/config/config.go, internal/server/config/config_test.go
This PR ensures that the ListUsers deadline is not lager than the configured request timeout.
=> fix: ListUsers config related to deadline settings

go.mod, internal/graph/check.go, pkg/server/commands/list_objects.go, pkg/server/commands/reverseexpand/reverse_expand.go
in the latest versions of Go, specifically from Go 1.19 onwards, we can use the errors.Join function, which was added to the standard library. This function can replace all of the functionality of the 3rd party [hashicorp/go-multierror](https://github.com/openfga/openfga/issues/github.com/hashicorp/go-multierror) package.
Closes https://github.com/openfga/openfga/issues/1556
=> refactor: replace hashicorp/go-multierror with errors.Join

Makefile
gomock is included in go coverage resulting in 71.43% coverage.
make test did not exclude all gomock packages, this change now excludes all gomock packages.
[1398](https://github.com/openfga/openfga/issues/1398)
=> fix: Exclude mock_check_resolver from code coverage

internal/graph/cached_resolver.go, internal/graph/check.go, internal/graph/cycle_check_resolver.go, internal/graph/dispatch_throttling_check_resolver.go
Prefer trace attributes over spans to reduce number of spans created.
=> perf: reduce spans in check api

pkg/server/server.go, pkg/server/server_test.go
Cache dispatcher should be before dispatch throttling dispatcher
Comments from https://github.com/openfga/openfga/pull/1571
=> fix: update order of dispatchers

internal/condition/condition.go, internal/condition/condition_test.go, pkg/server/commands/listusers/list_users_rpc.go
Before:
```
go test ./pkg/server/commands/listusers -count=1000 -race -run "TestListUsersConditions/multiple_conditions_some_params_provided"
--- FAIL: TestListUsersConditions (0.01s)
--- FAIL: TestListUsersConditions/multiple_conditions_some_params_provided (0.00s)
list_users_rpc_test.go:2724: 
Error Trace:    /Users/maria.inesparnisari/GitHub/openfga/pkg/server/commands/listusers/list_users_rpc_test.go:2724
Error:          Not equal: 
expected: "failed to evaluate relationship condition: 'isEqualToTen' - context is missing parameters '[param2]'"
actual  : ""
Diff:
--- Expected
+++ Actual
@@ -1 +1 @@
-failed to evaluate relationship condition: 'isEqualToTen' - context is missing parameters '[param2]'
+ 
```
After:
```
[6/05/24 8:29:25] ~/GitHub/openfga …
```
=> fix: send error before results

.config-schema.json, cmd/run/run.go, internal/server/config/config.go
Noticed while writing https://github.com/openfga/openfga.dev/pull/735.
Before:
```
[6/05/24 10:58:14] ~/GitHub/openfga-main (main) $ ./dist/openfga run --help | grep datastore-max-cache
--datastore-max-cache-size int                             the maximum number of cache keys that the storage cache can store before evicting old keys (default 100000)
```
After:
```
[6/05/24 10:59:03] ~/GitHub/openfga (doc-model-cache) $ ./dist/openfga run --help | grep datastore-max-cache
--datastore-max-cache-size int                             the maximum number of authorization models that will be cached in memory (default 100000)
[6/05/24 10:59:07] ~/GitHub/openfga (doc-model-cache) $ 
```
=> docs: update flag docs

cmd/run/run.go, internal/server/config/config.go
- log all server settings (except sensitive) on start up
- a few minor changes in wording
Closes https://github.com/openfga/openfga/issues/1501
Before:
After:
=> feat: log all server settings (except sensitive) on start up

cmd/run/run.go, cmd/run/run_test.go
Noticed while working on https://github.com/openfga/openfga/pull/1609 that we're not closing properly the profiler and metrics servers on server shutdown.
=> fix: close metrics and profiler properly, if enabled, on server shutdown

cmd/run/run.go, cmd/run/run_test.go, internal/server/config/config.go, pkg/server/server.go, pkg/server/server_test.go
- Fix more goroutine leaks
-  introduced by tests themselves
- in-memory cache of models not being closed on server close
- After this PR, everyone using OpenFGA as a library and not as a server can benefit from the in-memory cache of models.
- When you use as a library , you don't call `openfga.Run()`, you call `openfga.NewServerWithOpts()`. The former creates the cache of models, the latter doesn't. In this PR, i move the cache creation to the latter.
---
This test demonstrates the cache leak
```go
func TestBuildServiceWithPresharedKeyAuthenticationFailsIfZeroKeys(t *testing.T) {
t.Cleanup(func() {
goleak.VerifyNone(t)
})
cfg := testutils.MustDefaultConfigWithRandomPorts()
cfg.Authn.Method = "preshared"
cfg.Authn.AuthnPresharedKeyConfig = &serverconfig.AuthnPresharedKeyConfig{}
err := …
```
=> fix: close cache on server close

.github/workflows/release.yaml
The SLSA verification stage failed during [release of v1.5.4](https://github.com/openfga/openfga/actions/runs/9293326320/job/25607867536). The error message stated 
```
Verifying artifact *.tar.gz.sbom: FAILED: open *.tar.gz.sbom: no such file or directory
FAILED: SLSA verification failed: open *.tar.gz.sbom: no such file or directory
```
This happened because of a [recent goreleaser change](https://github.com/goreleaser/goreleaser/pull/4781) that added the `.json` fix extension to SBOM files by default. The solution here is to simply add the `.json` file extension to match the output of goreleaser.
**Testing:**
Not tested in CI but this was verified locally by running:
```sh
gh release download v1.5.4 \
--repo openfga/openfga \
-p "openfga.intoto.jsonl" -p "*.tar.gz" -p …
```
=> fix: slsa-verify stage during release by adding json file extension

.github/workflows/pull_request.yaml
Enables CI for the `stronger-consistency-options` branch on PRs. Should enable #1655 CI to run.
=> chore: enable CI on stronger-consistency-options branch

cmd/validatemodels/validate_models.go, pkg/storage/memory/memory.go, pkg/storage/mysql/mysql_test.go, pkg/storage/postgres/postgres_test.go, pkg/storage/storage.go, pkg/storage/test/authz_models.go, pkg/storage/test/stores.go, pkg/storage/test/tuples.go
page size of 0 is not valid. Thus, tests should never run with this option.
API validation - https://github.com/openfga/api/blob/394820dfc109972eb6366118718e212fc87412e3/openfga/v1/openfga_service.proto#L1381
Closes https://github.com/openfga/openfga/issues/1661
=> fix(test): test should not run with pageSize = 0

pkg/storage/test/tuples.go
For storage adapters:`Read`, `ReadChanges` and `ReadPage` should always return tuples with the timestamp that they were written.
=> test: add tests that assert on timestamp

go.mod
Updates go version to 1.22.4. This fixes [GO-2024-2887](https://pkg.go.dev/vuln/GO-2024-2887)
* https://pkg.go.dev/vuln/GO-2024-2887
* https://github.com/openfga/openfga/actions/runs/9394424353/job/25873691520?pr=1655
=> chore: update go version from 1.22.3 to 1.22.4

pkg/storage/memory/memory.go, pkg/storage/test/tuples.go
Fix regression introduced in https://github.com/openfga/openfga/pull/1660/files#diff-76e1d9c2639fc6c407f987f2698d74723cbe632c79cb31a5e0c1140dd33783b7
The memory storage adapter's `Read` method is supposed to return everything in the store, so it cannot use a `paginationOptions` object.
=> fix: Read in memory adapter

.github/workflows/pull_request.yaml
It's not uncommon for the maintainer team to build up larger bodies of work in a `feat/` branch before merging into `main`. Today we don't run the PR CI workflow for any PRs that are not targeting `main`. This changes that so that we always run our PR workflow for any PR.
=> ci(pull-requests): run PR workflow on all PRs

.config-schema.json, cmd/run/run.go, pkg/server/server.go
Adds the experimental flag `enable-consistency-params`, which will be used to enable the configuration of read consistency behavior.
Note that this PR targets the `stronger-consistency-options` branch, which we will work on as we implement this feature.
=> chore: add enable-consistency-params experimental flag

.github/workflows/release.yaml
Fix issue during releases uploading snyk.sarif to Github Code Scanning.
Regarding "undefined" output in SARIF, from https://github.com/github/codeql-action/issues/2187#issuecomment-2043220400:
> This behavior is expected - licenses and vulnerabilities were originally designed with a common structure but license-related findings are now managed differently. That is, license-related findings do not indicate a security vulnerability and are labeled as 'undefined'. 
https://github.com/github/codeql-action/issues/2187
https://github.com/openfga/openfga/actions/runs/9568501868/job/26379120370
=> ci: fix uploading synk results to github

pkg/server/commands/listusers/list_users.go, pkg/server/server.go
Passes the consistency parameter for Read, List Users, and Expand
Even though no cache is used in OpenFGA for Read, List Users, or Expand, we should pass through the request parameters.
=> chore: pass through consistency params

pkg/server/list_users.go, pkg/server/list_users_test.go, pkg/server/server.go, pkg/server/server_test.go
Raises an error when the `consistency` parameter is `HIGHER_CONSISTENCY` but the `enable-consistency-params` experimental flag is not set.
If a request is made that requests higher consistency (`consistency: HIGHER_CONSISTENCY`), but the `enable-consistency-params` is not enabled, raise an `InvalidArgument` error.
Impacts the following endpoints:
* Check
* Read
* ListObjects
* StreamedListObjects
* Expand
* ListUsers
Note that because the API will always send the default value of the consistency enum (`UNSPECIFIED`), we are only raising an error if the caller has specifically requested `HIGHER_CONSISTENCY` without the flag enabled.
=> feat: throw error when higher consistency requested but flag not enabled

pkg/typesystem/typesystem.go, pkg/typesystem/typesystem_test.go
If TTU and its child relations are directly assignable, then we can short circuit check evaluation.
=> feat: typesystem to evaluate TTU are exclusively directly assignable

pkg/server/list_users.go, pkg/server/server.go
Adds the requested consistency to the `request_duration_ms` histogram and spans of check, list objects, and streamed list objects. Currently this will report 3 possible values, `UNSPECIFIED`, `MINIMIZE_LATENCY`, `HIGHER_CONSISTENCY`, the intent here is that because a consistency of `HIGHER_CONSISTENCY` implies skipping the caching methods used within these queries, then the by being able to restrict searches based on the consistency type we can greater understand the impacts of skipping the cache.
Some examples of the data being shown below
=> feat: add telemetry data to view consistency type for request

pkg/typesystem/typesystem_test.go
Adding test to verify that we will not short circuit in the case of userset referencing itself
=> test: add case to cover recursion

cmd/validatemodels/validate_models.go, internal/mocks/mock_slow_storage.go, internal/mocks/mock_storage.go, pkg/server/commands/list_stores.go, pkg/server/commands/read.go, pkg/server/commands/read_authzmodels.go, pkg/server/commands/read_changes.go, pkg/server/commands/read_changes_test.go, pkg/server/commands/read_test.go, pkg/storage/memory/memory.go, pkg/storage/mysql/mysql.go, pkg/storage/mysql/mysql_test.go, pkg/storage/postgres/postgres.go, pkg/storage/postgres/postgres_test.go, pkg/storage/storage.go, pkg/storage/storagewrappers/combinedtuplereader.go, pkg/storage/storagewrappers/context.go, pkg/storage/test/authz_models.go, pkg/storage/test/stores.go, pkg/storage/test/tuples.go
For every storage method that takes a `PaginationOptions`, replace with method-specific options.
As discussed in #1716, as we add the ability to specify a consistency preference, we want to avoid adding another parameter to the methods that will require it. To make the storage API more resilient to additional future changes, we should instead specify an options type.
This PR adds the method-specific options, but **does not** introduce any consistency-related changes. The intent is that this PR maintain current functional behavior, while enabling us to add the consistency changes in a later PR.
The following options types have been added in this PR:
* `ReadAuthorizationModelsOptions`
* `ListStoresOptions`
* `ReadChangesOptions`
* `ReadPageOptions`
The related methods have been updated to …
=> feat(storage)!: use method-specific options

internal/graph/check.go, internal/mocks/mock_slow_storage.go, internal/mocks/mock_storage.go, pkg/server/commands/expand.go, pkg/server/commands/list_objects.go, pkg/server/commands/listusers/list_users_rpc.go, pkg/server/commands/listusers/list_users_rpc_test.go, pkg/server/commands/reverseexpand/reverse_expand.go, pkg/server/commands/reverseexpand/reverse_expand_test.go, pkg/server/list_users_test.go, pkg/server/server_test.go, pkg/server/test/reverse_expand.go, pkg/storage/memory/memory.go, pkg/storage/mysql/mysql.go, pkg/storage/mysql/mysql_test.go, pkg/storage/postgres/postgres.go, pkg/storage/postgres/postgres_test.go, pkg/storage/storage.go, pkg/storage/storagewrappers/boundedconcurrency.go, pkg/storage/storagewrappers/boundedconcurrency_test.go, pkg/storage/storagewrappers/combinedtuplereader.go, pkg/storage/storagewrappers/context.go, pkg/storage/test/tuples.go
Adds the consistency parameter to storage methods.
Adds a new `ConsistencyOptions` type:
```go
type ConsistencyOptions struct {
Preference openfgav1.ConsistencyPreference
}
```
The following methods have been updated to take new options to support consistency:
- `Read`
- `ReadPage`
- `ReadUsersetTuples`
- `ReadStartingWithUser`
=> feat(storage): add consistency parameter

assets/tests/consolidated_1_1_tests.yaml, internal/graph/check.go, pkg/typesystem/typesystem.go, pkg/typesystem/typesystem_test.go
Improvement in check latency where userset's and TTU's children are publicly wildcard assignable.
=> perf: check improvement in case userset and TTU wildcard

internal/graph/cached_resolver.go, internal/graph/cached_resolver_test.go, pkg/server/commands/list_objects_test.go
This PR introduces writing to the cache in `CachedCheckResolver` even when we are not reading from it due to the consistency requested being `HIGHER_CONSISTENCY`. Previously when we implemented skipping the cache we chose to not update the cache, but as it is relatively simple to do so we are now choosing to enrich the cache.
It refactors the existing test for this behaviour to now require the cache to be updated, and updates the list objects test that relied on cache interaction to reflect the new reality.
=> feat: update cached resolver cache when not reading from the cache

go.mod, go.sum, internal/graph/check.go, pkg/storage/memory/memory.go, pkg/storage/mysql/mysql.go, pkg/storage/postgres/postgres.go, pkg/storage/sortedset.go, pkg/storage/sortedset_test.go, pkg/storage/storage.go, pkg/storage/test/tuples.go
Follow-up to https://github.com/openfga/openfga/pull/1734 and https://github.com/openfga/openfga/pull/1735.
This PR is a breaking change to the interface `ReadStartingWIthUser`. Now, the `objectIDs` parameter will be given as a **sorted** list so that datastore implementations don't have to sort it.
=> perf(check): use a sorted set to store usersets

cmd/run/run.go, internal/mocks/mock_tracing_server.go, tests/check/check_test.go
Experimenting with some changes to fix
```
--- FAIL: TestServerLogs (0.09s)
tests.go:62: creating connection to address 0.0.0.0:39189
--- FAIL: TestServerLogs/streamed_list_objects_success (0.00s)
check_test.go:268: 
Error Trace:	/home/runner/work/openfga/openfga/tests/check/check_test.go:268
Error:      	"[]" should have 1 item(s), but has 0
Test:       	TestServerLogs/streamed_list_objects_success
```
```
$ go test ./tests/check -race -run="TestServerLogs" -count=100
ok      github.com/openfga/openfga/tests/check  59.203s
```
=> test: fix flakiness in TestServerLogs

assets/tests/consolidated_1_1_tests.yaml, internal/graph/cached_resolver_test.go, internal/graph/check.go, pkg/typesystem/connected_types.go, pkg/typesystem/connected_types_test.go, pkg/typesystem/typesystem.go, pkg/typesystem/typesystem_test.go
Determining the ultimate terminal types and terminal relations for a given object type and relation. This data is calculated at the time of typesystem creation and validations (`t.NewAndValidate()`) and associated in a multi-key map on the typesystem struct.
This work enables two different optimizations. The primary is an optimized TTU and userset lookup which requires knowledge of the terminal types and relations for a given userset to craft the appropriate query. Currently, this is limited to usersets that result in a direct relation and necessarily doesn't result in a computed relation, union, intersection, etc. This limitation can be observed in #1733. 
This PR _only_ supports TTU that result in direct relations, computed relations and public wildcards. It does not yet support the …
=> refactor: Using typesystem to determine when to apply TTU fast path 

Dockerfile
- Upgrade to latest version of go 1.22 as the current version (1.21) has a CVE, and the go version used in the project is go 1.22.5: https://github.com/openfga/openfga/blob/main/go.mod#L3
```
grype openfga/openfga
✔ Vulnerability DB                [updated]
✔ Pulled image
✔ Loaded image                                                                                                                                                                               openfga/openfga:latest
✔ Parsed image                                                                                                                              sha256:94bccb263cedd9b13ad754bf78ca4350e7edcfaea85d65551141e7f7de30c61c
✔ Cataloged contents …
```
=> chore: upgrade go1.22 in docker

cmd/run/run.go
Fixes a potential data race that can occur if `cfg.Metrics.Enabled = true` and the server stops too fast. `metricsServer` variable may be in progress of being written, and on server close we do `if metricsServer != nil` (read), we have a race.
```
2024-07-24T08:50:43.927-0700    INFO    attempting to shutdown gracefully...
2024-07-24T08:50:43.927-0700    INFO    HTTP server shut down.
==================
WARNING: DATA RACE
Read at 0x00c0009ae178 by goroutine 1512:
github.com/openfga/openfga/cmd/run.(*ServerContext).Run()
/Users/maria.inesparnisari/GitHub/openfga-main/cmd/run/run.go:835 +0x6ec4
github.com/openfga/openfga/cmd/run.runServer()
/Users/maria.inesparnisari/GitHub/openfga-main/cmd/run/run_test.go:186 +0x104
github.com/openfga/openfga/cmd/run.testServerMetricsReporting.func2() …
```
=> fix: data race on server close

tests/check/check_test.go
The TestServerLogs/streamed_list_objects_success test is flakey. This PR changes the test to read the entire streaming HTTP response before closing the body and attempting to read the logs.
The suspected cause of this issue: Currently, the test does not read the response body data for HTTP requests, and instead closes the body immediately after the client returns. This causes the client to close and discard the TCP connection immediately and move on. The `StreamedListObjects` sends response objects concurrently, and will attempt to send all objects, regardless of the state of the connection. This creates a race condition between the server sending all of the response objects before emitting the log, and the test attempting to read the logs. Hence the flakiness of this test.
To fix the …
=> fix: flakey test

.goreleaser.yaml
tries to fix the following:
```
⨯ release failed after 5m6s                error=docker manifests: failed to publish artifacts: failed to push ***/***:latest: exit status 1: cannot use source images from a different registry than the target image: ghcr.io != docker.io
```
https://github.com/openfga/openfga/actions/runs/10115398660/job/27977786555
=> fix: goreleaser docker manifests

cmd/run/run.go
`make test` now reacts to Ctrl+C quicker. Previously, if you sent Ctrl+C before the line `signal.Notify(done, syscall.SIGINT, syscall.SIGTERM)` executed, it was possible for the program to never stop.
- https://pkg.go.dev/os/signal#example-NotifyContext
- https://miparnisariblog.wordpress.com/2024/07/30/handling-program-interruptions-gracefully-in-go/
=> fix: server responds to cancellation signal quicker

internal/graph/check.go
=> fix: proper nesting of spans in Check API if computed usersets

go.mod, go.sum, pkg/server/commands/write_assertions.go, pkg/server/test/server.go, pkg/server/test/write_assertions.go
Supersedes https://github.com/openfga/openfga/pull/1635. Also:
- Re-worked unit tests so that they are shorter
- Fixed validation performed on contextual tuples
- Add tests with contextual tuples that have contexts
- Closes https://github.com/openfga/openfga/issues/946
- Depends on API changes https://github.com/openfga/api/pull/185
- Supersedes https://github.com/openfga/openfga/pull/1635
=> feat: Support Contextual Tuples in Assertions API

internal/mocks/mock_error_iterator.go, pkg/storage/iterators.go, pkg/storage/iterators_test.go, pkg/storage/memory/memory.go, pkg/storage/memory/memory_test.go, pkg/storage/mysql/mysql_test.go, pkg/storage/postgres/postgres_test.go, pkg/storage/sqlcommon/sqlcommon.go
Iterator function Head to look at the first item without advancing iterator.
Note: custom datastore implementation will need to be updated to support Head()
This is needed in preparation for check latency optimization for TTU & userset where the child is an intersection/union/exclusion.
=> chore!: add Head for iterator

pkg/typesystem/typesystem.go, pkg/typesystem/typesystem_test.go
This PR exists to showcase an example of refactoring to increase test comprehensiveness.
`TypeSystem::IsDirectlyRelated` is refactored by pulling out the function `RelationEquals`. By doing so, it is easier to more comprehensively test the logic for comparing two `RelationReference` instances.
=> chore: refactor TypeSystem::IsDirectlyRelated for more fine-grained testing.

Dockerfile
dcoker-test posts warning about mismatch case
Warning message in other PRs (for example - https://github.com/openfga/openfga/pull/1850/files)
=> fix: correct docker file syntax

.github/ISSUE_TEMPLATE/report_a_bug.yml
- Mention not to use the "report a bug" flow to report security vulnerabilities
- Condense the bug report template. There are too many fields to fill out and I think a more free-form report will be less daunting on users.
Current report:
=> chore: update bug report template

internal/graph/track_check_resolver.go
The consistency parameter is getting dropped when enabling the TrackerCheckResolver, add it to the `ResolveCheckRequest` being constructed so that it's passed through and can be used.
I'm not sure whether we can potentially move to something similar to `CloneResolveCheckResponse` so that we only need to update once place to ensure that properties get carried across?
=> fix: set consistency when calling ResolveCheck from TrackerCheckResolver

tests/check/check.go, tests/check/complexity_three.go
Continuation of adding integration test (tackling complexity 3).  Only cycle_nested are missing.
=> tests: integration test of complexity 3

pkg/typesystem/typesystem.go, pkg/typesystem/typesystem_test.go
refactor `tupleToUsersetsDefinitions` to `flattenUserset` and add tests.
adds a comprehensive set of tests for function
=> chore: refactor typesystem function that flattens a userset, and add tests

internal/graph/check.go, internal/graph/check_test.go
Adding unit test for buildCheckAssociatedObjects.  This will serve as building block to test consumeUsersets for graph/check.  In addition, update buildCheckAssociatedObjects so that it is not a method for the local checker
=> test: add tests for CheckAssociatedObjects

tests/check/check.go, tests/check/check_userset.go
Adds tests to cover the userset cases
Covers all relations except for `tuple_cycle2`, `tuple_cycle2`, and I know for sure I'm missing some cases in `nested_and_userset` I just haven't figured out all the paths yet
=> test: add tests for Check (usersets)

pkg/server/commands/listusers/list_users_rpc.go, pkg/server/commands/listusers/list_users_rpc_test.go
I am making the EvaluationError emitted by ListUsers the same as the one emitted in Check and ListObjects:
https://github.com/openfga/openfga/blob/47fb83bc711008fbd3d76cfe30cf07348ba9658f/internal/graph/check.go#L852-L857
https://github.com/openfga/openfga/blob/47fb83bc711008fbd3d76cfe30cf07348ba9658f/pkg/server/commands/reverseexpand/reverse_expand.go#L537-L542
ideally we wouldn't have to craft this error by hand in every API, but... baby steps
=> chore: standardize text of 'missing context' error in ListUsers

tests/check/check_userset.go
Adds tests that cover the `tuple_cycle2` and `tuple_cycle3` relations in usersets, verified the cycle cases by logging in the cycle detection logic.
=> test: add usersets tuple_cycle2 and tuple_cycle3 tests

.github/workflows/enforce-changelog-entry.yaml
This is flagged on the [OpenSSF scorecard](https://securityscorecards.dev/viewer/?uri=github.com/openfga/openfga) so we need to explicitly state the permissions.
https://securityscorecards.dev/viewer/?uri=github.com/openfga/openfga
See [run 1](https://github.com/openfga/openfga/actions/runs/10664490408/job/29555851673?pr=1899) and [run 2](https://github.com/openfga/openfga/actions/runs/10664498537/job/29555875702?pr=1899) of the job to ensure it still works with these permissions
=> ci: add permissions block to changelog enforcement

CHANGELOG.md, pkg/server/server.go
Adding stats on number of allowed vs. non-allowed response in check.
=> feat: add stats on number of allowed response in check

pkg/storage/iterators.go, pkg/storage/iterators_test.go
This pull request removes the unused `emptyTupleIterator` struct from `iterators.go` and the associated test case `TestEmptyIterator` from `iterators_test.go`. The struct was not being used and can be safely removed.
fixes #1823
=> refactor: remove unused `emptyTupleIterator

CHANGELOG.md, tests/check/check_test.go, tests/listobjects/listobjects_test.go
This PR extends the RequestTimeout to 10s for some of the tests. We run tests with code coverage enabled which can make them take longer than the default 3s timeout.
This appears to impact SQLite more than it does Postgres or MySQL, which may be due to the fact that the entirety of SQLite is pure go running in-process, vs just the client for the other databases.
=> Extend request timeout to 10s for slow tests

CHANGELOG.md, cmd/run/run.go
This pull request updates the signal handling in the `Run` function to include the `SIGTERM` signal in addition to `SIGINT` and `SIGKILL`. This ensures that the server can gracefully terminate when receiving a `SIGTERM` signal.
fixes #1910
=> fix: Update signal handling in Run function

tests/listusers/listusers_test.go
applies the same timeout extensions as #1926  to the list user tests
=> extend list users test timeout

internal/graph/check.go
Allow better association of ds store query with the correpsonding check
=> chore: add trace for consumeUsersets and produceUsersets

internal/authz/authz.go, pkg/server/server.go
Add Noop Authorizer so that we don't have to check if authorizer is set.
NoopAuthorizer and Authorizer meet the spec of AuthorizerInterface, allowing for either to be set on initial load.
https://github.com/openfga/openfga/pull/1914#discussion_r1761865960
https://github.com/openfga/openfga/pull/1913
=> feat: create noop authorizer that meets the interface of Authorizer

CHANGELOG.md
I noticed that a number of headings in the changelog were not at the correct level, this PR updates them so that release subheadings are all 3rd-level
=> chore: fix changelog headings

cmd/run/run.go, pkg/server/server.go, pkg/server/server_test.go
Access Control requires OIDC to be set as Authn method.
Add a check to see whether OIDC was set as Authn method, throw error if it is not set but access control is enabled.
(https://github.com/openfga/openfga/pull/1913)
=> fix: add check for oidc set as authn method

README.md
Unify shell run blocks in [README.md]
Small change only to unify shell run blocks in [README.md] file
=> chore: Unify shell run blocks in README.md

CHANGELOG.md, internal/graph/check.go, pkg/server/commands/listusers/list_users_rpc.go, pkg/server/server.go, pkg/typesystem/resolver.go
When trying to find patterns in Check requests via tracing information, i want to be able to find all top-level "Check" spans and gather all the information from there, and not have to manually dig into children spans.
I'm also improving attribute information for the model ID resolution which is a bit hard to find right now.
`docker-compose up --build`
After this PR:
=> feat: minor improvements in tracing of Check API

tests/check/check_test.go
Experimental flags related to this were already removed so no need to run the same tests twice
https://github.com/openfga/openfga/pull/1895
=> chore: run matrix memory tests once

pkg/storage/cache.go, pkg/storage/cache_test.go
Previous to this calling `.Close()` more than once would result in a goroutine leak.
Previously identified and fixed in https://github.com/openfga/openfga/pull/1924
=> fix: close cache once

internal/graph/check.go, internal/validation/validation.go, internal/validation/validation_test.go, pkg/server/commands/check_command.go, pkg/server/commands/list_objects.go, pkg/server/commands/listusers/validate.go, pkg/server/commands/reverseexpand/reverse_expand_test.go, pkg/server/commands/write.go, pkg/server/commands/write_assertions.go, pkg/tuple/tuple.go
Validations when reading from the datastore do not have to be the same ones as when we write to the datastore. Thus paying the penalty on each tuple read, is unnecessary. 
Additionally, some validations where being done explicitly and then implicitly under more complex types again, this PR aims to reduce the duplication also to improve overall validation.
Before:
```
BenchmarkValidateTuple
BenchmarkValidateTuple-16    	 1000000	      1167 ns/op
```
After:
```
BenchmarkValidateTupleForWrite
BenchmarkValidateTupleForWrite-16    	 1201627	       986.8 ns/op
BenchmarkValidateTupleForRead
BenchmarkValidateTupleForRead-16    	 3549020	       331.4 ns/op
```
=> fix: faster tuple validation when reading from datastore

CHANGELOG.md, pkg/storage/mysql/mysql_test.go, pkg/storage/postgres/postgres_test.go, pkg/storage/sqlcommon/sqlcommon.go
I introduced a regression in https://github.com/openfga/openfga/commit/540b94c56a5c74113930854ea4a690bc998f0054 wherein if the latest auth model written is split across rows (it should never happen in real life because this is the old format), FindLatestModel doesn't return the right data.
I detected this regression by looking at [code coverage](https://app.codecov.io/gh/openfga/openfga/blob/main/pkg%2Fstorage%2Fsqlcommon%2Fsqlcommon.go) when I was reviewing https://github.com/openfga/openfga/pull/1983. I thought: "why didn't I make coverage better when I merged https://github.com/openfga/openfga/commit/540b94c56a5c74113930854ea4a690bc998f0054 if I wrote a test specifically for that?"
=> fix: amend #1980

pkg/storage/mysql/mysql_test.go, pkg/storage/postgres/postgres_test.go
Added tests to check the return value of function constructAuthorizationModelFromSQLRows
Issue #1952
=> test: testing the return of func constructAuthorizationModelFromSQLRows

CONTRIBUTING.md
This PR fixes the link to the contribution guidelines and adds a _new line_ symbol at the end of the file.
=> fix: use proper link to contribution guidelines

pkg/server/server_test.go
Previous to this change this test would fail sometimes
```
go test -v -race -count 1000 -run '^TestCheckWithCachedIterator$' pkg/server/*.go
```
would usually fail like this:
```
=== RUN   TestCheckWithCachedIterator
--- FAIL: TestCheckWithCachedIterator (0.01s)
controller.go:243: missing call(s) to *mocks.MockOpenFGADatastore.ReadUsersetTuples(is anything, is equal to 01J9D47GKMG11MCH8VGP2T26ZS (string), is anything, is anything) /home/runner/work/openfga/openfga/pkg/server/server_test.go:2218
controller.go:243: aborting test due to missing call(s)
```
With this small change, I have not yet seen the flake.
https://github.com/openfga/openfga/pull/1924
=> fix: remove flakeyness from TestCheckWithCachedIterator

CHANGELOG.md, internal/graph/check.go, internal/graph/check_test.go, internal/graph/tuplemapper.go, internal/graph/tuplemapper_test.go
Extend https://github.com/openfga/openfga/pull/2004 to support the nested TTU scenario.
Part of https://github.com/openfga/openfga/issues/1945
With `OPENFGA_EXPERIMENTALS=enable-check-optimizations`
Test this model:
```
model
schema 1.1
type user
type group
relations
define parent: [group]
define member: [user] or member from parent
```
with:
```
STORE_ID=$(curl --silent --location 'localhost:8080/stores' \
--header 'Content-Type: application/json' \
--data '{"name":"pr2007"}' | jq .id --raw-output)
curl --silent --location "localhost:8080/stores/$STORE_ID/authorization-models" \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--data '{"schema_version":"1.1","type_definitions":[{"type":"user","relations":{},"metadata":null},{"type":"group","relations":{"pa …
```
=> perf: nested TTUs in Check

pkg/server/commands/check_command.go, pkg/server/commands/check_command_test.go, pkg/server/server.go, pkg/server/server_test.go, pkg/server/test/check.go
The upcoming BatchCheck work will be calling the CheckCommand, which currently requires its `.Execute` method to receive a `CheckRequest`. Passing the full request object isn't necessary; this PR pulls the required pieces of the `CheckRequest` into a struct and passes that struct into `.Execute` instead to increase reusability.
Creation of Check Command: https://github.com/openfga/openfga/pull/1857
=> refactor: check command execute params

pkg/server/commands/list_objects_test.go
This test fixes flakiness in List Objects dispatch throttling.
- This issue fixes the problem where we are trying LO on multiple objects, leading to flakiness. We will use a single LO and reduce the throttling value inside the check to achieve this. Ran the test with `-test.count 10000` to ensure flakiness is not reproducing.
https://github.com/openfga/openfga/actions/runs/11418224120/job/31773914192
=> fix(test): Fix flaky test in ListObjects dispatch throttling

CHANGELOG.md, go.mod, go.sum
This bumps the limit on contextual tuples from 20 to 100. See this PR for more https://github.com/openfga/api/pull/208
=> feat: bump api to increase max number of contextual tuples

cmd/run/run_test.go, internal/mocks/mock_oidc_server.go, internal/mocks/mock_tracing_server.go, pkg/testutils/testutils.go, tests/tests.go
Currently when starting HTTP/gRPC servers for testing we don't specify the host so the servers will be listen on all available network interfaces. This will most likely pop up a prompt for permission to do this (as it will expose ports on your machine), which can get irritating.
Instead, specifically listen on localhost which won't require permission. 
=> test: only listen on localhost to avoid prompting for permission

pkg/server/commands/check_command.go, pkg/server/commands/check_command_test.go, pkg/server/commands/errors.go, pkg/server/server.go, pkg/server/server_test.go
The CheckCommand was built with the assumption that we would be running only single checks in a request. As a result, the `check_command` itself is translating internal errors into external facing GRPC error types. For BatchCheck, we need error handling on a per-check basis (in addition to per-request).
This PR refactors the error handling in the `check_command` to make it completely agnostic to the transport layer. It just returns specific error types which the server (or BatchCheck) can transform as they need.
No logic was changed as part of this PR, it's a pure refactor.
Closely related to #2031 
=> refactor: consolidate check_command error handling

CHANGELOG.md, pkg/typesystem/typesystem.go, pkg/typesystem/typesystem_test.go, tests/check/check.go, tests/check/check_ttu.go, tests/check/check_userset.go
The current fastpath optimization for nested userset does not handle case 
Close https://github.com/openfga/openfga/issues/2048
=> fix: disable fastpath optimization for  nested userset with public wildcard

internal/graph/check.go
```
2024/10/28 19:36:35 [DEBUG] GET http://localhost:39425/healthz
==================
WARNING: DATA RACE
Read at 0x00c00286a244 by goroutine 6916:
github.com/openfga/openfga/internal/graph.(*LocalChecker).checkRewrite.(*LocalChecker).checkDirect.func2.1()
/home/runner/work/openfga/openfga/internal/graph/check.go:1373 +0x3fa
github.com/openfga/openfga/internal/graph.resolver.func1.2()
/home/runner/work/openfga/openfga/internal/graph/check.go:155 +0x69
Previous write at 0x00c00286a244 by goroutine 6909:
github.com/openfga/openfga/internal/graph.(*LocalChecker).nestedFastPath()
/home/runner/work/openfga/openfga/internal/graph/check.go:1278 +0x1b2a
github.com/openfga/openfga/internal/graph.(*LocalChecker).nestedTTUFastPath()
/home/runner/work/openfga/openfga/internal/graph/check.go:1286 …
```
=> fix: clone request to avoid data race

Dockerfile.goreleaser
Bump grpc health probe to v0.4.35
See https://github.com/openfga/openfga/pull/2051
=> chore: bump grpc health probe

internal/graph/check.go, internal/graph/check_test.go, pkg/typesystem/typesystem_test.go
Small refactor to move checkDirectUserTuple to its own function in preparation of optimizing nested userset with public wildcard assignable.
=> chore: move check directly assignable function out to its own function

internal/graph/cached_resolver_test.go, internal/graph/check.go, internal/graph/check_test.go, internal/graph/graph.go, internal/graph/resolve_check_request.go, internal/graph/resolve_check_response.go, internal/graph/resolve_check_response_test.go, pkg/server/commands/check_command.go, pkg/server/commands/check_command_test.go
Follow-up to https://github.com/openfga/openfga/pull/2022.
- I'm getting rid of a pointer reference in favor of a value(?) reference to simplify the code:
```go
type ResolveCheckResponse struct {
Allowed            bool
---	ResolutionMetadata *ResolveCheckResponseMetadata
+++ ResolutionMetadata ResolveCheckResponseMetadata
}
```
- I also moved some code around, namely `ResolveCheckRequestMetadata` and `ResolveCheckResponseMetadata`
=> refactor: resolve check response

CHANGELOG.md, go.mod, go.sum, pkg/server/commands/expand.go, pkg/server/commands/expand_test.go, pkg/server/server.go, pkg/server/test/expand.go
Adds contextual tuples support to Expand request.
#951 
1. [PR](https://github.com/openfga/api/pull/202) to add Contextual tuples to the request in openfga/api
2. [PR](https://github.com/openfga/api/pull/209) to add documentation for the same
=> feat: add contextual tuples to Expand API

CHANGELOG.md, internal/graph/check.go, internal/graph/check_test.go, pkg/server/server_test.go, pkg/typesystem/typesystem.go, pkg/typesystem/typesystem_test.go
Enabling performance optimization for nested userset that has public wildcard.  This requires moving the handling of public wildcard to separate checker.
Special note: This has slight degrade in benchmark performance for `benchmark_with_bypass_userset_read` as it now requires two calls to ReadUsersetTuples (1 for public wildcard and 1 for userset) instead of a single ReadUsersetTuples call (1 call combining public wildcard and userset).
=> perf: enable optimization for nested userset with public wildcard

CHANGELOG.md, internal/authz/authz.go, internal/authz/authz_test.go, pkg/server/server.go
Adding OTEL measurement on latency for root store check.  In addition, adding OTEL measurement on write latency (with and without authz)
=> feat: measurement on root store check + write latency due to authz

pkg/server/test/list_objects.go
Seen in https://github.com/openfga/openfga/actions/runs/11719328473/job/32642347221?pr=2076
```
BenchmarkOpenFGAServer/BenchmarkMySQLDatastore/BenchmarkListObjects/oneResult                             	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12756ba]
goroutine 12452829 [running]:
github.com/openfga/openfga/pkg/server/test.BenchmarkListObjects.func1(0xc000162a08)
/home/runner/work/openfga/openfga/pkg/server/test/list_objects.go:674 +0x13a
testing.(*B).runN(0xc000162a08, 0xd1b)
/opt/hostedtoolcache/go/1.22.7/x64/src/testing/benchmark.go:193 +0xf8
testing.(*B).launch(0xc000162a08)
/opt/hostedtoolcache/go/1.22.7/x64/src/testing/benchmark.go:316 +0x1b1
created by testing.(*B).doBench in goroutine …
```
=> test: fix nil pointer in benchmarks

pkg/server/commands/expand_test.go
The new Expand tests have a race condition built into them. I've seen it in CI and if you run `go clean -testcache && go test -v ./pkg/server/... -run TestExpand` enough times you will see the following:
The code is working properly but the assertion is order-dependent so depending on which comes back first the test sometimes fails. It's an artifact of using `require.Equal` on a deeply nested expectation which contains a slice.
This PR changes the Expand test from table-driven to individual test assertions to allow for more granular assertion targeting. E.g. now it uses `require.ElementsMatch` on the specific leaf node, instead of trying to `require.Equal` on a big object which contains a slice.
#2045 
If you haven't done so yet, we would appreciate it if you could star the [OpenFGA …
=> test: fix order-dependent assertion in expand test

pkg/encoder/token_serializer.go, pkg/server/commands/read.go, pkg/server/commands/read_changes.go, pkg/server/commands/read_changes_test.go, pkg/server/commands/read_test.go, pkg/storage/sqlcommon/sqlcommon.go, tests/functional_test.go
Due to a non-empty `continuation_token` returned by the API which internally contains an emtpy `ulid` - pagination for `read` would go into an infinite loop.
This PR checks for `ulid` length before serializing it into a token and never again returns a continuation token with empty contents.
On top of that - extra validation added to the serializer checking the length of the input `ulid` and throwing an error in cases its empty.
=> don't generate continuation token for empty result

CHANGELOG.md, pkg/server/commands/expand_test.go, pkg/server/commands/listusers/list_users_rpc_test.go, pkg/server/commands/read.go, pkg/server/commands/read_test.go, pkg/server/commands/reverseexpand/reverse_expand.go, pkg/server/commands/reverseexpand/reverse_expand_test.go
The `/read` and `/list-objects` endpoints were dropping the received `consistency` preference during evaluation. This PR passes it through.
This PR also adds assertions for `/expand` and `/list-users`. They were handling consistency correctly but didn't have test coverage for it.
=> fix: respect consistency preference in `read` and `listObjects`

CHANGELOG.md, internal/authz/authz.go, internal/authz/authz_test.go, pkg/server/server.go
Add GRPC tags to be able to detect when calls go through authz.
=> feat: add a field in log entries when authz calls were made

CHANGELOG.md, pkg/server/server.go, pkg/server/server_authz_test.go
For any access control error we want to return unauthorized, but we do want to log the corresponding error for users to debug.
=> fix: always return ErrUnauthorizedResponse for access control failures, but log the corresponding error

internal/graph/check.go, internal/graph/check_fast_path.go
In the case the client/upstream cancels the context, it should yield an error rather than a `false` resolution.
=> fix: prevent race condition of context cancellation

CHANGELOG.md, internal/graph/storagewrapper.go, internal/graph/storagewrapper_test.go, pkg/server/batch_check.go, pkg/server/check.go, pkg/server/commands/batch_check_command.go, pkg/server/commands/check_command.go, pkg/server/commands/check_command_test.go, pkg/server/server.go, pkg/storage/storagewrappers/request.go, pkg/storage/storagewrappers/request_test.go
Use a wait group per instance of a `CachedDatastore` to help synchronize any cached iterator goroutines still in flight during when server is shutting down. This should eliminate potential data races by allowing us to close the inmem cache instance once we're sure there's no further access to it.
```
==================
WARNING: DATA RACE
Read at 0x00c0008085a0 by goroutine 85819:
github.com/Yiling-J/theine-go/internal.(*Shard[go.shape.string,go.shape.interface {}]).get()
/home/runner/go/pkg/mod/github.com/!yiling-!j/theine-go@v0.6.0/internal/store.go:80 +0xd8
github.com/Yiling-J/theine-go/internal.(*Store[go.shape.string,go.shape.interface {}]).getFromShard()
/home/runner/go/pkg/mod/github.com/!yiling-!j/theine-go@v0.6.0/internal/store.go:212 +0x8b …
```
=> fix: wait for cached iters on close

.config-schema.json, cmd/run/run.go, cmd/run/run_test.go, internal/server/config/config.go, internal/server/config/config_test.go
Expose cache controller configurations as environment variables to allow configuration when running as a standalone binary.
Close https://github.com/openfga/openfga/issues/2148
=> chore: expose cache controller configuration to allow use as stand alone binary

CHANGELOG.md, internal/graph/check_fast_path.go, internal/graph/check_fast_path_test.go
Bug fix where incorrect check result is returned where system is configured with experimental flag `enable-check-optimizations` and model has intersection or exclusion.
=> fix: fastpath v2 tuples not iterated correctly for intersection and exclusion

pkg/storage/memory/memory.go, pkg/storage/mysql/mysql.go, pkg/storage/postgres/postgres.go, pkg/storage/sqlite/sqlite.go, pkg/storage/storage.go, pkg/storage/test/tuples.go
The optimized check function checkUsersetFastPathV2 expects ReadStartingWithUser to be sorted by object IDs.  Update various datastore ReadStartingWithUser to reflect this.
=> fix: enforce order by object id for ReadStartingWithUser

CHANGELOG.md, pkg/storage/cache.go
This is a low-hanging performance optimization I stumbled across while doing work on #2160.
=> perf: use `strings.builder` when generating check cache key

internal/checkutil/checkutil.go, internal/graph/check_fast_path.go
In preparation of improving performance by allowing public wildcard for v2 fastpath, refactor so that both TTU and userset shared construction of left channels.
=> chore: refactor check fastpath v2 left channels

pkg/testutils/testutils.go, tests/check/check.go, tests/listobjects/listobjects.go, tests/listusers/listusers.go
- shuffle order of tuples when writing them, and shuffle ctx tuples
- update maximum allowed number of contextual tuples per request.
Motivation:
- Prevent bugs related to the code assuming that the input tuples have the "right" order.
- https://github.com/openfga/openfga/pull/2150
=> test: shuffle order of tuples when writing them, and shuffle ctx tuples

pkg/storage/iterators.go, pkg/storage/iterators_test.go
While working on https://github.com/openfga/openfga/pull/2150 I looked at our existing iterators and found a couple of minor issues:
- there is no locking of the mutex before checking `len(c.pending)`, fixed it
- made `StaticIterator` thread safe
=> refactor: iterators

go.mod, go.sum
Address CVE-2024-45338
https://nvd.nist.gov/vuln/detail/CVE-2024-45338
=> chore: bump x/net version to v0.33.0

internal/keys/hasher.go, internal/keys/hasher_test.go, pkg/storage/cache.go, pkg/tuple/tuple.go, pkg/tuple/tuple_test.go
- move logic out of structs and into functions
- accept an io.StringWriter instead of using separate string builders
- allow the hasher to build the string and eliminate need for other builders
- add sorting logic to TupleKeys type
Unit tests can easily be added for each of the new functions, but I'm not sure what all of the cases around contexts and conditions would look like.
=> rework cache key hash generation

pkg/storage/iterators.go, pkg/storage/iterators_test.go
Add an iterator that is similar to [CombinedIterator](https://github.com/openfga/openfga/blob/9ec0ab1d01dec37dd540638f9429b7e851099520/pkg/storage/iterators.go#L34-L36) but with the restriction that the inner iterators must be sorted already in ascending fashion. This enables an implementation of [merging of K sorted lists](https://leetcode.com/problems/merge-k-sorted-lists/)
Ripped from https://github.com/openfga/openfga/pull/2150
=> chore: introduce new ordered combined iterator

internal/keys/hasher.go, internal/keys/hasher_test.go, pkg/tuple/tuple.go, pkg/tuple/tuple_test.go
Additional tests have been included for the recently introduced hasher `Write*` functions in the `keys` package.
Many of these new tests will error on the first call to `WriteString` in the unit under test. There are other locations in the code that could error on a call to `WriteString`, but are more challenging to reach due to the prior call to `WriteString` having already returned an error.
-- Edit:
I've altered some test helpers to allow deeper error cases to be covered.
Also, comments have been added to the new functions and text helpers.
=> test: add error test cases to the hasher Write* functions in the keys package

internal/keys/hasher.go
In function `hasher.WriteTuples`, instead of mutating the input slice of tuples, copy the input slice.
The intent or responsibility of this function is not to sort the input slice and it is a side-effect that is observable outside of the function that really shouldn't exist.
For performance reasons, I could argue that the caller should pass a copy of the slice when necessary. However, I see the mutation side-effect as surprising in a negative way.
=> avoid mutating reference input

pkg/storage/cache.go, pkg/storage/cache_test.go
replace simple uses of `fmt.Sprintf` with the concatenation operator `+`.
=> chore: replace sprintf in cache code

pkg/server/test/check.go, pkg/server/test/list_objects.go, pkg/server/test/list_users.go, pkg/storage/test/storage.go
This PR is a continuation of https://github.com/openfga/openfga/pull/2175. Adding randomness so that we can expose bugs caused by code that incorrectly relies on a particular order of tuples.
=> test: shuffle order of tuples when writing them

internal/graph/check_fast_path.go, internal/graph/check_fast_path_test.go, internal/graph/check_test.go
This PR is meant to have unit tests of Check API mimic production code as much as possible. 
In production code, we are calling `NewRequestStorageWrapperForCheckAPI` on every Check API call: https://github.com/openfga/openfga/blob/f00569d20166aab9810ea1b6566cd0968abb4ecd/pkg/server/commands/check_command.go#L115-L118
therefore, the tests should do the same.
To be able to write a complete integration test in https://github.com/openfga/openfga/pull/2150.
=> test: use storage wrapper in Check unit tests

CHANGELOG.md, internal/graph/check.go, internal/graph/check_test.go
This PR removes the `optimizationsEnabled` gate from two check optimizations, [shortcutting based on path](https://github.com/openfga/openfga/pull/2104/files) and [recursive userset fast path](https://github.com/openfga/openfga/blob/main/internal/graph/check_fast_path.go#L1003)
=> chore: remove experimental flag from check shortcut and fast_path_v1

internal/cachecontroller/cache_controller.go, internal/cachecontroller/cache_controller_test.go, pkg/storage/cache.go, pkg/storage/storagewrappers/check_caching.go, pkg/storage/storagewrappers/check_caching_test.go
No new behavior here.
We had a method in our cache code which was returning `[]string` but that slice was hardcoded to a single element. This PR changes it to just return that string without a slice.
=> refactor: return string instead of one-element string slice

pkg/tuple/tuple.go
Came across a `fmt.sprintf` in the `tuple` package which we can make faster while maintaining readability by just concatenating strings.
I did a quick benchmark comparison:
```
func BenchmarkTupleStringifiers(b *testing.B) {
tupleKey := &openfgav1.TupleKey{
User:     "user:justin",
Relation: "viewer",
Object:   "doc:1",
}
b.Run("new_version", func(b *testing.B) {
for i := 0; i < b.N; i++ {
_ = TupleKeyToString(tupleKey)
}
})
}
```
Old:
New
Percentage-wise it's quite a bit faster, but we're talking nanoseconds here so 🤷 
We can actually make it significantly faster still (and remove all memory usage) if we specify an explicit type for this function to accept, rather than an interface, but that requires a refactor in other places and doesn't seem worth it for such small gains.
With explicit …
=> perf: remove fmt.sprintf and just add strings

CHANGELOG.md, go.mod, go.sum, pkg/server/batch_check_test.go
Updates `openfga/api` to include https://github.com/openfga/api/pull/222 with validation for the presence of `tuple_key` so that when not includes a `400` error is received rather than `200` with the validation error in each check result
`openfga/api` diff https://github.com/openfga/api/compare/c22e6db...f970913
=> fix: require tuple_key to exist in BatchCheckItem

pkg/server/test/check.go
Recently i've seen an uptick in failures in Check benchmark comparisons (not the runs themselves, just the comparison with `main`). I have a strong suspicion  this is because I recently added randomness to the order the tuples are written, which will mean that one run of the benchmark may be "lucky" in finding a response quickly, while other runs may not.
E.g. https://github.com/openfga/openfga/actions/runs/13003063201/job/36265167139?pr=2241
```
threshold 2
Error: # :warning: **Performance Alert** :warning:
Possible performance regression was detected for benchmark.
Benchmark result of this commit is worse than the previous benchmark result exceeding threshold `2`.
| Benchmark suite | Current: 2e5a5a04db13a5a739697b84da1141c7cb1f3e50 | Previous: b20e5580b80a0ea4579ad31d7e23175dd255fdc7 | …
```
=> test: fix benchmark alarm firing due to randomness

.golangci.yaml, CHANGELOG.md, internal/authz/authz.go, internal/mocks/mock_oidc_server.go, pkg/server/commands/batch_check_command.go, pkg/storage/cache.go, pkg/storage/storagewrappers/check_caching.go, pkg/storage/storagewrappers/model_caching.go, pkg/testfixtures/storage/mysql.go, pkg/testfixtures/storage/postgres.go, pkg/tuple/tuple.go, pkg/typesystem/resolver.go, pkg/typesystem/typesystem.go
This PR improves performance by optimizing string operations across the codebase.
Changes:
- Replace `fmt.Sprintf` with direct string concatenation using + operator
- Use `strconv.FormatBool` for boolean to string conversion
- Optimize `strings.Builder` usage in tuple operations
- Clean up imports in affected files
Performance impact:
These changes reduce allocations and CPU overhead by using more efficient string operations instead of fmt.Sprintf formatting.
address [this comment](https://github.com/openfga/openfga/pull/2238#pullrequestreview-2573629219) 😄
=> perf: Replace `fmt.Sprintf` with efficient string operations

.golangci.yaml, pkg/server/test/list_objects.go, pkg/server/test/list_users.go, tests/check/check.go
In https://github.com/openfga/openfga/pull/2241 I forgot to comment that `perfsprint` needs to be added to `.golangci.yaml` 😅 
Part of https://github.com/openfga/openfga/issues/598
=> chore: add perfsprint linter

CHANGELOG.md, pkg/server/server_test.go, pkg/storage/mysql/mysql.go, pkg/storage/mysql/mysql_test.go, pkg/storage/postgres/postgres.go, pkg/storage/postgres/postgres_test.go, pkg/storage/sqlcommon/sqlcommon.go, pkg/storage/sqlite/sqlite.go
Optimizes database dialect handling by setting it once during initialization.
Changes:
- Added dialect parameter to `sqlcommon.NewDBInfo`
- Moved `goose.SetDialect` call to initialization time
- Added dbInfo field to SQLite Datastore struct
- Updated MySQL, Postgres and SQLite implementations to pass correct dialect during initialization
- Updated test files to include dialect parameter in NewDBInfo calls
- Optimized error messages using string concatenation
Fixes #2251
=> fix: Set database dialect during initialization to prevent SQL syntax errors

tests/check/check_test.go
The `check_test` suite _sometimes_ has a goroutine leak on cleanup. The exact cause is still under investigation, but it is within [this code path](https://github.com/openfga/openfga/blob/main/pkg/storage/storagewrappers/context.go#L25) and related to how our iterator cache interacts with the DB during shutdown; that behavior is modified by the environment variable in this PR. I have a messy branch which reproduced the leak reliably [here](https://github.com/openfga/openfga/compare/main...data-race-debugging), but after making the change in this PR I have been unable to reproduce the leak again.
=> test: fix goroutine leak in check tests

pkg/typesystem/typesystem.go, tests/check/check_test.go
In #2259 we introduced a config change to our `check_test` suite to resolve some goroutine leaks in test. That PR resulted in issues causing a lock of the SQLite DB in the same test suite. This PR makes the config change _specific_ to only mysql tests while we investigate why this caused an issue with SQLite.
=> fix: resolve Sqlite test database locking issue

CHANGELOG.md, tests/check/check.go, tests/check/check_test.go
This PR is a small testing update and refactor of the check matrix tests. It updates the test suite to run against more datastores and also publicizes a `RunTestMatrix` method to allow for testing with any other engine that implements a `ClientInterface`
=> test: expose matrix tests publicly, run them against all datastores

CHANGELOG.md
Add `v1.8.5` release details to the CHANGELOG.
=> docs(v1.8.5): add v1.8.5 release notes to CHANGELOG

CHANGELOG.md, internal/cachecontroller/cache_controller.go
This PR adds an additional metric to track cache invalidation operations performed by the cache_controller.
=> feat: add `cachecontroller_cache_invalidation_count` metric

CHANGELOG.md, pkg/server/errors/errors.go, pkg/server/errors/errors_test.go, pkg/storage/errors.go
This PR adds new storage error `ErrTransactionThrottled` to our existing set of potential errors, and adjusts for it in our centralized `HandleError` helper function. This PR also reorders some of the cases in `HandleError` so that it evaluates the most-frequent cases first.
=> feat: add `storage.ErrTransactionThrottled` and associated server error

CHANGELOG.md
The Changelog entry in #2308 was added to the wrong section, this moves it up into `Unreleased`
=> docs: move shadowresolver changelog entry

tests/check/check.go, tests/check/check_ttu.go, tests/check/check_userset.go
Updating matrix tests for the following cases:
1. recursive userset with condition
2. recursive TTU with condition
3. mixture of parents in recursive TTU
=> test: adding matrix test for recursive userset and TTUs with condition

tests/check/check.go, tests/check/check_test.go, tests/listobjects/listobjects.go, tests/listusers/listusers.go, tests/tests.go
Consolidate matrix test infrastructure so that list objects matrix test can also use some of the check matrix infra.
=> tests: consolidate matrix test infrastucture

pkg/storage/test/tuples.go
Adding tests for ReadUsersetTuples that tests what happen for AllowedUserTypeRestrictions if there are wildcard as well as direct relation reference with same type.
=> test: adding test on AllowedUserTypeRestrictions for ReadUsersetTuples

tests/listobjects/matrix.go, tests/listobjects/matrix_directs.go
This PR moves the ListObjects assertion slice into its own file since we're about to be adding many more of them: my current plan is to create a new file per `type` we test in this model.
This also adds a new assertion for listObjects with a relation of weight 1 and a single terminal type (with conditions and wildcards).
=> tests: moves ListObjects matrix assertions and adds Weight1 wildcard test

tests/listobjects/matrix.go, tests/listobjects/matrix_directs.go
More ListObjects matrix testing, branched off of #2327
=> test: add ListObjects weight one directs multiple types test case

CHANGELOG.md
Add v1.8.8 release details to the CHANGELOG.  Note that originally the changelog has v1.8.8 but it is not released.
=> docs(v1.8.8): add v1.8.8 release notes to CHANGELOG

tests/listobjects/matrix_usersets.go
Listobjects test cases for `#tuple_cycle_len2_userset` relation
=> test: ListObjects tuple_cycle_len2_userset

pkg/server/server.go
Add comments to denote that shadow resolver is a temporary feature and may be removed in future release.
=> docs: make note that shadow resolver is a temporary feature

tests/listobjects/matrix_usersets.go
Adding list object matrix test for userset:userset_recursive_alg_combined_oneline
=> test: add list object userset_recursive_alg_combined_oneline test

tests/listobjects/matrix_ttus.go
Matrix test for ListObjects `ttus#ttu_recursive_combined_w3`
=> test: ListObjects ttus#ttu_recursive_combined_w3

tests/listobjects/matrix_usersets.go
Adding list object matrix test for userset_recursive_alg_combined
=> test: list objects matrix userset_recursive_alg_combined

tests/listobjects/matrix_usersets.go
Adding matrix test for list object's tuple_cycle_len3 for userset type.
=> test: list object matrix with userset tuple_cycle_len3

CHANGELOG.md, pkg/server/check.go, pkg/server/commands/check_command.go, pkg/server/commands/check_command_test.go
Capture dispatch count, datastore query count, and if the request was throttled even when an error exists and/or the context deadline is exceeded.
For example, given a complex query and dispatch throttling enabled, the log line for `grpc_req_complete`:
**Before**
```
{"grpc_service": "openfga.v1.OpenFGAService", "grpc_method": "Check", "grpc_type": "unary", "trace_id": "29a1aa6b34009d3b4ece15baadaa4a8b", "user_agent": "openfga-cli/dev", "raw_request": {"store_id":"01JRE4QDT4X4JB95TD482GCAQN","tuple_key":{"user":"user:maria","relation":"viewer_complex","object":"folder:x"},"contextual_tuples":{"tuple_keys":[]},"authorization_model_id":"","trace":false,"context":{},"consistency":"UNSPECIFIED"}, "raw_response": {"code":"throttled_timeout_error","message":"timeout due to throttling on complex …
```
=> Surface partial metrics on check resolutions

CHANGELOG.md, internal/graph/check.go, internal/graph/check_fast_path.go, internal/graph/check_test.go, internal/graph/object_providers.go, internal/graph/object_providers_test.go
Add limit on goroutine concurrency limit when processing iterator.
This avoids high number of goroutine usage and avoids saturation
in datastore usage when the number of tuple iterators processed for
a check / list objects / list users request is high.
=> fix: add goroutine concurrency limit for iterator processing

internal/shared/shared.go, internal/shared/shared_test.go, pkg/server/commands/batch_check_command.go, pkg/server/commands/check_command.go, pkg/server/commands/check_command_test.go, pkg/server/server.go, pkg/storage/storagewrappers/request.go, pkg/storage/storagewrappers/request_test.go
We're currently working on adding the iterator cache into the ListObjects flow, and it will also be reusing these resources. I pulled the renaming diff into its own PR so it doesn't complicate the ListObjects caching PR which is coming soon.
No change in behavior here, just a rename.
=> refactor: rename sharedCheckResources -> sharedDatastoreResources

pkg/storage/storagewrappers/cached_datastore.go
Previous to this change, the `openfga_tuples_cache_discard_count` metric was only incremented when discarding tuples as part of draining an iterator when calling `.Stop()`. Tuples buffered for caching during `.Next()` can also be discarded after the maximum result size is reached.
This pull request introduces a minor enhancement to the `cachedIterator` implementation in `pkg/storage/storagewrappers/cached_datastore.go`. It adds a metric to track discarded tuples when the maximum result size is reached.
Metrics improvement:
* [`pkg/storage/storagewrappers/cached_datastore.go`](diffhunk://#diff-82cf5bfde2c5cec1b2ded64b56724a635b979199401e0ce5303b093473d89443R486): Incremented the `tuplesCacheDiscardCounter` metric with the operation label whenever the tuple cache is discarded due to …
=> fix: increase discard count on `.Next()`

pkg/testfixtures/storage/mysql.go, pkg/testfixtures/storage/postgres.go
Speed up the process of starting a test fixture container for `mysql` and `postgres`.
When searching local docker images for a `mysql` or `postgres` image, the code currently iterates through all images, even after the desired image is found. This is a tiny optimization to ensure that the `break` statement actually breaks out of the outer loop and not the inner loop.
=> test: add loop break optimization for test fixtures

CHANGELOG.md, pkg/storage/storagewrappers/cached_datastore.go, pkg/storage/storagewrappers/cached_iterators.go
Add counters on current number of iterator cache as gauge.
Purposely not calling Stop
=> feat: add counters on current number of iterator cache

CHANGELOG.md, Dockerfile, Dockerfile.goreleaser, go.mod
=> chore: update go version to 1.24.2

CHANGELOG.md, pkg/storage/storagewrappers/cached_datastore.go, pkg/storage/storagewrappers/cached_iterators.go
Update logic for `current_iterator_cache_count` so that it handles case where iterator stop more than once correctly.  Otherwise, the gauge counter can go into negative when the same iterator is stopped more than once.
=> fix: current_iterator_cache_count account for iter stop more than once

CHANGELOG.md, internal/graph/check_fast_path.go, internal/graph/check_fast_path_test.go, internal/graph/object_providers.go, internal/graph/object_providers_test.go, internal/iterator/fan_in.go, internal/iterator/fan_in_test.go
Move draining of `fanin.out` channel to consumers rather than itself to prevent race conditions.
Make draining be completely in deferred goroutines.
Change `fanin.Add` to return if new channel is accepted, and handle it's draining if rejected at the client.
Fix bug in `breadthFirstRecursiveMatch` where `fanin.Stop` was not being called as early as possible in the case of recurssion.
=> fix: fanin draining across clients

CHANGELOG.md, internal/throttler/throttler.go
This change should prevent Go routines from remaining throttled after the request context has been canceled. In the event that the Go routine is release from throttling after the request context has been canceled, or deadline has exceeded, the `LocalChecker` will check the status of the context and bail if the context contains an error.
=> fix: watch context when dispatch throttling

.golangci.yaml, pkg/server/commands/expand_test.go, pkg/server/commands/list_objects_test.go
As part of #598 , it is desired to include additional linters as part of the golangci config. This PR adds one of the mentioned linters `fatcontext` and addresses applicable lints
#598
=> chore: add fatcontext linter

.golangci.yaml, cmd/run/run_test.go, internal/checkutil/checkutil_test.go, internal/graph/cached_resolver_test.go, internal/graph/check_test.go, pkg/server/commands/expand.go, pkg/server/commands/listusers/list_users_rpc.go, pkg/server/commands/listusers/list_users_rpc_test.go, pkg/server/config/config_test.go, pkg/server/test/list_objects.go, pkg/tuple/tuple_test.go, pkg/typesystem/typesystem_test.go, tests/check/check.go, tests/functional_test.go, tests/listobjects/listobjects.go, tests/listusers/listusers.go
As part of #598  , it is desired to include additional linters as part of the golangci config. This PR adds one of the mentioned linters copyloopvar and addresses applicable lints.
#598
=> chore: add copyloopvar linter

pkg/server/server_test.go, pkg/storage/mysql/mysql.go, pkg/storage/mysql/mysql_test.go, pkg/storage/postgres/postgres.go, pkg/storage/postgres/postgres_test.go, pkg/storage/sqlcommon/sqlcommon.go, pkg/storage/sqlite/sqlite.go, pkg/storage/sqlite/tuple_iterator.go
Normalizes the usage of `SQLHandleError` across sqlcommon and sqlite and start using it on the tuple iterators.
Fix minor locking handling.
Fix minor errors that cause flaky tests.
=> fix: refactor handlesqlerror and minor fixes

CHANGELOG.md, cmd/migrate/migrate.go, cmd/migrate/migrate_test.go, pkg/storage/migrate/migrate.go, pkg/storage/migrate/migrate_test.go
feat: Expose `RunMigrations()` for library migration management
**Problem:** Grafana, embedding OpenFGA as a library, faces challenges with divergent database migration approaches. OpenFGA uses `goose`, while Grafana's migrator runs once, potentially skipping future OpenFGA schema updates and preventing versioned upgrades.
**Solution:** Utilize `RunMigrations()` from cmd for reliable schema management.
**Changes:**
* Introduces `MigrationConfig` struct.
* Adds `RunMigrations(cfg MigrationConfig) error` function to the library.
* Updates CLI `runMigration` to use the new library function.
This provides any organization that uses openFGA as a library with a method to manage OpenFGA database migrations.
Example:
```go
import "github.com/openfga/openfga/pkg/storage/migrate"
// Then use it
err …
```
=> feat: expose `RunMigration` from `cmd`

pkg/storage/storagewrappers/sharediterator/shared_iterator_datastore.go, pkg/storage/storagewrappers/sharediterator/shared_iterator_datastore_test.go, tests/check/check_test.go, tests/tests.go
1. In the case of context cancelled error, do not store this error as this error is only specific to the request and has no bearing on the actual datastore connection.
2. Update matrix + test suite to use shared iterator.
=> fix: shared iterator should not store context cancelled error

CHANGELOG.md, internal/graph/object_providers.go, internal/graph/object_providers_test.go
With enable-check-optimizations enabled, check for a model with recursive tuple to userset model may be incorrect if the user is assigned to more than 100 different groups due to iteratorToUserset not handline multiple messages correctly.
=> fix: iteratorToUserset with multiple messages

CHANGELOG.md, pkg/storage/storagewrappers/context.go
Our storage implementation needs access to context elements that are not currently propagated.
As I understand it, the need for the new context was to avoid the cancel propagation (or, more precisely, the timeout).
It is possible to use directly [context.WithoutCancel](https://pkg.go.dev/context#WithoutCancel) (available since go 1.21) which preserve everything else.
=> fix: storage context wrapper preserve context without cancel

CHANGELOG.md, pkg/storage/migrate/migrate.go
We used to have https://github.com/openfga/openfga/blob/5f720784ae7c637bc9a9ae8a18adc230982aba50/cmd/migrate/migrate.go#L64-L65
Then the regression was introduced in https://github.com/openfga/openfga/pull/2442, where we set https://github.com/openfga/openfga/blob/a3cae63e511715c91198673a1a72e7b0facc8168/pkg/storage/migrate/migrate.go#L69 to empty string initiation.
We now evaluate the following priority:
- If `--datastore-username` is provided, use
- If `--datastore-password` is provided, use
- Otherwise: fall back to URI credentials
Maintains same behavior as MySQL case, and tested on mysql
Fixes:
https://github.com/openfga/openfga/issues/2493
=> fix: regression of empty string initiation for `migrate` pkg

CHANGELOG.md
Add v1.8.15 release details to the CHANGELOG.
=> docs(v1.8.15): add v1.8.15 release notes to CHANGELOG

CHANGELOG.md, pkg/storage/sqlite/sqlite.go, pkg/storage/sqlite/tuple_iterator.go
With the fix introduced https://github.com/openfga/openfga/pull/2508 the test suite for SQLite moving to async passes consistently.
=> Move SQLite to lazy iterators

pkg/storage/storagewrappers/sharediterator/shared_iterator_datastore.go
There is currently a race condition in the shared iterator `await` structure where a read of its `wg` property can collide with a write to it.
Only access the data while a lock is held.
Instead of calling `Wait()` directly on the property, I first create a copy of the value before unlocking the mutex, and then call `Wait()` on the copy.
Line 578 still accesses `a.wg` outside of a mutex lock; however it is not possible for another goroutine to write to `a.wg` at this point.
=> fix data race around wait group in shared iterator

CHANGELOG.md
This PR updates the changelog in preparation for releasing `v1.9.6`.
=> Update changelog to prep for release `1.9.6`
